### ISSUE TITLE
[BUG]: Calibre fails to connect, indicating the response ended prematurely.

### ISSUE THREAD

**Issue by ACiDGRiM** [Readarr/Readarr#1189]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I load the url in the error, I get a json? output, so calibre seems to be working.
For the record, this _did_ work until recently as I have several books from readarr in calibre. calibre is running as an HTTP container behind a traefik proxy that does https to the outside world.

I'm able to load calibre user web interface without issue.

`Unknown error occured in CalibreRootFolderCheck HealthCheck: An error occurred while sending the request.: 'https://calibre.domain.net/ajax/books/library?ids=1812%2C1722%2C1713%2C1052%2C1004%2C992%2C991%2C990%2C989%2C988%2C987%2C986%2C985%2C984%2C983%2C982%2C981%2C980%2C979%2C978%2C977%2C976%2C975%2C974%2C973%2C972%2C971%2C970%2C969%2C968%2C967%2C966%2C964%2C963%2C962%2C961%2C960%2C959%2C958%2C957%2C956%2C955%2C954%2C953%2C952%2C951%2C950%2C844%2C764%2C600%2C579%2C550%2C497%2C455%2C446%2C395%2C331%2C319%2C309%2C254%2C252%2C243%2C242%2C241%2C240%2C239%2C238%2C237%2C236%2C235%2C234%2C233%2C232%2C231%2C230%2C227%2C225%2C224%2C223%2C222%2C221%2C220%2C213%2C212%2C210%2C209%2C208%2C206%2C205%2C204%2C202%2C201%2C200%2C199%2C198%2C197%2C196%2C195%2C194%2C193%2C192%2C191%2C190%2C189%2C188%2C187%2C186%2C185%2C184%2C183%2C182%2C181%2C180%2C179%2C178%2C177%2C176%2C175%2C174%2C173%2C172%2C171%2C170%2C169%2C168%2C167%2C166%2C165%2C164%2C163%2C162%2C161%2C160%2C159%2C158%2C157%2C156%2C155%2C154%2C153%2C152%2C151%2C150%2C149%2C148%2C147%2C146%2C145%2C144%2C143%2C142%2C141%2C140%2C139%2C138%2C137%2C136%2C135%2C134%2C133%2C132%2C131%2C130%2C129%2C128%2C127%2C126%2C125%2C124%2C123%2C122%2C121%2C120%2C119%2C118%2C117%2C116%2C115%2C114%2C113%2C112%2C111%2C108%2C107%2C105%2C104%2C103%2C101%2C99%2C97%2C96%2C95%2C93%2C92%2C90%2C89%2C88%2C87%2C86%2C85%2C84%2C83%2C82%2C81%2C80%2C79%2C78%2C77%2C76%2C75%2C74%2C73%2C72%2C71%2C70%2C69%2C68%2C67%2C66%2C65%2C64%2C62%2C61%2C60%2C59%2C58%2C57%2C56%2C55%2C54%2C53%2C52%2C50%2C49%2C48%2C47%2C46%2C45%2C44%2C43%2C42%2C41%2C40%2C38%2C37%2C36%2C35%2C33%2C32%2C31%2C29%2C28%2C27%2C26%2C25%2C22%2C21%2C20%2C18%2C17%2C16%2C15%2C14%2C13%2C12%2C11%2C10%2C9%2C8%2C7%2C6%2C5%2C4%2C3%2C1'
`

```
System.Net.WebException: An error occurred while sending the request.: 'https://calibre.domain.net/ajax/books/library?ids=1812%2C1722%2C1713%2C1052%2C1004%2C992%2C991%2C990%2C989%2C988%2C987%2C986%2C985%2C984%2C983%2C982%2C981%2C980%2C979%2C978%2C977%2C976%2C975%2C974%2C973%2C972%2C971%2C970%2C969%2C968%2C967%2C966%2C964%2C963%2C962%2C961%2C960%2C959%2C958%2C957%2C956%2C955%2C954%2C953%2C952%2C951%2C950%2C844%2C764%2C600%2C579%2C550%2C497%2C455%2C446%2C395%2C331%2C319%2C309%2C254%2C252%2C243%2C242%2C241%2C240%2C239%2C238%2C237%2C236%2C235%2C234%2C233%2C232%2C231%2C230%2C227%2C225%2C224%2C223%2C222%2C221%2C220%2C213%2C212%2C210%2C209%2C208%2C206%2C205%2C204%2C202%2C201%2C200%2C199%2C198%2C197%2C196%2C195%2C194%2C193%2C192%2C191%2C190%2C189%2C188%2C187%2C186%2C185%2C184%2C183%2C182%2C181%2C180%2C179%2C178%2C177%2C176%2C175%2C174%2C173%2C172%2C171%2C170%2C169%2C168%2C167%2C166%2C165%2C164%2C163%2C162%2C161%2C160%2C159%2C158%2C157%2C156%2C155%2C154%2C153%2C152%2C151%2C150%2C149%2C148%2C147%2C146%2C145%2C144%2C143%2C142%2C141%2C140%2C139%2C138%2C137%2C136%2C135%2C134%2C133%2C132%2C131%2C130%2C129%2C128%2C127%2C126%2C125%2C124%2C123%2C122%2C121%2C120%2C119%2C118%2C117%2C116%2C115%2C114%2C113%2C112%2C111%2C108%2C107%2C105%2C104%2C103%2C101%2C99%2C97%2C96%2C95%2C93%2C92%2C90%2C89%2C88%2C87%2C86%2C85%2C84%2C83%2C82%2C81%2C80%2C79%2C78%2C77%2C76%2C75%2C74%2C73%2C72%2C71%2C70%2C69%2C68%2C67%2C66%2C65%2C64%2C62%2C61%2C60%2C59%2C58%2C57%2C56%2C55%2C54%2C53%2C52%2C50%2C49%2C48%2C47%2C46%2C45%2C44%2C43%2C42%2C41%2C40%2C38%2C37%2C36%2C35%2C33%2C32%2C31%2C29%2C28%2C27%2C26%2C25%2C22%2C21%2C20%2C18%2C17%2C16%2C15%2C14%2C13%2C12%2C11%2C10%2C9%2C8%2C7%2C6%2C5%2C4%2C3%2C1'
 ---> System.Net.WebException: An error occurred while sending the request.
 ---> System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The response ended prematurely.
   at System.Net.Http.HttpConnection.FillAsync(Boolean async)
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean async, Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithNtAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean isProxyAuth, HttpConnection connection, HttpConnectionPool connectionPool, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.SocketsHttpHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DelegatingHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClientHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.HttpWebRequest.SendRequest(Boolean async)
   at System.Net.HttpWebRequest.GetResponse()
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in D:\a\1\s\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 147
   --- End of inner exception stack trace ---
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in D:\a\1\s\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 147
   at NzbDrone.Common.Http.HttpClient.ExecuteRequest(HttpRequest request, CookieContainer cookieContainer) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 124
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 57
   at NzbDrone.Common.Http.HttpClient.Get[T](HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 249
   at NzbDrone.Core.Books.Calibre.CalibreProxy.GetAllBookFilePaths(CalibreSettings settings) in D:\a\1\s\src\NzbDrone.Core\Books\Calibre\CalibreProxy.cs:line 346
   at NzbDrone.Core.HealthCheck.Checks.CalibreRootFolderCheck.Check() in D:\a\1\s\src\NzbDrone.Core\HealthCheck\Checks\CalibreRootFolderCheck.cs:line 52
```

### Expected Behavior

Readarr connects to calibre to manage the library

### Steps To Reproduce

1. Setup Calibre docker container
2. configure traefik HTTPS proxy
3. setup radarr install on a separate server
4. Connect radarr to calibre using the https:// address

### Environment

```markdown
- OS: Centos 8
- Readarr: 0.1.0.919
- Docker Install: no
- Using Reverse Proxy: yes
- Browser: Brave Version 1.27.111 Chromium: 92.0.4515.131 (Official Build) (64-bit)
```

### What branch are you running?

Nightly

### Anything else?

Yes, I did search for this issue. currently I have 400 books in queue waiting for calibre to become available.

[AB#1424](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1424)

**Comment by bakerboy448** [comment]
`latest` / `latest nightly` is not a valid version.

system -> status for that.

Highly suspect this is an issue with the reverse proxy and not readarr.  The proxy is probably killing the connection before it completes.

if this is all on the same server or LAN then there is no need to go through the reverse proxy as that adds an unnecessary, single point of failure in the connection stack; in addition to various other issues such as timeouts as size limits.

**Comment by ACiDGRiM** [comment]
Sorry you're right, I was being lazy, I've updated that field, sorry for being a dummy.

The reason that I have to use the reverse proxy, calibre is running in my private cloud I run, and readarr is hosted in my seedbox.
I haven't had other issues with the reverse proxy, I run a number of other high bandwidth services through it, such as nextcloud.
I'm also able to load the calibre library over the internet, my physical location is about 45ms away from where calibre is located, and the seedbox is 130ms away from calibre.

Furthermore, I run an SSH portforward proxy from my cloud to my seedbox so I can access readarr, sonarr, etc... using a local LAN IP, and I do not have any issues at all with connectivity. so the ~150ms distance doesn't seem to be an issue. I also have no problems with sonarr/radarr/lidarr updating my plex server when the library changes.

I guess this could be a calibre defect, but before I reset and rebuild my library, I'm curious if there is something to be done in readarr.

**Comment by bakerboy448** [comment]
ping distance has nothing to do with what I said?
all that confirms is that your ping times are reasonable so they would not be causing a timeout due to ping distance.

something - likely your proxy - is terminating the request prior to calibre responding with everything.  this is likely either a timeout within the proxy or a response size limit.

**Comment by ACiDGRiM** [comment]
I think the rush to blame the proxy was a bit premature.
I found that the timeout setting for Calibre was 37 seconds, and if I set the max books to return to something rediculus like 5000 so all 300 books would be loaded in the webui, it would reply with a timeout.

I increased the number of workers and the timeout to 2 minutes and this issue is improved, however reading the files is very slow. It's been processing a rescan for the last two hours, however I can manipulate/rescan the calibre library manually and load all books within a few minutes without issue.

Maybe some documentation on proper settings for calibre would be helpful, however readarr's method of requesting data from calibre in one large request may need to be changed to request the book library in reasonable segments so it plays better with various calibre settings.

**Comment by NotExpectedYet** [comment]
@ACiDGRiM Thanks for pointing that out, had the same issue myself.
