### ISSUE TITLE
[BUG]: Permissions issue with mounted smb shares

### ISSUE THREAD

**Issue by zachsteffens** [Readarr/Readarr#1199]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

attempt to import and get message 
```
[Warn] ImportApprovedBooks: Couldn't import book /downloads/completed/Audiobooks/112263/112263-Part35.mp3 
[v0.1.0.935] System.UnauthorizedAccessException: Access to the path is denied.
```

also seeing Warning message in the status UI that says 

> Readarr can see but not access downloaded track ..... Likely permissions error.

I have everything set up identically to Sonarr and Radar which work properly, same PUID, PGID, and UMASK. Similar source and destination directories.

When I watch the directory that the books will be moved to, it appears that the files does finish importing, but then disappears 
for instance, if this book contains 5 parts. I'll see each of the 5 parts appear in the destination directory as the process is running.  As these show up, they appear to have finished (the full file size is listed in the destination directory but this could be misleading) but then the file disappears and the next part appears.  When the process completes, sometimes that last item in the process remains in place in the destination directory sometimes it's not.

I went nuclear and all directories and files have permissions of 777

### Expected Behavior

Import (hardlink/copy or Move) to work properly from/to smb mounted drives

### Steps To Reproduce

/books dir: smb share
/downloads dir: smb share

Manual -> Interactive Import
Select book to be imported.
Either Hardlink/copy or Move files- same result for both.
Click Import

Import fails.

### Environment

```markdown
- OS: Ubuntu 20.04
- Readarr: 0.1.0.935
- Docker Install:Yes
- Using Reverse Proxy: No
- Browser:Not ui related
```

### What branch are you running?

Nightly

### Anything else?

```
[Info] ImportApprovedBooks: Importing book 1/1 [15553789][Eleven twenty-two sixty-three] 


[Info] ImportApprovedBooks: Importing 35 files 


[Warn] ImportApprovedBooks: Couldn't import book /downloads/112263/112263-Part14.mp3 




[v0.1.0.935] System.UnauthorizedAccessException: Access to the path is denied.


 ---> System.IO.IOException: Operation not permitted


   --- End of inner exception stack trace ---


   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)


   at Interop.CheckIo(Int64 result, String path, Boolean isDirectory, Func`2 errorRewriter)


   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)


   at NzbDrone.Common.Disk.DiskProviderBase.CopyFile(String source, String destination, Boolean overwrite) in D:\a\1\s\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 241


   at NzbDrone.Common.Disk.DiskTransferService.TryCopyFileVerified(String sourcePath, String targetPath, Int64 originalSize) in D:\a\1\s\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 488


   at NzbDrone.Common.Disk.DiskTransferService.TransferFile(String sourcePath, String targetPath, TransferMode mode, Boolean overwrite) in D:\a\1\s\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 297


   at NzbDrone.Core.MediaFiles.BookFileMovingService.TransferFile(BookFile bookFile, Author author, Book book, String destinationFilePath, TransferMode mode) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\BookFileMovingService.cs:line 139


   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeBookFile(BookFile bookFile, LocalBook localBook, Boolean copyOnly) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\UpgradeMediaFileService.cs:line 105


   at NzbDrone.Core.MediaFiles.BookImport.ImportApprovedBooks.Import(List`1 decisions, Boolean replaceExisting, DownloadClientItem downloadClientItem, ImportMode importMode) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\BookImport\ImportApprovedBooks.cs:line 198
```

[AB#1457](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1457)

**Comment by bakerboy448** [comment]
Can reopen if it is in fact a bug, but much more likely to be a config issue; let's troubleshoot on Reddit/discord first
