### ISSUE TITLE
[BUG]: Error occurred while executing task ImportListSync

### ISSUE THREAD

**Issue by DoubtfulTurnip** [Readarr/Readarr#1235]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Unable to sync import list via Goodreads

### Expected Behavior

ImportListSync expected to correctly import all books from Goodreads

### Steps To Reproduce

Have configured Import lists
This did work the first time it was run but has since stopped

### Environment

```markdown
- OS: Ubuntu 20.04 
- Readarr:
Version
0.1.0.963
Package Version
nightly-04e673f by hotio 
.NET Core
Yes (5.0.8)
Docker
Yes
- Docker Install: hotio/readarr:nightly
- Using Reverse Proxy: NPM
- Browser: Firefox
```

### What branch are you running?

Nightly

### Anything else?

Log
`2021-09-17 17:49:44.9|Error|CommandExecutor|Error occurred while executing task ImportListSync

[v0.1.0.963] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.ImportLists.ImportListSyncService.ProcessBookReport(ImportListDefinition importList, ImportListItemInfo report, List`1 listExclusions, List`1 booksToAdd, List`1 authorsToAdd)
   at NzbDrone.Core.ImportLists.ImportListSyncService.ProcessReports(List`1 reports) in D:\a\1\s\src\NzbDrone.Core\ImportLists\ImportListSyncService.cs:line 107
   at NzbDrone.Core.ImportLists.ImportListSyncService.SyncAll() in D:\a\1\s\src\NzbDrone.Core\ImportLists\ImportListSyncService.cs:line 66
   at NzbDrone.Core.ImportLists.ImportListSyncService.Execute(ImportListSyncCommand message) in D:\a\1\s\src\NzbDrone.Core\ImportLists\ImportListSyncService.cs:line 361
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 116
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 42`

Debug
`2021-09-17 17:49:44.9|Error|CommandExecutor|Error occurred while executing task ImportListSync

[v0.1.0.963] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.ImportLists.ImportListSyncService.ProcessBookReport(ImportListDefinition importList, ImportListItemInfo report, List`1 listExclusions, List`1 booksToAdd, List`1 authorsToAdd)
   at NzbDrone.Core.ImportLists.ImportListSyncService.ProcessReports(List`1 reports) in D:\a\1\s\src\NzbDrone.Core\ImportLists\ImportListSyncService.cs:line 107
   at NzbDrone.Core.ImportLists.ImportListSyncService.SyncAll() in D:\a\1\s\src\NzbDrone.Core\ImportLists\ImportListSyncService.cs:line 66
   at NzbDrone.Core.ImportLists.ImportListSyncService.Execute(ImportListSyncCommand message) in D:\a\1\s\src\NzbDrone.Core\ImportLists\ImportListSyncService.cs:line 361
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 116
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 42
`

Trace
`2021-09-17 17:49:44.9|Trace|CommandQueueManager|Updating command status
2021-09-17 17:49:44.9|Trace|EventAggregator|Publishing CommandUpdatedEvent
2021-09-17 17:49:44.9|Trace|EventAggregator|CommandUpdatedEvent -> CommandController
2021-09-17 17:49:44.9|Trace|EventAggregator|CommandUpdatedEvent <- CommandController
2021-09-17 17:49:44.9|Trace|EventAggregator|Publishing CommandExecutedEvent
2021-09-17 17:49:44.9|Trace|EventAggregator|CommandExecutedEvent -> TaskManager
2021-09-17 17:49:44.9|Trace|TaskManager|Updating last run time for: NzbDrone.Core.ImportLists.ImportListSyncCommand
2021-09-17 17:49:44.9|Trace|EventAggregator|CommandExecutedEvent <- TaskManager
2021-09-17 17:49:44.9|Trace|EventAggregator|CommandExecutedEvent -> TaskController
2021-09-17 17:49:44.9|Trace|EventAggregator|CommandExecutedEvent <- TaskController
2021-09-17 17:49:44.9|Trace|CommandExecutor|ImportListSyncCommand <- ImportListSyncService [00:00:25.3621856]
2021-09-17 17:49:44.9|Error|CommandExecutor|Error occurred while executing task ImportListSync

[v0.1.0.963] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.ImportLists.ImportListSyncService.ProcessBookReport(ImportListDefinition importList, ImportListItemInfo report, List`1 listExclusions, List`1 booksToAdd, List`1 authorsToAdd)
   at NzbDrone.Core.ImportLists.ImportListSyncService.ProcessReports(List`1 reports) in D:\a\1\s\src\NzbDrone.Core\ImportLists\ImportListSyncService.cs:line 107
   at NzbDrone.Core.ImportLists.ImportListSyncService.SyncAll() in D:\a\1\s\src\NzbDrone.Core\ImportLists\ImportListSyncService.cs:line 66
   at NzbDrone.Core.ImportLists.ImportListSyncService.Execute(ImportListSyncCommand message) in D:\a\1\s\src\NzbDrone.Core\ImportLists\ImportListSyncService.cs:line 361
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 116
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 42`

[AB#1589](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1589)

**Comment by DoubtfulTurnip** [comment]
This appears to be happening with new books that have been added within Goodreads. If I remove recently added books from the Goodreads list then the import completes successfully.

As an example, after adding a book to the Goodreads list:

`2021-09-18 10:34:03.4|Debug|GoodreadsProxy|Getting Book with GoodreadsId of 233667
2021-09-18 10:34:03.4|Debug|ImportListSyncService|233667 [Firestarter] Rejected, Book Exists in DB.  Ensuring Book and Author monitored.
2021-09-18 10:34:03.4|Debug|GoodreadsProxy|Getting Book with GoodreadsId of 34527
2021-09-18 10:34:03.5|Debug|ImportListSyncService|34527 [Feet of Clay] Rejected, Book Exists in DB.  Ensuring Book and Author monitored.
2021-09-18 10:34:03.5|Debug|GoodreadsProxy|Getting Book with GoodreadsId of 7923163
2021-09-18 10:34:03.5|Debug|ImportListSyncService|7923163 [Mogworld] Rejected, Book Exists in DB.  Ensuring Book and Author monitored.
2021-09-18 10:34:03.5|Debug|GoodreadsProxy|Getting Book with GoodreadsId of 10256723
**2021-09-18 10:34:03.5|Debug|ImportListSyncService|10953 [Kevin D. Mitnick] Rejected, Author Exists in DB.  Ensuring Author monitored
2021-09-18 10:34:03.5|Error|CommandExecutor|Error occurred while executing task ImportListSync

[v0.1.0.963] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.ImportLists.ImportListSyncService.ProcessBookReport(ImportListDefinition importList, ImportListItemInfo report, List`1 listExclusions, List`1 booksToAdd, List`1 authorsToAdd)
   at NzbDrone.Core.ImportLists.ImportListSyncService.ProcessReports(List`1 reports) in D:\a\1\s\src\NzbDrone.Core\ImportLists\ImportListSyncService.cs:line 107
   at NzbDrone.Core.ImportLists.ImportListSyncService.SyncList(ImportListDefinition definition) in D:\a\1\s\src\NzbDrone.Core\ImportLists\ImportListSyncService.cs:line 77
   at NzbDrone.Core.ImportLists.ImportListSyncService.Execute(ImportListSyncCommand message) in D:\a\1\s\src\NzbDrone.Core\ImportLists\ImportListSyncService.cs:line 357
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 116
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 42**

`

Monitor is set to specific book in the import list settings

**Comment by ta264** [comment]
I think this is the same as an issue we discussed on discord, hopefully a fix arriving in the next few days

**Comment by DoubtfulTurnip** [comment]
I have just found the discussion you have mentioned. Happy to wait for the fix. Thanks!
