### ISSUE TITLE
[BUG]: Manual import fails

### ISSUE THREAD

**Issue by arg** [Readarr/Readarr#1238]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm trying to manually import several EPUBs downloaded via Prowlarr+Transmission combo. Previously book data was added to Readarr via GoodReads integration (in English) but the actual EPUBs are in Russian. Apparently this happens only when downloaded EPUBs can't be automatically imported due to Russian<->English name mismatch.

### Expected Behavior

EPUBs are imported successfully.

### Steps To Reproduce

1. Enable GoodReads Bookshelves integration
2. Import books data from GoodReads shelves
3. Navigate to Library->Authors
4. Open some author's page
5. Select any book
6. Navigate to Search page
7. Select any result
8. Click "Add to downloaded queue"
   ![1](https://user-images.githubusercontent.com/1044277/134141598-93dfa721-b9e2-44b1-aad0-35ece9f52883.png)
9. Wait till book is downloaded
10. Navigate to Activity->Queue
11. Click "Manual import" icon
   ![2](https://user-images.githubusercontent.com/1044277/134141720-ab877526-d59d-4fd7-a2ca-1c977c923dd8.png)
12. Select the EPUB
   ![3](https://user-images.githubusercontent.com/1044277/134141839-2bd860cb-eb7d-451e-8cff-156b90256b79.png)
13. Set book name from the list
   ![4](https://user-images.githubusercontent.com/1044277/134141940-9450adc1-2d79-457b-80d6-3d5d72d72d61.png)
14. Click "Import"
   ![5](https://user-images.githubusercontent.com/1044277/134142052-fa4185fc-95c1-4bc9-b9ba-e6098647ca96.png)

Import fails with message:

```
Message
Error occurred while executing task ManualImport: Book with id  was not found, it may have been removed from metadata server.

Exception
NzbDrone.Core.Exceptions.BookNotFoundException: Book with id  was not found, it may have been removed from metadata server.
   at NzbDrone.Core.MetadataSource.Goodreads.GoodreadsProxy.GetBookInfo(String foreignEditionId, Boolean useCache) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\Goodreads\GoodreadsProxy.cs:line 361
   at NzbDrone.Core.MediaFiles.BookImport.Manual.ManualImportService.Execute(ManualImportCommand message) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\BookImport\Manual\ManualImportService.cs:line 311
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 116
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 42
```

![6](https://user-images.githubusercontent.com/1044277/134142192-bd38f40e-4fb4-4d78-93fa-44c3fb979c81.png)

### Environment

```markdown
- OS: Synology DSM 7.0
- Readarr:0.1.0.968-ls7 by linuxserver.io
- Docker Install: Yes
- Using Reverse Proxy: Yes, DSM
- Browser: Any
```

### What branch are you running?

Nightly

### Anything else?

Probably related to https://github.com/Readarr/Readarr/issues/424

[AB#1599](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1599)

**Comment by ta264** [comment]
Please come by the discord channel to help debug this.  This issue has been reported a few times but I've never been able to replicate. https://readarr.com/discord

**Comment by Justanotherhomosapien** [comment]
Same problem here, although without GoodReads integration. Manual import of a file that automatic import decides is not a close enough match.

[v0.1.0.968] NzbDrone.Core.Exceptions.BookNotFoundException: Book with id  was not found, it may have been removed from metadata server.

**Comment by Yann-J** [comment]
Facing the same error very regularly when trying to import unmapped files - although for Audiobooks.
Some books just don't want to import...
Also happens when trying manual import from a finished download, although that seems less frequent.

**Comment by bakerboy448** [comment]
Like Ta said - have not been able to replicate, come by discord to troubleshoot

[Discord](http://readarr.com/discord)

**Comment by Yann-J** [comment]
I sure did of course, but thought it might be useful to chime in here to mention it's affecting more folks.

As far as I could see in the discord, the main recommendation was to wipe and reinstall, which I did... and faced the same issue again.

After fighting this most of the weekend, I've reached a few conclusions:

* First, I'm almost certain that the `Book with id  was not found` is caused by clicking too fast on the Import button after selecting a book to import the files to. When the book is properly guessed automatically, the issue does not appear, probably because the book id is already known by the UI. However if we have to select a book, I can see the log entry `[Info] IdentificationService: Identifying book 1/1` on the server firing off after the selection - I'm guessing that the UI needs this to complete (but I don't actually get feedback on the completion from the server logs, so I'm just speculating here). Anyway the bottomline is that, if I wait a bit before clicking Import, I'm not seeing the issue. The only UI feedback we get that the book id is retrieved, is that books that have warnings ("match < 80%", "another file with same size" etc...) will show the warning icon, but if there's no warning, we don't have any UI feedback that the book identification is completed. Looking at the network logs, I suspect we just need to wait for the response to the `PUT api/v1/manualimport` call that seems to return the book details (but the book name and import button are available before we get a response)
* Technically unrelated, but still heavily impacting the manual import experience, is that unfortunately, the vast majority of the time (though not always), these manual imports only succeed for one of the selected files (random). There's no log entry indicating any problem, including in `trace` level, the import really just seems to stop after the first processed file of the batch... The logs will say "Importing 22 files", but only one works. If I retry the import, another one will work, so I basically have to repeat the process 22 times...
* Finally, I have the _impression_ that a lot of import failures are simply caused by the failure of the automatic matching. If my ID3 tags are off, auto-matching will, predictably, fail, but in that case even forcing the match manually will not help. If I fix the tags, then the auto-match will work, and the next manual imports will succeed... I don't know if that's expected. I would think that forcing a manual match would override any matching warnings and let the import proceed...

Hope all this helps! Essentially the TL;DR that fixed things for me was:
* Fix the ID3 tags to make the auto-match work when possible (**SUPER** painful in a cloud-based, headless setup! My files aren't available locally so I cannot use any desktop tagging tool... I **REALLY** wish there would be a simple tag editor feature available in the import screens - we can already display tags, so I presume editing would be reasonably doable)
* Wait a bit in the import modal for the book id when auto-match doesn't work - I think this can be fixed in the UI by disabling the import button while we get the book id
* Re-run the import process about a bazillion times
