### ISSUE TITLE
[BUG]: Retagging Audio Files Fails - Nullable Object without value

### ISSUE THREAD

**Issue by tehniemer** [Readarr/Readarr#1253]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Some audio files, but not all, fail to re-tag.

### Expected Behavior

All files are re-tagged.

### Steps To Reproduce

1. Navigate to an author with audiobooks.
2. Click preview retag
3. See error

![image](https://user-images.githubusercontent.com/11021632/135670711-82c5860d-fda3-4114-bfb3-af3fa207e836.png)
 

### Environment

```markdown
- OS: Debian 11
- Readarr: 0.1.0.971
- Docker Install: Yes
- Using Reverse Proxy: Traefik
- Browser: Edge
```

### What branch are you running?

Nightly

### Anything else?

```
[Fatal] ReadarrErrorPipeline: Request Failed. GET /api/v1/retag
[v0.1.0.971] System.InvalidOperationException: Nullable object must have a value.
at NzbDrone.Core.MediaFiles.AudioTagService.GetTrackMetadata(BookFile trackfile) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\AudioTagService.cs:line 73
at NzbDrone.Core.MediaFiles.AudioTagService.GetPreviews(List`1 files)+MoveNext() in D:\a\1\s\src\NzbDrone.Core\MediaFiles\AudioTagService.cs:line 245
at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
at NzbDrone.Core.MediaFiles.AudioTagService.GetRetagPreviewsByAuthor(Int32 authorId) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\AudioTagService.cs:line 222
at NzbDrone.Core.MediaFiles.MetadataTagService.GetRetagPreviewsByAuthor(Int32 authorId) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\MetadataTagService.cs:line 74
at Readarr.Api.V1.Books.RetagBookController.GetBooks(Nullable`1 authorId, Nullable`1 bookId) in D:\a\1\s\src\Readarr.Api.V1\Books\RetagBookController.cs:line 29
at lambda_method179(Closure , Object , Object[] )
at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
at Readarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Readarr.Http\Middleware\BufferingMiddleware.cs:line 28
at Readarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Readarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
at Readarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Readarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
at Readarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Readarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
at Readarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Readarr.Http\Middleware\VersionMiddleware.cs:line 28
at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
-------------9/28/2021 10:59:52 AM--------------
```

[AB#1648](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1648)

**Comment by bakerboy448** [comment]
Please properly fill out the bug report as the template notes.  Just the error is not helpful.
![image](https://user-images.githubusercontent.com/55419169/135670991-37aad1b1-9185-47c8-9a5d-1f07a7aab298.png)

Additionally the book trying to be tagged, and the existing tags of the file it is failing on would likely be helpful as well

**Comment by tehniemer** [comment]
Here are the trace logs of the retag call and existing tags. The audiobook file is 1.9 GB, how would you like me to get that to you?

![image](https://user-images.githubusercontent.com/11021632/135699694-2956c7af-bcba-457b-9bee-7b7a6d84ca73.png)

[Readarr.trace.txt](https://github.com/Readarr/Readarr/files/7270712/Readarr.trace.txt)
