### ISSUE TITLE
Unable to configure with Calibre Content Server on a port different than 8080

### ISSUE THREAD

**Issue by tessierp** [Readarr/Readarr#1428]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a Calibre Content Server running which works fine however it is configure on a port different than the usual one. The reason for this is I have another service running on 8080 and so I needed to configure Calibre on port 9080.

Unfortunately, readarr doesn't want to accept that port and I'm given an error message 

![image](https://user-images.githubusercontent.com/6784384/147254549-d87d6478-0015-450b-94be-9804cb6dbe96.png)

### Expected Behavior

Should allow me to configure Calibre Content Server on any port where Calibre is running

### Environment

```markdown
- OS: Linux / Debian 11
- Readarr: 0.1.0.1142
- Docker Install: yes
- Using Reverse Proxy: No
- Browser: N/A
```

### What branch are you running?

Nightly

### Trace Logs?

N/A

[AB#2250](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2250)

**Comment by bakerboy448** [comment]
Trace logs are required for bug reports and are certainly applicable

nightly is not a version.

see the version in system status

**Comment by ta264** [comment]
It works on non standard ports just fine, I use it like that.

Whatever is on port 9080 it's not the calibre content server.  Please join the discord if you need more help.

**Comment by tessierp** [comment]
> It works on non standard ports just fine, I use it like that.
> 
> Whatever is on port 9080 it's not the calibre content server. Please join the discord if you need more help.

I'm using linuxserver/calibre which is a content server is it not? I will provide the logs in a moment.

Update : I believe I know what happened. By default the content server is not started.

**Comment by tessierp** [comment]
Here are some logs on the issue

2021-12-23 09:28:56.0|Warn|ReadarrErrorPipeline|Invalid request Validation failed: 
 -- Port: Not a valid Calibre content server.  See https://manual.calibre-ebook.com/server.html
2021-12-23 09:29:43.4|Error|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.

[v0.1.0.1142] FluentValidation.ValidationException: Validation failed: 
 -- Port: Not a valid Calibre content server.  See https://manual.calibre-ebook.com/server.html
   at NzbDrone.Core.Books.Calibre.CalibreProxy.Test(CalibreSettings settings) in D:\a\1\s\src\NzbDrone.Core\Books\Calibre\CalibreProxy.cs:line 592
   at Readarr.Api.V1.RootFolders.RootFolderController.CreateRootFolder(RootFolderResource rootFolderResource) in D:\a\1\s\src\Readarr.Api.V1\RootFolders\RootFolderController.cs:line 107
   at lambda_method249(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Readarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Readarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Readarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Readarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Readarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Readarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Readarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Readarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Readarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Readarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
