### ISSUE TITLE
epub files breakes import

### ISSUE THREAD

**Issue by snickers2k** [Readarr/Readarr#1446]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

i'm pretty new to readarr and still trying out how to configure. but every time i try to import, this breaks the import after 20 or so files.
Hope it's okay to post here - and that it's a bug (because looks like one). otherwise, if it's my stupidity sorry :D

`Error occurred while executing task RescanFolders: Could not find file '/opt/calibre-library/Janet Evanovich/019 - Kussen und kussen lassen (26)/019 - Kussen und kussen lassen - Janet Evanovich.epub'.`

```
System.IO.FileNotFoundException: Could not find file '/opt/calibre-library/Janet Evanovich/019 - Kussen und kussen lassen (26)/019 - Kussen und kussen lassen - Janet Evanovich.epub'.
File name: '/opt/calibre-library/Janet Evanovich/019 - Kussen und kussen lassen (26)/019 - Kussen und kussen lassen - Janet Evanovich.epub'
   at System.IO.FileInfo.get_Length()
   at NzbDrone.Core.MediaFiles.BookImport.ImportDecisionMaker.GetLocalTracks(List`1 musicFiles, DownloadClientItem downloadClientItem, ParsedTrackInfo folderInfo, FilterFilesType filter) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\BookImport\ImportDecisionMaker.cs:line 111
   at NzbDrone.Core.MediaFiles.BookImport.ImportDecisionMaker.GetImportDecisions(List`1 musicFiles, IdentificationOverrides idOverrides, ImportDecisionMakerInfo itemInfo, ImportDecisionMakerConfig config) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\BookImport\ImportDecisionMaker.cs:line 149
   at NzbDrone.Core.MediaFiles.DiskScanService.Scan(List`1 folders, FilterFilesType filter, Boolean addNewAuthors, List`1 authorIds) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\DiskScanService.cs:line 164
   at NzbDrone.Core.MediaFiles.DiskScanService.Execute(RescanFoldersCommand message) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\DiskScanService.cs:line 313
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 79
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 42
```

### Expected Behavior

import epub flawlessly ... or at least skip it and not break import

### Steps To Reproduce

docker container
media folder and/or calibre folder containing epub 

### Environment

```markdown
- OS: ubuntu 20.04
- Readarr: 0.1.0.1156
- Docker Install: 20.10.12
- Using Reverse Proxy: no
- Browser: chrome
```

### What branch are you running?

Nightly

### Trace Logs?

[Readarr.txt](https://github.com/Readarr/Readarr/files/7847980/Readarr.txt)

[AB#2353](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2353)

**Comment by snickers2k** [comment]
i reinstalled everything and still the same :(

**Comment by ta264** [comment]
Please join the discord channel for support.
