### ISSUE TITLE
Failed to import book, error communicating with Calibre. Check log for details.

### ISSUE THREAD

**Issue by Majawat** [Readarr/Readarr#1451]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After downloading the book, Readarr won't import due to error: "Failed to import book, error communicating with Calibre. Check log for details."

### Expected Behavior

Readarr imports book into Calibre

### Steps To Reproduce

1. Allow Readarr to download through Deluge.
2. Let import automatically

(basically, dunno how to reproduce, probably a config error?)

### Environment

```markdown
- OS: Windows 10 x64 21H1
- Readarr: 0.1.0.1162
- Docker Install: No
- Using Reverse Proxy: Yes, nginx, but traffic is local
- Browser: Chrome 97.0.4692.71
```

### What branch are you running?

Nightly

### Trace Logs?

2022-01-15 11:02:28.1|Debug|Parser|Unable to parse Dark World (Undying Mercenaries, Book 9) by B. V. Larson EPUB
2022-01-15 11:02:28.1|Trace|CalibreProxy|Importing to calibre: \\Hathor\Plex\Torrent\Readarr\Dark World (Undying Mercenaries, Book 9) by B. V. Larson EPUB\Dark World (Undying Mercenaries, Book 9) by B. V. Larson.epub calibre id: 0
2022-01-15 11:02:28.1|Trace|CalibreProxy|Read 468655 bytes from \\Hathor\Plex\Torrent\Readarr\Dark World (Undying Mercenaries, Book 9) by B. V. Larson EPUB\Dark World (Undying Mercenaries, Book 9) by B. V. Larson.epub
2022-01-15 11:02:28.1|Trace|HttpClient|Req: [POST] http://192.168.9.12:8080/cdb/add-book/481556135/1/$dummy.epub/Books
2022-01-15 11:02:28.1|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2022-01-15 11:02:28.1|Trace|HttpClient|Res: [POST] http://192.168.9.12:8080/cdb/add-book/481556135/1/$dummy.epub/Books: 500.InternalServerError
 (10 ms)
2022-01-15 11:02:28.1|Trace|HttpClient|Response content (0 bytes): 
2022-01-15 11:02:28.1|Warn|HttpClient|HTTP Error - Res: [POST] http://192.168.9.12:8080/cdb/add-book/481556135/1/$dummy.epub/Books: 500.InternalServerError

2022-01-15 11:02:28.1|Warn|ImportApprovedBooks|Couldn't import book \\Hathor\Plex\Torrent\Readarr\Dark World (Undying Mercenaries, Book 9) by B. V. Larson EPUB\Dark World (Undying Mercenaries, Book 9) by B. V. Larson.epub

[v0.1.0.1162] NzbDrone.Core.Books.Calibre.CalibreException: Unable to add file to Calibre library: HTTP request failed: [500:InternalServerError] [POST] at [http://192.168.9.12:8080/cdb/add-book/481556135/1/$dummy.epub/Books]
 ---> NzbDrone.Common.Http.HttpException: HTTP request failed: [500:InternalServerError] [POST] at [http://192.168.9.12:8080/cdb/add-book/481556135/1/$dummy.epub/Books]
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 101
   at NzbDrone.Common.Http.HttpClient.Post(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 302
   at NzbDrone.Common.Http.HttpClient.Post[T](HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 308
   at NzbDrone.Core.Books.Calibre.CalibreProxy.AddBook(BookFile book, CalibreSettings settings) in D:\a\1\s\src\NzbDrone.Core\Books\Calibre\CalibreProxy.cs:line 145

   --- End of inner exception stack trace ---
   at NzbDrone.Core.Books.Calibre.CalibreProxy.AddBook(BookFile book, CalibreSettings settings) in D:\a\1\s\src\NzbDrone.Core\Books\Calibre\CalibreProxy.cs:line 156
   at NzbDrone.Core.Books.Calibre.CalibreProxy.AddAndConvert(BookFile file, CalibreSettings settings) in D:\a\1\s\src\NzbDrone.Core\Books\Calibre\CalibreProxy.cs:line 84
   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeBookFile(BookFile bookFile, LocalBook localBook, Boolean copyOnly) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\UpgradeMediaFileService.cs:line 112
   at NzbDrone.Core.MediaFiles.BookImport.ImportApprovedBooks.Import(List`1 decisions, Boolean replaceExisting, DownloadClientItem downloadClientItem, ImportMode importMode) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\BookImport\ImportApprovedBooks.cs:line 199

[AB#2368](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2368)

**Comment by Majawat** [comment]
Hmm, this may have been resolved with a Calibre server update and a restart of the VM (that Readarr and Calibre sit on).
