### ISSUE TITLE
Receiving "Sequence contains no elements" exception, when trying to import books

### ISSUE THREAD

**Issue by kamtschatka** [Readarr/Readarr#1454]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I was using the automatic import functionality on my existing library and it ran for some time and then reported an exception:

```
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.PollBook(String foreignBookId)
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.SearchByGoodreadsWorkId(Int32 id) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\BookInfo\BookInfoProxy.cs:line 302
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.Search(String query, Boolean getAllEditions) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\BookInfo\BookInfoProxy.cs:line 236
   at NzbDrone.Core.MediaFiles.BookImport.Identification.CandidateService.GetRemoteCandidates(LocalEdition localEdition, IdentificationOverrides idOverrides)+MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at NzbDrone.Core.MediaFiles.BookImport.Identification.IdentificationService.GetBestRelease(LocalEdition localBookRelease, IEnumerable`1 candidateReleases, List`1 extraTracksOnDisk, Boolean& seenCandidate) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\BookImport\Identification\IdentificationService.cs:line 192
   at NzbDrone.Core.MediaFiles.BookImport.Identification.IdentificationService.IdentifyRelease(LocalEdition localBookRelease, IdentificationOverrides idOverrides, ImportDecisionMakerConfig config) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\BookImport\Identification\IdentificationService.cs:line 144
   at NzbDrone.Core.MediaFiles.BookImport.Identification.IdentificationService.Identify(List`1 localTracks, IdentificationOverrides idOverrides, ImportDecisionMakerConfig config) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\BookImport\Identification\IdentificationService.cs:line 87
   at NzbDrone.Core.MediaFiles.BookImport.ImportDecisionMaker.GetImportDecisions(List`1 musicFiles, IdentificationOverrides idOverrides, ImportDecisionMakerInfo itemInfo, ImportDecisionMakerConfig config) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\BookImport\ImportDecisionMaker.cs:line 157
   at NzbDrone.Core.MediaFiles.DownloadedBooksImportService.ProcessFolder(IDirectoryInfo directoryInfo, ImportMode importMode, Author author, DownloadClientItem downloadClientItem) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\DownloadedBooksImportService.cs:line 221
   at NzbDrone.Core.MediaFiles.DownloadedBooksImportService.ProcessFolder(IDirectoryInfo directoryInfo, ImportMode importMode, DownloadClientItem downloadClientItem) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\DownloadedBooksImportService.cs:line 154
   at NzbDrone.Core.MediaFiles.DownloadedBooksImportService.ProcessPath(String path, ImportMode importMode, Author author, DownloadClientItem downloadClientItem) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\DownloadedBooksImportService.cs:line 89
   at NzbDrone.Core.MediaFiles.DownloadedBooksCommandService.ProcessPath(DownloadedBooksScanCommand message) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\DownloadedBooksCommandService.cs:line 62
   at NzbDrone.Core.MediaFiles.DownloadedBooksCommandService.Execute(DownloadedBooksScanCommand message) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\DownloadedBooksCommandService.cs:line 71
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 79
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 42
```

### Expected Behavior

Import works and there is no exception

### Environment

```markdown
- OS: Unraid 6.9 (not sure which version of linux this uses)
- Readarr: 0.1.0.1162
- Docker Install: Yes 
- Using Reverse Proxy: No
- Browser: Chrome 97
```

### What branch are you running?

Nightly

### Trace Logs?

I have provided the exception stack trace above, If you really need trace logs, let me know, that will take a day or so to rerun the whole import.

[AB#2374](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2374)

**Comment by bakerboy448** [comment]
Just the error and no input is not helpful for what caused the error.

> # Generally speaking, all bug reports must have trace logs provided.

**Comment by kamtschatka** [comment]
```
2022-01-17 14:06:06.3|Debug|IdentificationService|Identifying book files:
/toimport/Anonymus/Das Buch ohne Namen - Anonymus_ Bu (11233)/Das Buch ohne Namen - Anonymus_ - Anonymus.epub
2022-01-17 14:06:06.3|Trace|TrackGroupingService|DistinctCount 1 MostCommonCount 1 TotalCout 1
2022-01-17 14:06:06.3|Debug|CandidateService|Getting 0 candidates from tags for 1 tracks took 0ms
2022-01-17 14:06:06.3|Debug|IdentificationService|Retrieved 0 possible tracks in 0ms
2022-01-17 14:06:06.3|Debug|IdentificationService|Matching 1 track files against candidates
2022-01-17 14:06:06.3|Trace|IdentificationService|Processing files:
/toimport/Anonymus/Das Buch ohne Namen - Anonymus_ Bu (11233)/Das Buch ohne Namen - Anonymus_ - Anonymus.epub
2022-01-17 14:06:06.3|Trace|CandidateService|Searching by isbn 9783838706023
2022-01-17 14:06:06.3|Trace|CachedHttpResponseService|Returning cached response for [GET] https://www.goodreads.com/book/auto_complete?format=json&q=9783838706023
2022-01-17 14:06:06.3|Debug|BookInfoProxy|Getting Author details GoodreadsId of 5158478
2022-01-17 14:06:06.3|Trace|ConfigService|Using default config value for 'metadatasource' defaultValue:''
2022-01-17 14:06:06.3|Trace|HttpClient|Req: [GET] https://api.bookinfo.club/v1/work/166852
2022-01-17 14:06:06.3|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2022-01-17 14:06:06.6|Trace|HttpClient|Res: [GET] https://api.bookinfo.club/v1/work/166852: 200.OK (282 ms)
2022-01-17 14:06:06.7|Trace|CommandQueueManager|Updating command status
2022-01-17 14:06:06.7|Trace|EventAggregator|Publishing CommandUpdatedEvent
2022-01-17 14:06:06.7|Trace|EventAggregator|CommandUpdatedEvent -> CommandController
2022-01-17 14:06:06.7|Trace|EventAggregator|CommandUpdatedEvent <- CommandController
2022-01-17 14:06:06.7|Trace|EventAggregator|Publishing CommandExecutedEvent
2022-01-17 14:06:06.7|Trace|EventAggregator|CommandExecutedEvent -> TaskManager
2022-01-17 14:06:06.7|Trace|EventAggregator|CommandExecutedEvent <- TaskManager
2022-01-17 14:06:06.7|Trace|EventAggregator|CommandExecutedEvent -> TaskController
2022-01-17 14:06:06.7|Trace|EventAggregator|CommandExecutedEvent <- TaskController
2022-01-17 14:06:06.7|Trace|CommandExecutor|DownloadedBooksScanCommand <- DownloadedBooksCommandService [05:54:05.7346652]
2022-01-17 14:06:06.7|Trace|Http|Req: 212 [GET] /api/v1/command (from 10.0.0.206)
2022-01-17 14:06:06.7|Trace|CommandQueueManager|Getting all commands
2022-01-17 14:06:06.7|Trace|Http|Res: 212 [GET] /api/v1/command: 200.OK (4 ms)
2022-01-17 14:06:06.7|Debug|Api|[GET] /api/v1/command: 200.OK (4 ms)
2022-01-17 14:06:06.7|Error|CommandExecutor|Error occurred while executing task DownloadedBooksScan

[v0.1.0.1165] System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.PollBook(String foreignBookId)
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.SearchByGoodreadsWorkId(Int32 id) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\BookInfo\BookInfoProxy.cs:line 302
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.Search(String query, Boolean getAllEditions) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\BookInfo\BookInfoProxy.cs:line 236
   at NzbDrone.Core.MediaFiles.BookImport.Identification.CandidateService.GetRemoteCandidates(LocalEdition localEdition, IdentificationOverrides idOverrides)+MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at NzbDrone.Core.MediaFiles.BookImport.Identification.IdentificationService.GetBestRelease(LocalEdition localBookRelease, IEnumerable`1 candidateReleases, List`1 extraTracksOnDisk, Boolean& seenCandidate) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\BookImport\Identification\IdentificationService.cs:line 192
   at NzbDrone.Core.MediaFiles.BookImport.Identification.IdentificationService.IdentifyRelease(LocalEdition localBookRelease, IdentificationOverrides idOverrides, ImportDecisionMakerConfig config) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\BookImport\Identification\IdentificationService.cs:line 144
   at NzbDrone.Core.MediaFiles.BookImport.Identification.IdentificationService.Identify(List`1 localTracks, IdentificationOverrides idOverrides, ImportDecisionMakerConfig config) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\BookImport\Identification\IdentificationService.cs:line 87
   at NzbDrone.Core.MediaFiles.BookImport.ImportDecisionMaker.GetImportDecisions(List`1 musicFiles, IdentificationOverrides idOverrides, ImportDecisionMakerInfo itemInfo, ImportDecisionMakerConfig config) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\BookImport\ImportDecisionMaker.cs:line 157
   at NzbDrone.Core.MediaFiles.DownloadedBooksImportService.ProcessFolder(IDirectoryInfo directoryInfo, ImportMode importMode, Author author, DownloadClientItem downloadClientItem) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\DownloadedBooksImportService.cs:line 221
   at NzbDrone.Core.MediaFiles.DownloadedBooksImportService.ProcessFolder(IDirectoryInfo directoryInfo, ImportMode importMode, DownloadClientItem downloadClientItem) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\DownloadedBooksImportService.cs:line 154
   at NzbDrone.Core.MediaFiles.DownloadedBooksImportService.ProcessPath(String path, ImportMode importMode, Author author, DownloadClientItem downloadClientItem) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\DownloadedBooksImportService.cs:line 89
   at NzbDrone.Core.MediaFiles.DownloadedBooksCommandService.ProcessPath(DownloadedBooksScanCommand message) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\DownloadedBooksCommandService.cs:line 62
   at NzbDrone.Core.MediaFiles.DownloadedBooksCommandService.Execute(DownloadedBooksScanCommand message) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\DownloadedBooksCommandService.cs:line 71
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 111
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 42
```
