### ISSUE TITLE
InternalServer Error when calling bookinfo.club API stops the import

### ISSUE THREAD

**Issue by kamtschatka** [Readarr/Readarr#1465]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I was trying to import books and bookinfo.club returned an internal server error, which stopped the import.

Error occurred while executing task DownloadedBooksScan: HTTP request failed: [500:InternalServerError] [GET] at [https://api.bookinfo.club/v1/author/65135]

```
NzbDrone.Common.Http.HttpException: HTTP request failed: [500:InternalServerError] [GET] at [https://api.bookinfo.club/v1/author/65135]
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.PollAuthorUncached(String foreignAuthorId) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\BookInfo\BookInfoProxy.cs:line 491
   at NzbDrone.Common.Cache.Cached`1.Get(String key, Func`1 function, Nullable`1 lifeTime) in D:\a\1\s\src\NzbDrone.Common\Cache\Cached.cs:line 113
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.PollAuthor(String foreignAuthorId) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\BookInfo\BookInfoProxy.cs:line 459
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.SearchByGoodreadsAuthorId(Int32 id) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\BookInfo\BookInfoProxy.cs:line 273
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.Search(String query, Boolean getAllEditions) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\BookInfo\BookInfoProxy.cs:line 229
   at NzbDrone.Core.MediaFiles.BookImport.Identification.CandidateService.GetRemoteCandidates(LocalEdition localEdition, IdentificationOverrides idOverrides)+MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at NzbDrone.Core.MediaFiles.BookImport.Identification.IdentificationService.GetBestRelease(LocalEdition localBookRelease, IEnumerable`1 candidateReleases, List`1 extraTracksOnDisk, Boolean& seenCandidate) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\BookImport\Identification\IdentificationService.cs:line 192
   at NzbDrone.Core.MediaFiles.BookImport.Identification.IdentificationService.IdentifyRelease(LocalEdition localBookRelease, IdentificationOverrides idOverrides, ImportDecisionMakerConfig config) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\BookImport\Identification\IdentificationService.cs:line 144
   at NzbDrone.Core.MediaFiles.BookImport.Identification.IdentificationService.Identify(List`1 localTracks, IdentificationOverrides idOverrides, ImportDecisionMakerConfig config) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\BookImport\Identification\IdentificationService.cs:line 87
   at NzbDrone.Core.MediaFiles.BookImport.ImportDecisionMaker.GetImportDecisions(List`1 musicFiles, IdentificationOverrides idOverrides, ImportDecisionMakerInfo itemInfo, ImportDecisionMakerConfig config) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\BookImport\ImportDecisionMaker.cs:line 157
   at NzbDrone.Core.MediaFiles.DownloadedBooksImportService.ProcessFolder(IDirectoryInfo directoryInfo, ImportMode importMode, Author author, DownloadClientItem downloadClientItem) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\DownloadedBooksImportService.cs:line 221
   at NzbDrone.Core.MediaFiles.DownloadedBooksImportService.ProcessFolder(IDirectoryInfo directoryInfo, ImportMode importMode, DownloadClientItem downloadClientItem) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\DownloadedBooksImportService.cs:line 154
   at NzbDrone.Core.MediaFiles.DownloadedBooksImportService.ProcessPath(String path, ImportMode importMode, Author author, DownloadClientItem downloadClientItem) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\DownloadedBooksImportService.cs:line 89
   at NzbDrone.Core.MediaFiles.DownloadedBooksCommandService.ProcessPath(DownloadedBooksScanCommand message) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\DownloadedBooksCommandService.cs:line 62
   at NzbDrone.Core.MediaFiles.DownloadedBooksCommandService.Execute(DownloadedBooksScanCommand message) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\DownloadedBooksCommandService.cs:line 71
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 79
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 42
```

### Expected Behavior

Book will be skipped instead of completely failing the import

### Environment

```markdown
- OS: Unraid
- Readarr: 0.1.0.1175
- Docker Install: yes
- Using Reverse Proxy: no
- Browser: Chrome 97
```

### What branch are you running?

Nightly

### Trace Logs?

Not available, stacktrace shows the problem and the URL where it happened.

[AB#2402](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2402)

**Comment by ta264** [comment]
Please post trace logs.  Hard to tell what's going on other than that it doesn't work otherwise.

**Comment by kamtschatka** [comment]
I did not have trace logs active at that time and I do not have control over the bookinfo.club API to return 500 errors.
I am not sure why you would need it though? 
The error is originating from a 500 error returned from the API and on line 491 in BookInfoProxy.cs you are checking if the request has an error and if yes, you throw a new HttpException, which seems to be unhandled later on.

**Comment by bakerboy448** [comment]
> checking if the request has an error and if yes, you throw a new HttpException, which seems to be unhandled later on.

this is expected

> The error is originating from a 500 error returned from the API

Seeing what lead into this request is key.

**Comment by kamtschatka** [comment]
that is what the stacktrace is for and it also shows the URL of the request.
The URL does not return a 500 response right now and the request doesn't have any special headers set on it, so it is safe to assume that there was a problem in the bookinfo.club infrastructure.

In the end it boils down to this: An exception is unhandled and stops the whole import, which is not desired.

**Comment by bakerboy448** [comment]
Manual Import from wanted? Letting Readarr doing it's monitor root folder thing? Auto Import from a download client? Manual Import from an author or book page?  Blackhole download client?

What was the details of the file?

Where in the process did it fail?
What occurred after the stack trace?

All of this would be in the trace logs. This is also why the template explicitly says all bug reports require trace logs.

The stack trace and just the error is just about never helpful in getting into the root of an issue.  

We'll see if the extremely limited information provided is enough for Ta to go off of. Based on his initial comments, it doesn't appear so.

Though perhaps the sidebar issue of failing more gracefully and skipping to the next time could make sense.  But again, there's no information provided as to what specifically was occurring.

**Comment by kamtschatka** [comment]
* I did a manual import from wanted
* What was the details of the file: Doesn't really matter, it ended up making a request to find the author for it, by calling "https://api.bookinfo.club/v1/author/65135", which returned a 500 error at this point in time.
* Where in the process did it fail? Check the stacktrace, it shows exactly where it failed
* What occurred after the stack trace? Well nothing, because an uncaught exception will halt all execution and the task was just failed.
* All of this would be in the trace logs: Yes and No. The folder I am trying to import for 5 times now has about 110k books. It takes hours to go through all the process and the trace logs are so abundant that they get rotated multiple times as the disk space is not enough. So I would have only been able to give you the information about the book, but since it is a 500 error which does not occur anymore, it was definitely not related to the book or the author itself. Additionally the code explicitly throws an exception, which is not caught higher up, so a static code analysis is enough to fix this issue.
* I am not sure why you are repeating that there is limited information/no information on what specifically was occuring, when it is literally in the first comment? It shows, which request was made, that it returned a 500 error and that the code throws an exception because of this, which is not caught. I really don't know how that can be any more specific?

**Comment by ta264** [comment]
I have an idea. Drop the attitude and try importing a folder with just the bad book and post logs of that.

**Comment by kamtschatka** [comment]
I have said it now multiple times: It is not a bad book, the bookinfo.club returned a 500 error, you rethrow the error and do not catch it, causing the task to fail.
I will check what I can make of the code and open a PR...
