### ISSUE TITLE
Audiobook Tagging Failing

### ISSUE THREAD

**Issue by dagwood90** [Readarr/Readarr#1523]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When an audiobook is found via automatic or manual search, the tagging of the files fails. The file is copied to the destination location, the file is renamed but it errors out on writing the tags. This just started after the 1240 build as far as I can tell. 

If I go an manually import the same file, it seems to work as expected.

### Expected Behavior

File gets processed and tags updated without error

### Steps To Reproduce

1) auto-download any audiobook (m4b and mp3 exhibit this)
2) have system set to update tags (always in sync with goodreads)

### Environment

```markdown
- OS: Alpine
- Readarr: 0.1.0.1242
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: Firefox
```

### What branch are you running?

Nightly

### Trace Logs?

2022-02-13 19:24:43.2|Warn|ImportApprovedBooks|Couldn't import book /abooks-seed/Craig Alanson - Paradise Expeditionary Force, Book 3 (Unabridged) M4B/Paradise Expeditionary Force, Book 3 (Unabridged).m4b

[v0.1.0.1242] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.MediaFiles.AudioTagService.GetTrackMetadata(BookFile trackfile) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\AudioTagService.cs:line 98
   at NzbDrone.Core.MediaFiles.AudioTagService.WriteTags(BookFile trackfile, Boolean newDownload, Boolean force) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\AudioTagService.cs:line 186
   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeBookFile(BookFile bookFile, LocalBook localBook, Boolean copyOnly) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\UpgradeMediaFileService.cs:line 106
   at NzbDrone.Core.MediaFiles.BookImport.ImportApprovedBooks.Import(List`1 decisions, Boolean replaceExisting, DownloadClientItem downloadClientItem, ImportMode importMode) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\BookImport\ImportApprovedBooks.cs:line 215

2022-02-13 19:24:43.3|Debug|ImportApprovedBooks|Inserted new trackfiles in 2ms
2022-02-13 19:24:43.3|Trace|TrackedDownloadAlreadyImported|Checking if all books for 'Craig Alanson - Paradise Expeditionary Force, Book 3 (Unabridged) M4B' have been imported
2022-02-13 19:24:43.3|Trace|TrackedDownloadAlreadyImported|Last event for book: [53307790][Paradise] is: Grabbed
2022-02-13 19:24:43.3|Trace|TrackedDownloadAlreadyImported|All books for 'Craig Alanson - Paradise Expeditionary Force, Book 3 (Unabridged) M4B' have been imported: False
2022-02-13 19:24:43.3|Debug|CompletedDownloadService|Not all books have been imported for Craig Alanson - Paradise Expeditionary Force, Book 3 (Unabridged) M4B
2022-02-13 19:24:43.3|Trace|EventAggregator|Publishing BookImportIncompleteEvent
2022-02-13 19:24:43.3|Trace|EventAggregator|BookImportIncompleteEvent -> NotificationService
2022-02-13 19:24:43.3|Debug|NotificationService|No tags set for this notification.
2022-02-13 19:24:43.3|Trace|HttpClient|Req: [POST] https://api.pushover.net/1/messages.json: token=(removed)&user=(removed)&device=&title=Import%20Failed&message=Readarr%20failed%20to%20Import%20all%20files%20for%20Craig%20Alanson%20-%20Paradise%20Expeditionary%20Force%2C%20Book%203%20%28Unabridged%29%20M4B&priority=0
2022-02-13 19:24:43.3|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2022-02-13 19:24:43.6|Trace|HttpClient|Res: [POST] https://api.pushover.net/1/messages.json: 200.OK (293 ms)

[AB#2578](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2578)

**Comment by ta264** [comment]
Please can you join the discord channel to help debug this? I'm not sure it can be all books so we need to try to figure out what's going on.

**Comment by johnpyp** [comment]
I believe I'm seeing the same or similar behavior as well, the books go from Downloading -> "purple importing" status -> yellow failed to import book, but the book ends up moved properly, and as far as I can tell it does not get tagged correctly, but does get renamed correctly, then it also just ends up hanging out in queue as "failed to import" for no reason.

I can manually resolve the issue after refreshing, then going into unmapped files and importing.

If it's important, I have my move setup as copy rather than hardlink.

**Comment by dagwood90** [comment]
@ta264 I pinged in discord yesterday as well on this. Anyway what @johnpyp is seeing above is the same thing I am seeing. it started with build 1240 and have happened to about 40 books downloaded since then (every single one downloaded).

**Comment by johnpyp** [comment]
Interestingly, there seems to be some UI finnicky-ness with this as well, specifically:

1. Looking at the Activity status page, I see them go from purple to yellow, then I click on the authors name, and the downloading books are marked as "missing" (despite being renamed into the right location).
2. Before refreshing the page, I click "Refresh and Scan", and the books actually get indexed and show up, not missing anymore.
3. Then I navigate away and come back, or refresh, and the books are then missing again. Clicking refresh and scan does nothing.
4. Finally, I can go into the unmapped files tab to import the books and retag them properly.
