### ISSUE TITLE
Amazon is throttling goodreads img pulls 

### ISSUE THREAD

**Issue by DreadDragoon** [Readarr/Readarr#1584]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Amazon seems to be throttling goodread pulls. I can curl the url directly, and if i do it twice+ in a row, or make sequential requests quickly, goodreads will start blocking 

### Expected Behavior

Download image from goodreads AWS site

### Environment

```markdown
- OS: Ubuntu 21.10
- Readarr: 0.1.0.1248
- Docker Install: Yes
- Using Reverse Proxy: no
- Browser: na
```

### What branch are you running?

Develop

### Trace Logs?

```
Error] MediaCoverService: Couldn't download media cover for [57522823][Classic Gold] 
[v0.1.0.1248] System.Threading.Tasks.TaskCanceledException: A task was canceled.
  at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
  at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
  at System.Net.Http.HttpClient.Send(HttpRequestMessage request, CancellationToken cancellationToken)
  at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in D:\a\1\s\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 110
  at NzbDrone.Common.Http.HttpClient.ExecuteRequest(HttpRequest request, CookieContainer cookieContainer) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 124
  at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 59
  at NzbDrone.Core.MediaCover.MediaCoverService.GetServerHeaders(String url) in D:\a\1\s\src\NzbDrone.Core\MediaCover\MediaCoverService.cs:line 286
```

```
root@7096c4f27e07:/#curl -sv https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1558617803i/40138608.jpg
Trying 199.232.5.16:443...

Connected to images-na.ssl-images-amazon.com (199.232.5.16) port 443 (#0)

ALPN, offering h2

ALPN, offering http/1.1

CAfile: /etc/ssl/certs/ca-certificates.crt

CApath: none

TLSv1.3 (OUT), TLS handshake, Client hello (1):

TLSv1.3 (IN), TLS handshake, Server hello (2):

TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):

TLSv1.3 (IN), TLS handshake, Certificate (11):

TLSv1.3 (IN), TLS handshake, CERT verify (15):

TLSv1.3 (IN), TLS handshake, Finished (20):

TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):

TLSv1.3 (OUT), TLS handshake, Finished (20):

SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384

ALPN, server accepted to use h2

Server certificate:

subject: CN=images-na.ssl-images-amazon.com

start date: Aug 9 00:00:00 2021 GMT

expire date: Jul 24 23:59:59 2022 GMT

subjectAltName: host "images-na.ssl-images-amazon.com" matched cert's "images-na.ssl-images-amazon.com"

issuer: C=US; O=DigiCert Inc; CN=DigiCert Global CA G2

SSL certificate verify ok.

Using HTTP2, server supports multiplexing

Connection state changed (HTTP/2 confirmed)

Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0

Using Stream ID: 1 (easy handle 0x7fdce2286a90)

GET /images/S/compressed.photo.goodreads.com/books/1558617803i/40138608.jpg HTTP/2 Host: images-na.ssl-images-amazon.com user-agent: curl/7.80.0 accept: /

TLSv1.3 (IN), TLS handshake, Newsession Ticket (4): < HTTP/2 200 < content-type: image/jpeg < x-amz-ir-id: 6e9fc577-7d21-467e-af34-84bbf2a1cfac < access-control-allow-origin: * < last-modified: Thu, 23 May 2019 13:55:22 GMT < x-nginx-cache-status: MISS < accept-ranges: bytes < date: Wed, 23 Feb 2022 00:04:47 GMT < age: 13725 < x-served-by: cache-iad-kjyo7100086-IAD, cache-chi21122-CHI < x-cache: HIT from fastly, HIT from fastly < content-length: 37034 <

Failure writing output to destination

stopped the pause stream!

Connection #0 to host images-na.ssl-images-amazon.com left intact 
```

```
root@7096c4f27e07:/#curl -sv https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1558617803i/40138608.jpg

Trying 199.232.5.16:443...

Connected to images-na.ssl-images-amazon.com (199.232.5.16) port 443 (#0)

ALPN, offering h2

ALPN, offering http/1.1

CAfile: /etc/ssl/certs/ca-certificates.crt

CApath: none

TLSv1.3 (OUT), TLS handshake, Client hello (1):
* SSL connection timeout
* Closing connection 0
```

[AB#2771](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2771)

**Comment by DreadDragoon** [comment]
fyi, metadata comes down fine, just not images
