### ISSUE TITLE
Search is very unstable and slow

### ISSUE THREAD

**Issue by Visne** [Readarr/Readarr#1740]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The search functionality for adding a new book is very unstable. It often instantly displays `"Couldn't find any results for '[book]'
You can also search using the[ Goodreads ID ](https://goodreads.com/)of a book (e.g. edition:656), work (e.g. work:4912783) or author (e.g. author:128382), the isbn (e.g. isbn:067003469X) or the asin (e.g. asin:B00JCDK5ME)"`. After cutting and pasting the title into the search bar a few times it works, although it still takes very long (~1 min).

### Expected Behavior

After typing in a search query, results are shown in a reasonable amount of time (<20 seconds).

### Steps To Reproduce

1. Type in a search query on `/add/search`

### Environment

```markdown
- OS: Manjaro Linux on a Raspberry Pi 4B
- Readarr: 0.1.1.1320
- Docker Install: No
- Using Reverse Proxy: Yes, Nginx
- Browser: Firefox 102.0.1
```

### What branch are you running?

Develop

### Trace Logs?

[Readarr.trace.txt](https://github.com/Readarr/Readarr/files/9104783/Readarr.trace.txt)

[AB#3359](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3359)

**Comment by bakerboy448** [comment]
Not a Readarr issue

```
2022-07-13 19:55:28.0|Trace|Http|Req: 976 [GET] /readarr/api/v1/search?term=do%20androids%20dream (from 192.168.1.1 Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0)
2022-07-13 19:55:28.0|Trace|CachedHttpResponseService|Returning cached response for [GET] https://www.goodreads.com/book/auto_complete?format=json&q=do%20androids%20dream
2022-07-13 19:55:28.0|Trace|ConfigService|Using default config value for 'metadatasource' defaultValue:''
2022-07-13 19:55:28.0|Trace|HttpClient|Req: [POST] https://api.bookinfo.club/v1/book/bulk
2022-07-13 19:55:28.0|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2022-07-13 19:55:38.8|Trace|HttpClient|Res: [POST] https://api.bookinfo.club/v1/book/bulk: 524.524 (0 bytes) (99196 ms)
2022-07-13 19:55:38.8|Warn|HttpClient|HTTP Error - Res: [POST] https://api.bookinfo.club/v1/book/bulk: 524.524 (0 bytes)
2022-07-13 19:55:38.8|Warn|BookInfoProxy|Error mapping search results

[v0.1.1.1320] NzbDrone.Common.Http.HttpException: HTTP request failed: [524:524] [POST] at [https://api.bookinfo.club/v1/book/bulk]
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 101
   at NzbDrone.Common.Http.HttpClient.Post(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 302
   at NzbDrone.Common.Http.HttpClient.Post[T](HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 308
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.MapSearchResult(List`1 ids) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\BookInfo\BookInfoProxy.cs:line 462
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.Search(String query, Boolean getAllEditions) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\BookInfo\BookInfoProxy.cs:line 295



2022-07-13 19:55:38.9|Trace|Http|Res: 917 [GET] /readarr/api/v1/search?term=brave%20new%20world: 200.OK (100490 ms)
2022-07-13 19:55:44.8|Trace|HttpClient|Res: [POST] https://api.bookinfo.club/v1/book/bulk: 200.OK (18059 bytes) (75453 ms)
2022-07-13 19:55:44.8|Trace|Http|Res: 963 [GET] /readarr/api/v1/search?term=Do%20Androids%20Dream%20of%20Electric%20Shee: 200.OK (75921 ms)
2022-07-13 19:55:44.8|Trace|HttpClient|Res: [POST] https://api.bookinfo.club/v1/book/bulk: 200.OK (24211 bytes) (94902 ms)
2022-07-13 19:55:44.9|Trace|Http|Res: 957 [GET] /readarr/api/v1/search?term=conta: 200.OK (95260 ms)
2022-07-13 19:55:45.0|Trace|HttpClient|Res: [POST] https://api.bookinfo.club/v1/book/bulk: 200.OK (11244 bytes) (92542 ms)
2022-07-13 19:55:45.1|Trace|HttpClient|Res: [POST] https://api.bookinfo.club/v1/book/bulk: 200.OK (18059 bytes) (75281 ms)
2022-07-13 19:55:45.1|Trace|HttpClient|Res: [POST] https://api.bookinfo.club/v1/book/bulk: 200.OK (18059 bytes) (87031 ms)
2022-07-13 19:55:45.1|Trace|Http|Res: 959 [GET] /readarr/api/v1/search?term=contact%20carl%20sagan: 200.OK (92885 ms)
2022-07-13 19:55:45.1|Trace|HttpClient|Res: [POST] https://api.bookinfo.club/v1/book/bulk: 200.OK (18059 bytes) (80037 ms)
2022-07-13 19:55:45.1|Trace|Http|Res: 961 [GET] /readarr/api/v1/search?term=Do%20Androids%20Dream%20of%20Electric%20Sheep%3F: 200.OK (80097 ms)
2022-07-13 19:55:45.1|Trace|Http|Res: 964 [GET] /readarr/api/v1/search?term=Do%20Androids%20Dream%20of%20Electric%20Sheep: 200.OK (75375 ms)
2022-07-13 19:55:45.1|Trace|Http|Res: 960 [GET] /readarr/api/v1/search?term=Do%20Androids%20Dream%20of%20Electric%20Sheep%3F: 200.OK (87537 ms)
2022-07-13 19:55:46.4|Trace|HttpClient|Res: [POST] https://api.bookinfo.club/v1/book/bulk: 524.524 (0 bytes) (99177 ms)
2022-07-13 19:55:46.4|Warn|HttpClient|HTTP Error - Res: [POST] https://api.bookinfo.club/v1/book/bulk: 524.524 (0 bytes)
2022-07-13 19:55:46.4|Warn|BookInfoProxy|Error mapping search results

[v0.1.1.1320] NzbDrone.Common.Http.HttpException: HTTP request failed: [524:524] [POST] at [https://api.bookinfo.club/v1/book/bulk]
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 101
   at NzbDrone.Common.Http.HttpClient.Post(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 302
   at NzbDrone.Common.Http.HttpClient.Post[T](HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 308
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.MapSearchResult(List`1 ids) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\BookInfo\BookInfoProxy.cs:line 462
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.Search(String query, Boolean getAllEditions) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\BookInfo\BookInfoProxy.cs:line 295



2022-07-13 19:55:46.4|Trace|Http|Res: 937 [GET] /readarr/api/v1/search?term=brave%20new%20world: 200.OK (99210 ms)
2022-07-13 19:55:47.7|Trace|HttpClient|Res: [POST] https://api.bookinfo.club/v1/book/bulk: 200.OK (18059 bytes) (71095 ms)
2022-07-13 19:55:47.7|Trace|Http|Res: 967 [GET] /readarr/api/v1/search?term=do%20androids%20dream: 200.OK (71138 ms)
2022-07-13 19:55:47.8|Trace|HttpClient|Res: [POST] https://api.bookinfo.club/v1/book/bulk: 200.OK (18059 bytes) (80101 ms)
2022-07-13 19:55:47.8|Trace|Http|Res: 962 [GET] /readarr/api/v1/search?term=Do%20Androids%20Dream%20of%20Electric%20Sheep: 200.OK (80445 ms)
2022-07-13 19:55:48.0|Trace|HttpClient|Res: [POST] https://api.bookinfo.club/v1/book/bulk: 524.524 (0 bytes) (99151 ms)
2022-07-13 19:55:48.0|Warn|HttpClient|HTTP Error - Res: [POST] https://api.bookinfo.club/v1/book/bulk: 524.524 (0 bytes)
2022-07-13 19:55:48.0|Warn|BookInfoProxy|Error mapping search results

[v0.1.1.1320] NzbDrone.Common.Http.HttpException: HTTP request failed: [524:524] [POST] at [https://api.bookinfo.club/v1/book/bulk]
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 101
   at NzbDrone.Common.Http.HttpClient.Post(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 302
   at NzbDrone.Common.Http.HttpClient.Post[T](HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 308
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.MapSearchResult(List`1 ids) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\BookInfo\BookInfoProxy.cs:line 462
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.Search(String query, Boolean getAllEditions) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\BookInfo\BookInfoProxy.cs:line 295



2022-07-13 19:55:48.0|Trace|Http|Res: 956 [GET] /readarr/api/v1/search?term=brave%20new%20world: 200.OK (99169 ms)
2022-07-13 19:55:48.6|Trace|HttpClient|Res: [POST] https://api.bookinfo.club/v1/book/bulk: 200.OK (7124 bytes) (75435 ms)
2022-07-13 19:55:48.6|Trace|Http|Res: 965 [GET] /readarr/api/v1/search?term=do%20androids%20sleep: 200.OK (75757 ms)
2022-07-13 19:55:49.6|Trace|HttpClient|Res: [POST] https://api.bookinfo.club/v1/book/bulk: 200.OK (18059 bytes) (21524 ms)
2022-07-13 19:55:49.6|Trace|Http|Res: 976 [GET] /readarr/api/v1/search?term=do%20androids%20dream: 200.OK (21560 ms)
2022-07-13 19:55:50.6|Trace|HttpClient|Res: [POST] https://api.bookinfo.club/v1/book/bulk: 500.InternalServerError (0 bytes) (75686 ms)
2022-07-13 19:55:50.6|Warn|HttpClient|HTTP Error - Res: [POST] https://api.bookinfo.club/v1/book/bulk: 500.InternalServerError (0 bytes)
2022-07-13 19:55:50.6|Warn|BookInfoProxy|Error mapping search results

[v0.1.1.1320] NzbDrone.Common.Http.HttpException: HTTP request failed: [500:InternalServerError] [POST] at [https://api.bookinfo.club/v1/book/bulk]
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 101
   at NzbDrone.Common.Http.HttpClient.Post(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 302
   at NzbDrone.Common.Http.HttpClient.Post[T](HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 308
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.MapSearchResult(List`1 ids) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\BookInfo\BookInfoProxy.cs:line 462
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.Search(String query, Boolean getAllEditions) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\BookInfo\BookInfoProxy.cs:line 295



2022-07-13 19:55:50.6|Trace|Http|Res: 966 [GET] /readarr/api/v1/search?term=do%20androids%20dream: 200.OK (76081 ms)
```

GoodRead's API is returning a 524 and not responding.
`2022-07-13 19:55:38.8|Trace|HttpClient|Res: [POST] https://api.bookinfo.club/v1/book/bulk: 524.524 (0 bytes) (99196 ms)`
When it does finally respond, it's taking a signifcant time.

Not a Readarr issue.

**Comment by Visne** [comment]
Okay, I'll continue on Discord.
