### ISSUE TITLE
`Value cannot be null. (Parameter 'input')` When scanning folder

### ISSUE THREAD

**Issue by potchin** [Readarr/Readarr#1749]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This is a new readarr installation. When scanning existing files (audiobooks) the scanner crashes with the error...

```
2022-07-27 14:49:01.1|Error|CommandExecutor|Error occurred while executing task RescanFolders

[v0.1.0.715] System.ArgumentNullException: Value cannot be null. (Parameter 'input')
```

I suspect the problem is with the file its processing.. BUT at no point, even with trace logging, does it print which file its about to scan. I have no way of investigating further until I know which file is causing the problem.

### Expected Behavior

It should either fully scan all files or error with the current filename in the case of an error.

### Environment

```markdown
- OS: Linux
- Readarr: 0.1.0.715
- Docker Install: yes. ghcr.io/k8s-at-home/readarr:v0.1.0.715
- Using Reverse Proxy: yes, nginx ingress controller (k8s)
- Browser: Firefox
```

### What branch are you running?

Develop

### Trace Logs?

```
2022-07-27 14:49:01.1|Debug|IdentificationService|Best release found in 13ms
2022-07-27 14:49:01.1|Debug|IdentificationService|IdentifyRelease done in 13ms
2022-07-27 14:49:01.1|Info|IdentificationService|Identifying book 39/68
2022-07-27 14:49:01.1|Trace|EventAggregator|Publishing CommandUpdatedEvent
2022-07-27 14:49:01.1|Trace|EventAggregator|CommandUpdatedEvent -> CommandController
2022-07-27 14:49:01.1|Trace|EventAggregator|CommandUpdatedEvent <- CommandController
2022-07-27 14:49:01.1|Trace|TrackGroupingService|DistinctCount 1 MostCommonCount 25 TotalCout 25
2022-07-27 14:49:01.1|Trace|CommandQueueManager|Updating command status
2022-07-27 14:49:01.1|Trace|CommandExecutor|ProcessMonitoredDownloadsCommand -> DownloadProcessingService
2022-07-27 14:49:01.1|Trace|CommandQueueManager|Marking command as started: ProcessMonitoredDownloads
2022-07-27 14:49:01.1|Trace|EventAggregator|Publishing CommandUpdatedEvent
2022-07-27 14:49:01.1|Trace|EventAggregator|CommandUpdatedEvent -> CommandController
2022-07-27 14:49:01.1|Trace|EventAggregator|CommandUpdatedEvent <- CommandController
2022-07-27 14:49:01.1|Trace|EventAggregator|Publishing CommandExecutedEvent
2022-07-27 14:49:01.1|Trace|EventAggregator|CommandExecutedEvent -> TaskManager
2022-07-27 14:49:01.1|Trace|ConfigService|Using default config value for 'enablecompleteddownloadhandling' defaultValue:'True'
2022-07-27 14:49:01.1|Trace|ConfigService|Using default config value for 'removecompleteddownloads' defaultValue:'False'
2022-07-27 14:49:01.1|Trace|TaskManager|Updating last run time for: NzbDrone.Core.MediaFiles.Commands.RescanFoldersCommand
2022-07-27 14:49:01.1|Trace|EventAggregator|Publishing DownloadsProcessedEvent
2022-07-27 14:49:01.1|Trace|EventAggregator|DownloadsProcessedEvent -> DownloadMonitoringService
2022-07-27 14:49:01.1|Trace|EventAggregator|Publishing TrackedDownloadRefreshedEvent
2022-07-27 14:49:01.1|Trace|EventAggregator|TrackedDownloadRefreshedEvent -> QueueService
2022-07-27 14:49:01.1|Trace|EventAggregator|CommandExecutedEvent <- TaskManager
2022-07-27 14:49:01.1|Trace|EventAggregator|Publishing QueueUpdatedEvent
2022-07-27 14:49:01.1|Trace|EventAggregator|CommandExecutedEvent -> TaskController
2022-07-27 14:49:01.1|Trace|EventAggregator|QueueUpdatedEvent -> QueueController
2022-07-27 14:49:01.1|Trace|EventAggregator|CommandExecutedEvent <- TaskController
2022-07-27 14:49:01.1|Trace|EventAggregator|QueueUpdatedEvent <- QueueController
2022-07-27 14:49:01.1|Trace|CommandExecutor|RescanFoldersCommand <- DiskScanService [00:00:04.1064763]
2022-07-27 14:49:01.1|Trace|EventAggregator|QueueUpdatedEvent -> QueueDetailsController
2022-07-27 14:49:01.1|Trace|EventAggregator|QueueUpdatedEvent <- QueueDetailsController
2022-07-27 14:49:01.1|Trace|EventAggregator|QueueUpdatedEvent -> QueueStatusController
2022-07-27 14:49:01.1|Trace|EventAggregator|QueueUpdatedEvent <- QueueStatusController
2022-07-27 14:49:01.1|Trace|EventAggregator|TrackedDownloadRefreshedEvent <- QueueService
2022-07-27 14:49:01.1|Trace|EventAggregator|DownloadsProcessedEvent <- DownloadMonitoringService
2022-07-27 14:49:01.1|Trace|CommandQueueManager|Updating command status
2022-07-27 14:49:01.1|Trace|EventAggregator|Publishing CommandExecutedEvent
2022-07-27 14:49:01.1|Trace|EventAggregator|CommandExecutedEvent -> TaskManager
2022-07-27 14:49:01.1|Trace|EventAggregator|CommandExecutedEvent <- TaskManager
2022-07-27 14:49:01.1|Trace|EventAggregator|CommandExecutedEvent -> TaskController
2022-07-27 14:49:01.1|Trace|EventAggregator|CommandExecutedEvent <- TaskController
2022-07-27 14:49:01.1|Trace|CommandExecutor|ProcessMonitoredDownloadsCommand <- DownloadProcessingService [00:00:00.0026579]
2022-07-27 14:49:01.1|Error|CommandExecutor|Error occurred while executing task RescanFolders

[v0.1.0.715] System.ArgumentNullException: Value cannot be null. (Parameter 'input')
   at System.Text.RegularExpressions.ThrowHelper.ThrowArgumentNullException(ExceptionArgument arg)
   at System.Text.RegularExpressions.Regex.Replace(String input, String replacement)
   at NzbDrone.Core.Parser.Parser.CleanAuthorName(String name) in D:\a\1\s\src\NzbDrone.Core\Parser\Parser.cs:line 587
   at NzbDrone.Core.Books.AuthorService.GetCandidates(String title) in D:\a\1\s\src\NzbDrone.Core\Books\Services\AuthorService.cs:line 139
   at NzbDrone.Core.MediaFiles.BookImport.Identification.CandidateService.GetDbCandidates(LocalEdition localEdition, Boolean includeExisting) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\BookImport\Identification\CandidateService.cs:line 176
   at NzbDrone.Core.MediaFiles.BookImport.Identification.CandidateService.GetDbCandidatesFromTags(LocalEdition localEdition, IdentificationOverrides idOverrides, Boolean includeExisting) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\BookImport\Identification\CandidateService.cs:line 45
   at NzbDrone.Core.MediaFiles.BookImport.Identification.IdentificationService.IdentifyRelease(LocalEdition localBookRelease, IdentificationOverrides idOverrides, ImportDecisionMakerConfig config) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\BookImport\Identification\IdentificationService.cs:line 120
   at NzbDrone.Core.MediaFiles.BookImport.Identification.IdentificationService.Identify(List`1 localTracks, IdentificationOverrides idOverrides, ImportDecisionMakerConfig config) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\BookImport\Identification\IdentificationService.cs:line 84
   at NzbDrone.Core.MediaFiles.BookImport.ImportDecisionMaker.GetImportDecisions(List`1 musicFiles, IdentificationOverrides idOverrides, ImportDecisionMakerInfo itemInfo, ImportDecisionMakerConfig config) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\BookImport\ImportDecisionMaker.cs:line 157
   at NzbDrone.Core.MediaFiles.DiskScanService.Scan(List`1 folders, FilterFilesType filter, Boolean addNewAuthors, List`1 authorIds) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\DiskScanService.cs:line 164
   at NzbDrone.Core.MediaFiles.DiskScanService.Execute(RescanFoldersCommand message) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\DiskScanService.cs:line 313
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 116
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 42
```

[AB#3390](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3390)

**Comment by ta264** [comment]
You are nearly 500 builds out of date, upgrade
