### ISSUE TITLE
Library-Books: Filter = Missing, Search filtered results in CommandExecutor error "Object reference not set to an instance of an object"

### ISSUE THREAD

**Issue by norrisp90** [Readarr/Readarr#1754]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When clicking Search Filtered, in books section filtered on missing the following error occurs.
```
Message: 
Library-Books: Filter = Missing, Search filter results in CommandExecutor error "Object reference not set to an instance of an object"

Exception: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.IndexerSearch.NzbSearchService.BookSearch(Book book, Boolean missingOnly, Boolean userInvokedSearch, Boolean interactiveSearch) in D:\a\1\s\src\NzbDrone.Core\IndexerSearch\NzbSearchService.cs:line 74
   at NzbDrone.Core.IndexerSearch.NzbSearchService.BookSearch(Int32 bookId, Boolean missingOnly, Boolean userInvokedSearch, Boolean interactiveSearch) in D:\a\1\s\src\NzbDrone.Core\IndexerSearch\NzbSearchService.cs:line 47
   at NzbDrone.Core.IndexerSearch.BookSearchService.Execute(BookSearchCommand message) in D:\a\1\s\src\NzbDrone.Core\IndexerSearch\BookSearchService.cs:line 63
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 111
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 42
[Library](http://192.168.20.43:8787/)
[Calendar](http://192.168.20.43:8787/calendar)
[Activity](http://192.168.20.43:8787/activity/queue)
[Wanted](http://192.168.20.43:8787/wanted/missing)
[Settings](http://192.168.20.43:8787/settings)
[System](http://192.168.20.43:8787/system/status)
[Status](http://192.168.20.43:8787/system/status)
[Tasks](http://192.168.20.43:8787/system/tasks)
[Backup](http://192.168.20.43:8787/system/backup)
[Updates](http://192.168.20.43:8787/system/updates)
[Events](http://192.168.20.43:8787/system/events)
[Log Files](http://192.168.20.43:8787/system/logs/files)
```

### Expected Behavior

A search for all missing books would run without error.

### Steps To Reproduce

Library - Books section, set Filter = Missing click search filtered

### Environment

```markdown
- OS: Docker on Unraid 6.10.3  Linux 5.15.46-Unraid x86_64
- Readarr: 0.1.1.1320 Develop
- Docker Install: 20.10.14
- Using Reverse Proxy: None
- Browser: Firefox Developer ed. 104.0b4 (64 bit)
```

### What branch are you running?

Develop

### Trace Logs?

2022-08-01 22:14:37.9|Trace|DiskProviderBase|Deleting file: /config/logs/Readarr.debug.txt
2022-08-01 22:14:37.9|Trace|CommandQueueManager|Updating command status
2022-08-01 22:14:37.9|Trace|EventAggregator|Publishing CommandUpdatedEvent
2022-08-01 22:14:37.9|Trace|EventAggregator|CommandUpdatedEvent -> CommandController
2022-08-01 22:14:37.9|Trace|EventAggregator|CommandUpdatedEvent <- CommandController
2022-08-01 22:14:37.9|Trace|EventAggregator|Publishing CommandExecutedEvent
2022-08-01 22:14:37.9|Trace|EventAggregator|CommandExecutedEvent -> TaskManager
2022-08-01 22:14:37.9|Trace|EventAggregator|CommandExecutedEvent <- TaskManager
2022-08-01 22:14:37.9|Trace|EventAggregator|CommandExecutedEvent -> TaskController
2022-08-01 22:14:37.9|Trace|EventAggregator|CommandExecutedEvent <- TaskController
2022-08-01 22:14:37.9|Trace|CommandExecutor|DeleteLogFilesCommand <- DeleteLogFilesService [00:00:00.0822615]
2022-08-01 22:14:38.0|Trace|Http|Req: 384 [GET] /api/v1/command (from 192.168.10.52 Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:104.0) Gecko/20100101 Firefox/104.0)
2022-08-01 22:14:38.0|Trace|CommandQueueManager|Getting all commands
2022-08-01 22:14:38.0|Trace|Http|Res: 384 [GET] /api/v1/command: 200.OK (3 ms)
2022-08-01 22:14:38.0|Debug|Api|[GET] /api/v1/command: 200.OK (3 ms)
2022-08-01 22:14:38.2|Trace|Scheduler|Pending Tasks: 0
2022-08-01 22:14:41.7|Trace|Http|Req: 385 [GET] /api/v1/log/file (from 192.168.10.52 Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:104.0) Gecko/20100101 Firefox/104.0)
2022-08-01 22:14:41.7|Trace|Http|Res: 385 [GET] /api/v1/log/file: 200.OK (4 ms)
2022-08-01 22:14:41.7|Debug|Api|[GET] /api/v1/log/file: 200.OK (4 ms)
2022-08-01 22:14:50.4|Trace|Http|Req: 386 [POST] /api/v1/command (from 192.168.10.52 Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:104.0) Gecko/20100101 Firefox/104.0)
2022-08-01 22:14:50.4|Trace|CommandQueueManager|Publishing BookSearch
2022-08-01 22:14:50.4|Trace|CommandQueueManager|Checking if command is queued or started: BookSearch
2022-08-01 22:14:50.4|Trace|CommandQueueManager|Inserting new command: BookSearch
2022-08-01 22:14:50.4|Trace|CommandExecutor|BookSearchCommand -> BookSearchService
2022-08-01 22:14:50.4|Trace|Http|Res: 386 [POST] /api/v1/command: 201.Created (18 ms)
2022-08-01 22:14:50.4|Trace|CommandQueueManager|Marking command as started: BookSearch
2022-08-01 22:14:50.4|Debug|Api|[POST] /api/v1/command: 201.Created (18 ms)
2022-08-01 22:14:50.4|Trace|EventAggregator|Publishing CommandUpdatedEvent
2022-08-01 22:14:50.4|Trace|EventAggregator|CommandUpdatedEvent -> CommandController
2022-08-01 22:14:50.4|Trace|EventAggregator|CommandUpdatedEvent <- CommandController
2022-08-01 22:14:50.4|Trace|CommandQueueManager|Updating command status
2022-08-01 22:14:50.5|Trace|EventAggregator|Publishing CommandUpdatedEvent
2022-08-01 22:14:50.5|Trace|EventAggregator|CommandUpdatedEvent -> CommandController
2022-08-01 22:14:50.5|Trace|EventAggregator|CommandUpdatedEvent <- CommandController
2022-08-01 22:14:50.5|Trace|EventAggregator|Publishing CommandExecutedEvent
2022-08-01 22:14:50.5|Trace|EventAggregator|CommandExecutedEvent -> TaskManager
2022-08-01 22:14:50.5|Trace|EventAggregator|CommandExecutedEvent <- TaskManager
2022-08-01 22:14:50.5|Trace|EventAggregator|CommandExecutedEvent -> TaskController
2022-08-01 22:14:50.5|Trace|EventAggregator|CommandExecutedEvent <- TaskController
2022-08-01 22:14:50.5|Trace|CommandExecutor|BookSearchCommand <- BookSearchService [00:00:00.0205959]
2022-08-01 22:14:50.5|Trace|Http|Req: 387 [GET] /api/v1/command (from 192.168.10.52 Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:104.0) Gecko/20100101 Firefox/104.0)
2022-08-01 22:14:50.5|Trace|CommandQueueManager|Getting all commands
2022-08-01 22:14:50.5|Error|CommandExecutor|Error occurred while executing task BookSearch

[v0.1.1.1320] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.IndexerSearch.NzbSearchService.BookSearch(Book book, Boolean missingOnly, Boolean userInvokedSearch, Boolean interactiveSearch) in D:\a\1\s\src\NzbDrone.Core\IndexerSearch\NzbSearchService.cs:line 74
   at NzbDrone.Core.IndexerSearch.NzbSearchService.BookSearch(Int32 bookId, Boolean missingOnly, Boolean userInvokedSearch, Boolean interactiveSearch) in D:\a\1\s\src\NzbDrone.Core\IndexerSearch\NzbSearchService.cs:line 47
   at NzbDrone.Core.IndexerSearch.BookSearchService.Execute(BookSearchCommand message) in D:\a\1\s\src\NzbDrone.Core\IndexerSearch\BookSearchService.cs:line 63
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 111
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 42

2022-08-01 22:14:50.5|Trace|Http|Res: 387 [GET] /api/v1/command: 200.OK (4 ms)
2022-08-01 22:14:50.5|Debug|Api|[GET] /api/v1/command: 200.OK (4 ms)
2022-08-01 22:14:53.7|Trace|Http|Req: 388 [GET] /api/v1/health (from 192.168.10.52 Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:104.0) Gecko/20100101 Firefox/104.0)
2022-08-01 22:14:53.7|Trace|Http|Res: 388 [GET] /api/v1/health: 200.OK (3 ms)
2022-08-01 22:14:53.7|Trace|Http|Req: 389 [GET] /api/v1/system/status (from 192.168.10.52 Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:104.0) Gecko/20100101 Firefox/104.0)
2022-08-01 22:14:53.7|Trace|Http|Req: 390 [GET] /api/v1/diskspace (from 192.168.10.52 Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:104.0) Gecko/20100101 Firefox/104.0)
2022-08-01 22:14:53.7|Debug|Api|[GET] /api/v1/health: 200.OK (3 ms)
2022-08-01 22:14:53.7|Trace|Http|Res: 389 [GET] /api/v1/system/status: 200.OK (2 ms)
2022-08-01 22:14:53.7|Debug|Api|[GET] /api/v1/system/status: 200.OK (2 ms)
2022-08-01 22:14:53.8|Debug|DiskProvider|path: /books/
2022-08-01 22:14:53.8|Debug|DiskProvider|path: /
2022-08-01 22:14:53.8|Trace|Http|Res: 390 [GET] /api/v1/diskspace: 200.OK (28 ms)
2022-08-01 22:14:53.8|Debug|Api|[GET] /api/v1/diskspace: 200.OK (28 ms)
2022-08-01 22:14:55.0|Trace|Http|Req: 391 [GET] /api/v1/log/file (from 192.168.10.52 Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:104.0) Gecko/20100101 Firefox/104.0)
2022-08-01 22:14:55.0|Trace|Http|Res: 391 [GET] /api/v1/log/file: 200.OK (4 ms)
2022-08-01 22:14:55.0|Debug|Api|[GET] /api/v1/log/file: 200.OK (4 ms)
2022-08-01 22:14:58.2|Trace|Http|Req: 392 [GET] /logfile/Readarr.trace.txt (from 192.168.10.52 Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:104.0) Gecko/20100101 Firefox/104.0)

[AB#3411](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3411)

**Comment by bakerboy448** [comment]
Still an issue in 2025?
