### ISSUE TITLE
Importing books gives Invalid Object Reference

### ISSUE THREAD

**Issue by OFark** [Readarr/Readarr#1839]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

A number of books are causing an error during Interactive import:

"/downloads/Books/Harlan Coben - Win (retail) (epub)/Harlan Coben - Win (retail) (epub).epub"
"/downloads/Books/Wicked Plants/Amy Stewart - Wicked Plants.mobi"
Anything by Patricia Briggs. 
and a bunch of others.

This is the error from the logs:

> 22-9-5 15:44:14.6|Warn|ReadarrErrorPipeline|System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.MediaFiles.BookImport.Identification.DistanceCalculator.BookDistance(List`1 localTracks, Edition edition) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\BookImport\Identification\DistanceCalculator.cs:line 56
   at NzbDrone.Core.MediaFiles.BookImport.Identification.IdentificationService.GetBestRelease(LocalEdition localAlbumRelease, List`1 candidateReleases, List`1 extraTracksOnDisk) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\BookImport\Identification\IdentificationService.cs:line 177
   at NzbDrone.Core.MediaFiles.BookImport.Identification.IdentificationService.IdentifyRelease(LocalEdition localAlbumRelease, IdentificationOverrides idOverrides, ImportDecisionMakerConfig config) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\BookImport\Identification\IdentificationService.cs:line 149
   at NzbDrone.Core.MediaFiles.BookImport.Identification.IdentificationService.Identify(List`1 localTracks, IdentificationOverrides idOverrides, ImportDecisionMakerConfig config) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\BookImport\Identification\IdentificationService.cs:line 84
   at NzbDrone.Core.MediaFiles.BookImport.ImportDecisionMaker.GetImportDecisions(List`1 musicFiles, IdentificationOverrides idOverrides, ImportDecisionMakerInfo itemInfo, ImportDecisionMakerConfig config) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\BookImport\ImportDecisionMaker.cs:line 156
   at NzbDrone.Core.MediaFiles.BookImport.Manual.ManualImportService.ProcessFolder(String folder, String downloadId, Author author, FilterFilesType filter, Boolean replaceExistingFiles) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\BookImport\Manual\ManualImportService.cs:line 155
   at NzbDrone.Core.MediaFiles.BookImport.Manual.ManualImportService.GetMediaFiles(String path, String downloadId, Author author, FilterFilesType filter, Boolean replaceExistingFiles) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\BookImport\Manual\ManualImportService.cs:line 116
   at Readarr.Api.V1.ManualImport.ManualImportModule.GetMediaFiles() in D:\a\1\s\src\Readarr.Api.V1\ManualImport\ManualImportModule.cs:line 64
   at Readarr.Http.REST.RestModule`1.<set_GetResourceAll>b__33_0(Object options) in D:\a\1\s\src\Readarr.Http\REST\RestModule.cs:line 137
   at Nancy.NancyModule.<>c__DisplayClass14_0`1.<Get>b__0(Object args)
   at Nancy.NancyModule.<>c__DisplayClass16_0`1.<Get>b__0(Object args, CancellationToken ct)
   at Nancy.Routing.Route`1.Invoke(DynamicDictionary parameters, CancellationToken cancellationToken)
   at Nancy.Routing.DefaultRouteInvoker.Invoke(Route route, CancellationToken cancellationToken, DynamicDictionary parameters, NancyContext context)
   at Nancy.Routing.DefaultRequestDispatcher.Dispatch(NancyContext context, CancellationToken cancellationToken)
   at Nancy.NancyEngine.InvokeRequestLifeCycle(NancyContext context, CancellationToken cancellationToken, IPipelines pipelines)

### Expected Behavior

I expect Interactive import to work without throwing errors and to maybe refuse to import the file if there is something wrong with it

### Environment

```markdown
- OS: Unraid 6.10.3
- Readarr: 0.1.0.261
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Chrome
```

### What branch are you running?

Nightly

### Trace Logs?

22-9-5 15:44:14.6|Warn|ReadarrErrorPipeline|System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.MediaFiles.BookImport.Identification.DistanceCalculator.BookDistance(List`1 localTracks, Edition edition) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\BookImport\Identification\DistanceCalculator.cs:line 56
   at NzbDrone.Core.MediaFiles.BookImport.Identification.IdentificationService.GetBestRelease(LocalEdition localAlbumRelease, List`1 candidateReleases, List`1 extraTracksOnDisk) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\BookImport\Identification\IdentificationService.cs:line 177
   at NzbDrone.Core.MediaFiles.BookImport.Identification.IdentificationService.IdentifyRelease(LocalEdition localAlbumRelease, IdentificationOverrides idOverrides, ImportDecisionMakerConfig config) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\BookImport\Identification\IdentificationService.cs:line 149
   at NzbDrone.Core.MediaFiles.BookImport.Identification.IdentificationService.Identify(List`1 localTracks, IdentificationOverrides idOverrides, ImportDecisionMakerConfig config) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\BookImport\Identification\IdentificationService.cs:line 84
   at NzbDrone.Core.MediaFiles.BookImport.ImportDecisionMaker.GetImportDecisions(List`1 musicFiles, IdentificationOverrides idOverrides, ImportDecisionMakerInfo itemInfo, ImportDecisionMakerConfig config) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\BookImport\ImportDecisionMaker.cs:line 156
   at NzbDrone.Core.MediaFiles.BookImport.Manual.ManualImportService.ProcessFolder(String folder, String downloadId, Author author, FilterFilesType filter, Boolean replaceExistingFiles) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\BookImport\Manual\ManualImportService.cs:line 155
   at NzbDrone.Core.MediaFiles.BookImport.Manual.ManualImportService.GetMediaFiles(String path, String downloadId, Author author, FilterFilesType filter, Boolean replaceExistingFiles) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\BookImport\Manual\ManualImportService.cs:line 116
   at Readarr.Api.V1.ManualImport.ManualImportModule.GetMediaFiles() in D:\a\1\s\src\Readarr.Api.V1\ManualImport\ManualImportModule.cs:line 64
   at Readarr.Http.REST.RestModule`1.<set_GetResourceAll>b__33_0(Object options) in D:\a\1\s\src\Readarr.Http\REST\RestModule.cs:line 137
   at Nancy.NancyModule.<>c__DisplayClass14_0`1.<Get>b__0(Object args)
   at Nancy.NancyModule.<>c__DisplayClass16_0`1.<Get>b__0(Object args, CancellationToken ct)
   at Nancy.Routing.Route`1.Invoke(DynamicDictionary parameters, CancellationToken cancellationToken)
   at Nancy.Routing.DefaultRouteInvoker.Invoke(Route route, CancellationToken cancellationToken, DynamicDictionary parameters, NancyContext context)
   at Nancy.Routing.DefaultRequestDispatcher.Dispatch(NancyContext context, CancellationToken cancellationToken)
   at Nancy.NancyEngine.InvokeRequestLifeCycle(NancyContext context, CancellationToken cancellationToken, IPipelines pipelines)

[AB#3703](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3703)

**Comment by ta264** [comment]
That version of readarr is comically out of date

**Comment by OFark** [comment]
Hotio's Docker. I'll try the LinuxServer.io one. I couldn;t find the latest version number on Github anywhere, to compare it to.
