### ISSUE TITLE
Unhandled exception when trying to add specific book

### ISSUE THREAD

**Issue by plmcgrn** [Readarr/Readarr#1846]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When attempting to add `Travel by Bullet` by `John Scalzi`, the green button does its animation, and then failed very quickly, leaving no indicator of why it failed or if it did fail.

Looking at the debug logs, it seems the _Search_ mechanism can find the book in Goodreads, but the _Add Book_ mechanism cannot.

I've seen this sporadically with other books, and I know it's likely tied to something in the Goodreads data, but the discrepancy between Search finding the book and the Add Book failing leads me to believe there's a bug in Readarr where one mechanism is fine and the other is using different logic.

### Expected Behavior

Either add the book, or at least show an error to the user in the UI.  Current behavior is to silently suppress the error and write it to the log file.

### Steps To Reproduce

1. Have `John Scalzi` added as an author
2. Search for `Travel by Bullet` in the `Add New` screen
3. Book Add fails silently

### Environment

```markdown
- OS: MacOS
- Readarr: 0.1.1.1320
- Docker Install: yes
- Using Reverse Proxy: no
- Browser: Chrome 105.0.5195.125
```

### What branch are you running?

Develop

### Trace Logs?

```
2022-09-17 14:21:20.2|Debug|Api|[GET] /api/v1/rootFolder: 200.OK (19 ms)
2022-09-17 14:21:24.5|Debug|Api|[GET] /api/v1/search?term=travel%20by%20bullet: 200.OK (665 ms)
2022-09-17 14:21:28.3|Debug|AddBookService|Adding book [98014095][Travel by Bullet]
2022-09-17 14:21:28.9|Debug|BookInfoProxy|Clearing cache for 4763 due to Expired
2022-09-17 14:21:28.9|Error|AddBookService|Book with Foreign Id 98014095 was not found, it may have been removed from Goodreads.
2022-09-17 14:21:28.9|Error|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.

[v0.1.1.1320] FluentValidation.ValidationException: Validation failed: 
 -- GoodreadsId: A book with this ID was not found
   at NzbDrone.Core.Books.AddBookService.AddSkyhookData(Book newBook) in D:\a\1\s\src\NzbDrone.Core\Books\Services\AddBookService.cs:line 117
   at NzbDrone.Core.Books.AddBookService.AddBook(Book book, Boolean doRefresh) in D:\a\1\s\src\NzbDrone.Core\Books\Services\AddBookService.cs:line 47
   at Readarr.Api.V1.Books.BookController.AddBook(BookResource bookResource) in D:\a\1\s\src\Readarr.Api.V1\Books\BookController.cs:line 144
   at lambda_method375(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Readarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Readarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Readarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Readarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Readarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Readarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Readarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Readarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Readarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Readarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)


2022-09-17 14:21:29.0|Warn|ReadarrErrorPipeline|Invalid request Validation failed: 
 -- GoodreadsId: A book with this ID was not found
2022-09-17 14:21:29.0|Debug|Api|[POST] /api/v1/book: 400.BadRequest (674 ms)
```

[AB#3741](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3741)

**Comment by JakeShirley** [comment]
I came here with the same error and the same exact book, pretty funny.

**Comment by JakeShirley** [comment]
Side note: When Plex imported The Dispatcher (also by Scalzi) it insisted it was Travel By Bullet even though the namings were right.  I wonder if GoodReads metadata is fudged.

**Comment by cyndane31** [comment]
Same error, different book. 

The fact that this error is completely silent and there is no method to override and "force" the addition of a book is quite frustrating!

Relevant log entry:
`2023-06-11 17:20:36.2|Error|AddBookService|Book with Foreign Id 838691 was not found, it may have been removed from Goodreads.
2023-06-11 17:20:36.2|Warn|ReadarrErrorPipeline|Invalid request Validation failed: 
 -- GoodreadsId: A book with this ID was not found`

Associated Goodreads page:
https://www.goodreads.com/work/editions/838691-the-end

**Comment by whilefork** [comment]
Same here trying to add https://www.goodreads.com/work/editions/15553789-eleven-twenty-two-sixty-three

**Comment by albert239825** [comment]
Hi, I also have this problem trying to add "The Man Who Would Be King" by Rudyard Kipling. It appears when in the search but when I click the add book button, it says "A book with this ID was not found." I think this a recent thing. Thanks guys!

**Comment by BrendanKOz** [comment]
Adding another mark here. Out of about 1500 books, I have about 6 that can be found via Add New search, but then fail to add with the same error above. The odd issue is that one of the books I tried to add, if I manually search for it on GoodReads, I believe the ID is not the same as the one that Readarr is trying to add.

![image](https://github.com/Readarr/Readarr/assets/8381343/900c43a8-444f-4257-bb3b-4670d4e3f29f)

`Book with Foreign Id 97248708 was not found, it may have been removed from Goodreads.`

![image](https://github.com/Readarr/Readarr/assets/8381343/d0289b65-45e6-47e3-a698-71a96747ece5)

**Comment by grantdobbe** [comment]
Same issue, multiple books. Anything by Asimov; specific examples include:

- https://www.goodreads.com/book/show/41804.I_Robot
- https://www.goodreads.com/book/show/41811.The_Caves_of_Steel

log entries:
```
2023-09-18 22:19:07.9|Error|AddBookService|Book with Foreign Id 1796026 was not found, it may have been removed from Goodreads.
2023-09-18 22:19:07.9|Warn|ReadarrErrorPipeline|Invalid request Validation failed: 
 -- GoodreadsId: A book with this ID was not found
2023-09-18 22:21:35.2|Error|AddBookService|Book with Foreign Id 140376 was not found, it may have been removed from Goodreads.
2023-09-18 22:21:35.2|Warn|ReadarrErrorPipeline|Invalid request Validation failed: 
 -- GoodreadsId: A book with this ID was not found
```

Also happens for Agatha Christie, Ray Bradbury, and Daniel Defoe. 

I can also confirm that the issue happens on a fresh container setup with an empty database and library folder. Same authors as above.

## Environment

- OS: Linux
- Readarr: 0.3.5.2217
- Docker Install: yes
- Using Reverse Proxy: no
- Browser: Firefox 117.0.1

## What branch are you running?

Develop

**Comment by pkishino** [comment]
just started using Readarr and having the same issue with many of my books, Asimov, as mentioned above etc..putting the library setup on hold until this is fixed.

**Comment by bart-kooi** [comment]
Has anyone found a solution or workaround for this yet?
So many books are unable to add due to this error

**Comment by pjones112000** [comment]
I'm having the same problem with Agatha Christie novels, nor is it retrieving any of her books along with a few others here and there.  I've also noticed that if you use author: 123715, nothing returns.   I've noticed that when searching by name and you select one of her books, A Pocket Full Of Rye, the logs say that foreign id 2887138 was not found; however, according to GoodReads, the ID should actually be 834378; however, if you try adding with edition:834378, nothing returns.  It's like the search and the retrieval are sometimes using different IDs.

**Comment by magjo67** [comment]
If I add Agatha Christie and do a refresh & scan it only find:

"And Then There Were None : The Queen Of Mystery"

Then readarr try to match my 103 Christie-books to that name.

If there are some code-ing problem on Goodreads on Christie it would be hard to find.

**Comment by dontfearSP** [comment]
Thank God I found this thread. Having the same issue with Asimov's "I, Robot"... Anyone found a solution yet?

**Comment by thetic** [comment]
Still experiencing this problem.

**Comment by bakerboy448** [comment]
Part of the larger metadata issues. Referr to pinned GHI, the pins in the discord, and the metadata issues page on the wiki
