### ISSUE TITLE
Importing books errors out - sequence contains more than one element

### ISSUE THREAD

**Issue by rpharrison** [Readarr/Readarr#1890]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When trying to import unmapped files during the file search this error appears: Sequence contains more than one element.

This also happens quite often when adding a author or book or trying to add books (books randomly fail to add)

### Expected Behavior

The book to be imported.

### Steps To Reproduce

1. W11 x64
2. Nightly
3. Fresh install

### Environment

```markdown
- OS: 
- Readarr:
- Docker Install:
- Using Reverse Proxy:
- Browser:
- Database:
```

### What branch are you running?

Nightly

### Trace Logs?

[Readarr.trace.txt](https://github.com/Readarr/Readarr/files/9739868/Readarr.trace.txt)

[AB#3885](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3885)

**Comment by mikeage** [comment]
I have the same issue: lscr.io/linuxserver/readarr:develop, on hash a74d6046f262 (from Nov 11th). The book is "Sandra Brown - The Rana Look", which I've downloaded from MyAnonamouse. I received the following three files:

```
a74e755b45ad88c9272b88f94b1db9bb  /mnt/sdb1/new/sb/Brown, S ( 1986 ) The Rana Look - Sandra Brown.jpg
5b949005d1d94c56a31dca113081df34  /mnt/sdb1/new/sb/Brown, S ( 1986 ) The Rana Look - Sandra Brown.mobi
3b8f68866570569e4ab9d5415f6f8f1f  /mnt/sdb1/new/sb/Brown, S ( 1986 ) The Rana Look - Sandra Brown.opf
```

I can provide the `.mobi` directly if it will help.

I didn't see anything interesting in the logs besides the backtrace, but here it is anyway:
<details>
  <summary>Backtrace</summary>

```
[Fatal] ReadarrErrorPipeline: Request Failed. GET /api/v1/manualimport

[v0.1.1.1320] System.InvalidOperationException: Sequence contains more than one element
   at System.Linq.ThrowHelper.ThrowMoreThanOneElementException()
   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Boolean& found)
   at Readarr.Api.V1.Books.BookResourceMapper.ToResource(Book model) in D:\a\1\s\src\Readarr.Api.V1\Books\BookResource.cs:line 47
   at Readarr.Api.V1.ManualImport.ManualImportResourceMapper.ToResource(ManualImportItem model) in D:\a\1\s\src\Readarr.Api.V1\ManualImport\ManualImportResource.cs:line 35
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at Readarr.Api.V1.ManualImport.ManualImportResourceMapper.ToResource(IEnumerable`1 models) in D:\a\1\s\src\Readarr.Api.V1\ManualImport\ManualImportResource.cs:line 63
   at Readarr.Api.V1.ManualImport.ManualImportController.GetMediaFiles(String folder, String downloadId, Nullable`1 authorId, Boolean filterExistingFiles, Boolean replaceExistingFiles) in D:\a\1\s\src\Readarr.Api.V1\ManualImport\ManualImportController.cs:line 53
   at lambda_method354(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Readarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Readarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Readarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Readarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Readarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Readarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Readarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Readarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Readarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Readarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```
</details>

**Comment by bakerboy448** [comment]
Closing in lieu of #1573
