### ISSUE TITLE
Importing Books fails

### ISSUE THREAD

**Issue by kahn10** [Readarr/Readarr#19]
**Describe the bug**
When importing authors from goodreads list the process never finishes. An error occurs in the logs (below) and appears to be fatal.

List currently has about 800 books on it.

**To Reproduce**
Create a list of "want to read" books on goodreads.com
Link account in Import lists and check "Want to Read"
Start "Import List Sync" in Tasks
Check logs

**Expected behavior**
Add authors to list

**Logs**
20-5-9 14:56:08.8|Info|ImportListSyncService|Starting Import List Sync
20-5-9 14:57:38.1|Info|ImportListSyncService|Processing 1043 list items
20-5-9 14:58:06.4|Warn|SkyHookProxy|An item with the same key has already been added. Key: amzn1.gr.book.v1.9XobLHlP-sUwLdwKEcccBQ

[v0.1.0.63] System.ArgumentException: An item with the same key has already been added. Key: amzn1.gr.book.v1.9XobLHlP-sUwLdwKEcccBQ
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey](List`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.MapSeriesLinks(List`1 series, List`1 books, BulkResource resource) in d:\a\1\s\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 290
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.MapSearchResult(BookSearchResource resource) in d:\a\1\s\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 447
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.SearchForNewBook(String title, String artist) in d:\a\1\s\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 192

20-5-9 14:58:06.4|Error|CommandExecutor|Error occurred while executing task ImportListSync

[v0.1.0.63] NzbDrone.Core.MetadataSource.SkyHook.SkyHookException: Search for 'The Art of War' failed. Invalid response received from ReadarrAPI.
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.SearchForNewBook(String title, String artist) in d:\a\1\s\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 192
   at NzbDrone.Core.ImportLists.ImportListSyncService.MapAlbumReport(ImportListItemInfo report) in d:\a\1\s\src\NzbDrone.Core\ImportLists\ImportListSyncService.cs:line 163
   at NzbDrone.Core.ImportLists.ImportListSyncService.ProcessReports(List`1 reports) in d:\a\1\s\src\NzbDrone.Core\ImportLists\ImportListSyncService.cs:line 107
   at NzbDrone.Core.ImportLists.ImportListSyncService.SyncAll() in d:\a\1\s\src\NzbDrone.Core\ImportLists\ImportListSyncService.cs:line 66
   at NzbDrone.Core.ImportLists.ImportListSyncService.Execute(ImportListSyncCommand message) in d:\a\1\s\src\NzbDrone.Core\ImportLists\ImportListSyncService.cs:line 303
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in d:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 112
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in d:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 42

**System info (please complete the following information):**
 - Readarr Version: 0.1.0.63 (docker: hotio/readarr)
 - Operating System: MacOS 10.13.6 High Sierra
 - .net Framework (Windows) or mono (macOS/Linux) Version: Unknown
Issuing "mono --version" in the docker image returns "mono: not found"

**Comment by kahn10** [comment]
The problem persists in 0.1.0.77:
20-5-12 14:00:44.6|Warn|SkyHookProxy|An item with the same key has already been added. Key: amzn1.gr.book.v1.9XobLHlP-sUwLdwKEcccBQ

[v0.1.0.77] System.ArgumentException: An item with the same key has already been added. Key: amzn1.gr.book.v1.9XobLHlP-sUwLdwKEcccBQ
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey](List`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.MapSeriesLinks(List`1 series, List`1 books, BulkResource resource) in d:\a\1\s\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 290
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.MapSearchResult(BookSearchResource resource) in d:\a\1\s\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 447
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.SearchForNewBook(String title, String artist) in d:\a\1\s\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 192

20-5-12 14:00:44.7|Error|CommandExecutor|Error occurred while executing task ImportListSync

[v0.1.0.77] NzbDrone.Core.MetadataSource.SkyHook.SkyHookException: Search for 'The Prince' failed. Invalid response received from ReadarrAPI.
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.SearchForNewBook(String title, String artist) in d:\a\1\s\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 192
   at NzbDrone.Core.ImportLists.ImportListSyncService.MapAlbumReport(ImportListItemInfo report) in d:\a\1\s\src\NzbDrone.Core\ImportLists\ImportListSyncService.cs:line 163
   at NzbDrone.Core.ImportLists.ImportListSyncService.ProcessReports(List`1 reports) in d:\a\1\s\src\NzbDrone.Core\ImportLists\ImportListSyncService.cs:line 107
   at NzbDrone.Core.ImportLists.ImportListSyncService.SyncAll() in d:\a\1\s\src\NzbDrone.Core\ImportLists\ImportListSyncService.cs:line 66
   at NzbDrone.Core.ImportLists.ImportListSyncService.Execute(ImportListSyncCommand message) in d:\a\1\s\src\NzbDrone.Core\ImportLists\ImportListSyncService.cs:line 303
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in d:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 112
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in d:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 42

**Comment by kahn10** [comment]
After running a few times and deleting offending books I was able to get it to import the list.

**Comment by tingtom** [comment]
Are you able to provide a link to the list so we can test it out?

amzn1.gr.book.v1.9XobLHlP-sUwLdwKEcccBQ is [this book](http://www.goodreads.com/book/show/6878022-the-prince-by-niccolo-machiavelli-and-the-art-of-war-by-sun-tzu) in Goodreads, do you have another book by either author or the same book in the list?

**Comment by bakerboy448** [comment]
Is this still occuring on recent builds?

**Comment by kahn10** [comment]
I have been able to successfully import lists. I believe whatever this issue was is no longer happening.

**Comment by kahn10** [comment]
It looks like I spoke too soon. It had previously imported books, but now it back to failing.

```
21-4-11 17:24:33.6|Warn|GoodreadsBookshelf|Error fetching bookshelves from Goodreads

[v0.1.0.583] System.Net.WebException: Cannot assign requested address [2606:4700:e4::ac40:a915]:443 (auth.servarr.com:443): 'https://auth.servarr.com/v1/goodreads/sign'
 ---> System.Net.WebException: Cannot assign requested address [2606:4700:e4::ac40:a915]:443 (auth.servarr.com:443)
 ---> System.Net.Http.HttpRequestException: Cannot assign requested address [2606:4700:e4::ac40:a915]:443 (auth.servarr.com:443)
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (99): Cannot assign requested address [2606:4700:e4::ac40:a915]:443
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.Socket.Connect(IPAddress[] addresses, Int32 port)
--- End of stack trace from previous location ---
   at System.Net.Sockets.Socket.Connect(IPAddress[] addresses, Int32 port)
   at System.Net.Sockets.Socket.Connect(String host, Int32 port)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Http.ConnectHelper.Connect(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.Connect(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.SocketsHttpHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClientHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.HttpWebRequest.SendRequest(Boolean async)
   at System.Net.HttpWebRequest.GetResponse()
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in D:\a\1\s\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 90
   --- End of inner exception stack trace ---
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in D:\a\1\s\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 113
   at NzbDrone.Common.Http.HttpClient.ExecuteRequest(HttpRequest request, CookieContainer cookieContainer) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 119
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 55
   at NzbDrone.Common.Http.HttpClient.Post(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 256
   at NzbDrone.Common.Http.HttpClient.Post[T](HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 262
   at NzbDrone.Core.ImportLists.Goodreads.GoodreadsImportListBase`1.GetAuthorizationHeader(OAuthRequest oAuthRequest) in D:\a\1\s\src\NzbDrone.Core\ImportLists\Goodreads\GoodreadsImportListBase.cs:line 153
   at NzbDrone.Core.ImportLists.Goodreads.GoodreadsImportListBase`1.OAuthGet(HttpRequestBuilder builder) in D:\a\1\s\src\NzbDrone.Core\ImportLists\Goodreads\GoodreadsImportListBase.cs:line 135
   at NzbDrone.Core.ImportLists.Goodreads.GoodreadsBookshelf.GetReviews(String shelf, Int32 page) in D:\a\1\s\src\NzbDrone.Core\ImportLists\Goodreads\Bookshelf\GoodreadsBookshelf.cs:line 144
```

**Comment by ta264** [comment]
I think that is a different issue, and most likely a problem with your local networking.

I'm going to close this and if you need help figuring out the networking come by the discord.

**Comment by kahn10** [comment]
I don't believe it is a networking issue. The network setup is fairly straightforward and works fine for the other docker servers. It works fine in Readarr for all other tasks, and in fact worked for this import process right until I added more books.
