### ISSUE TITLE
Importing a specific book throws error and does not import

### ISSUE THREAD

**Issue by delize** [Readarr/Readarr#1907]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When importing a [specific book](https://www.goodreads.com/book/show/25720849-kitchen-hacks) that is ~500 MB in size, I am constantly met with the trace logs below. 

This so far has only happens with this book, other formats and books can import fine.

### Expected Behavior

Book imports without issue.

### Steps To Reproduce

1. Have book in accessible file path
2. Manually import book
3. Book causes trace errors below

### Environment

```markdown
- OS: Ubuntu 22.04.1
- Readarr: 0.1.1.1426
- Docker Install: Yes / LinuxServer
- Using Reverse Proxy: Yes / LinuxServer's SWAG
- Browser: Chrome v107
- Database: Sqlite 3.36.0
```

### What branch are you running?

Nightly

### Trace Logs?

```2022-10-29 16:22:27.3|Trace|EventAggregator|Publishing QueueUpdatedEvent
2022-10-29 16:22:27.3|Trace|EventAggregator|QueueUpdatedEvent -> QueueController
2022-10-29 16:22:27.3|Trace|EventAggregator|QueueUpdatedEvent <- QueueController
2022-10-29 16:22:27.3|Trace|EventAggregator|QueueUpdatedEvent -> QueueDetailsController
2022-10-29 16:22:27.3|Trace|EventAggregator|QueueUpdatedEvent <- QueueDetailsController
2022-10-29 16:22:27.3|Trace|EventAggregator|QueueUpdatedEvent -> QueueStatusController
2022-10-29 16:22:27.3|Trace|EventAggregator|QueueUpdatedEvent <- QueueStatusController
2022-10-29 16:22:27.3|Trace|EventAggregator|TrackedDownloadRefreshedEvent <- QueueService
2022-10-29 16:22:27.3|Trace|CommandQueueManager|Publishing ProcessMonitoredDownloads
2022-10-29 16:22:27.3|Trace|CommandQueueManager|Checking if command is queued or started: ProcessMonitoredDownloads
2022-10-29 16:22:27.3|Trace|CommandQueueManager|Command is already in progress: ProcessMonitoredDownloads
2022-10-29 16:22:27.3|Trace|CommandQueueManager|Updating command status
2022-10-29 16:22:27.3|Trace|EventAggregator|Publishing CommandExecutedEvent
2022-10-29 16:22:27.3|Trace|EventAggregator|CommandExecutedEvent -> TaskManager
2022-10-29 16:22:27.3|Trace|TaskManager|Updating last run time for: NzbDrone.Core.Download.RefreshMonitoredDownloadsCommand
2022-10-29 16:22:27.3|Trace|EventAggregator|CommandExecutedEvent <- TaskManager
2022-10-29 16:22:27.3|Trace|EventAggregator|CommandExecutedEvent -> TaskController
2022-10-29 16:22:27.3|Trace|EventAggregator|CommandExecutedEvent <- TaskController
2022-10-29 16:22:27.3|Trace|CommandExecutor|RefreshMonitoredDownloadsCommand <- DownloadMonitoringService [00:00:00.0042161]
2022-10-29 16:22:27.4|Trace|Http|Req: 1906 [GET] /readarr/api/v1/queue?page=1&pageSize=20&sortDirection=ascending&sortKey=timeleft&includeUnknownAuthorItems=false (from 10.10.10.1 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36)
2022-10-29 16:22:27.4|Trace|Http|Req: 1907 [GET] /readarr/api/v1/queue/details?authorId=80 (from 10.10.10.1 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36)
2022-10-29 16:22:27.4|Trace|Http|Req: 1908 [GET] /readarr/api/v1/command (from 10.10.10.1 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36)
2022-10-29 16:22:27.4|Trace|CommandQueueManager|Getting all commands
2022-10-29 16:22:27.4|Trace|Http|Res: 1906 [GET] /readarr/api/v1/queue?page=1&pageSize=20&sortDirection=ascending&sortKey=timeleft&includeUnknownAuthorItems=false: 200.OK (1 ms)
2022-10-29 16:22:27.4|Trace|Http|Res: 1907 [GET] /readarr/api/v1/queue/details?authorId=80: 200.OK (1 ms)
2022-10-29 16:22:27.4|Trace|Http|Res: 1908 [GET] /readarr/api/v1/command: 200.OK (1 ms)
2022-10-29 16:22:27.4|Trace|Http|Req: 1909 [GET] /readarr/api/v1/command (from 10.10.10.1 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36)
2022-10-29 16:22:27.4|Trace|CommandQueueManager|Getting all commands
2022-10-29 16:22:27.4|Trace|Http|Res: 1909 [GET] /readarr/api/v1/command: 200.OK (1 ms)
2022-10-29 16:22:29.4|Trace|Http|Req: 1910 [GET] /readarr/api/v1/log?page=1&pageSize=50&sortDirection=descending&sortKey=time (from 10.10.10.1 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36)
2022-10-29 16:22:29.4|Trace|Http|Res: 1910 [GET] /readarr/api/v1/log?page=1&pageSize=50&sortDirection=descending&sortKey=time: 200.OK (2 ms)
2022-10-29 16:22:29.4|Trace|CalibreProxy|Read 545471446 bytes from /pool/downloads/complete/prowlarr/ebooks/America's Test Kitchen Cookbook Collection/Cook's Illustrated Kitchen Hacks How Clever Cooks Get Things Done.epub
2022-10-29 16:22:29.4|Trace|HttpClient|Req: [POST] http://calibre:8081/cdb/add-book/466537601/1/$dummy.epub/books
2022-10-29 16:22:29.4|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2022-10-29 16:22:29.4|Error|ManagedHttpDispatcher|HttpClient error

[v0.1.1.1426] System.Net.Http.HttpRequestException: Error while copying content to a stream.
 ---> System.IO.IOException: Unable to write data to the transport connection: Broken pipe.
 ---> System.Net.Sockets.SocketException (32): Broken pipe
   at System.Net.Sockets.NetworkStream.Write(ReadOnlySpan`1 buffer)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Write(ReadOnlySpan`1 buffer)
   at System.Net.Http.HttpConnection.WriteToStream(ReadOnlySpan`1 source)
   at System.Net.Http.HttpConnection.Write(ReadOnlySpan`1 source)
   at System.Net.Http.HttpConnection.ContentLengthWriteStream.Write(ReadOnlySpan`1 buffer)
   at System.Net.Http.ByteArrayContent.SerializeToStream(Stream stream, TransportContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.CopyTo(Stream stream, TransportContext context, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpContent.CopyTo(Stream stream, TransportContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.SendRequestContentAsync(HttpRequestMessage request, HttpContentWriteStream stream, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithNtAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean isProxyAuth, HttpConnection connection, HttpConnectionPool connectionPool, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.SocketsHttpHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in D:\a\1\s\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 110


2022-10-29 16:22:29.5|Warn|ImportApprovedBooks|Couldn't import book /pool/downloads/complete/prowlarr/ebooks/America's Test Kitchen Cookbook Collection/Cook's Illustrated Kitchen Hacks How Clever Cooks Get Things Done.epub

[v0.1.1.1426] System.Net.Http.HttpRequestException: Error while copying content to a stream.
 ---> System.IO.IOException: Unable to write data to the transport connection: Broken pipe.
 ---> System.Net.Sockets.SocketException (32): Broken pipe
   at System.Net.Sockets.NetworkStream.Write(ReadOnlySpan`1 buffer)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Write(ReadOnlySpan`1 buffer)
   at System.Net.Http.HttpConnection.WriteToStream(ReadOnlySpan`1 source)
   at System.Net.Http.HttpConnection.Write(ReadOnlySpan`1 source)
   at System.Net.Http.HttpConnection.ContentLengthWriteStream.Write(ReadOnlySpan`1 buffer)
   at System.Net.Http.ByteArrayContent.SerializeToStream(Stream stream, TransportContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.CopyTo(Stream stream, TransportContext context, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpContent.CopyTo(Stream stream, TransportContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.SendRequestContentAsync(HttpRequestMessage request, HttpContentWriteStream stream, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithNtAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean isProxyAuth, HttpConnection connection, HttpConnectionPool connectionPool, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.SocketsHttpHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in D:\a\1\s\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 110
   at NzbDrone.Common.Http.HttpClient.ExecuteRequest(HttpRequest request, CookieContainer cookieContainer) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 124
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 59
   at NzbDrone.Common.Http.HttpClient.Post[T](HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 310
   at NzbDrone.Core.Books.Calibre.CalibreProxy.AddBook(BookFile book, CalibreSettings settings) in D:\a\1\s\src\NzbDrone.Core\Books\Calibre\CalibreProxy.cs:line 156
   at NzbDrone.Core.Books.Calibre.CalibreProxy.AddAndConvert(BookFile file, CalibreSettings settings) in D:\a\1\s\src\NzbDrone.Core\Books\Calibre\CalibreProxy.cs:line 84
   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeBookFile(BookFile bookFile, LocalBook localBook, Boolean copyOnly) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\UpgradeMediaFileService.cs:line 112
   at NzbDrone.Core.MediaFiles.BookImport.ImportApprovedBooks.Import(List`1 decisions, Boolean replaceExisting, DownloadClientItem downloadClientItem, ImportMode importMode) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\BookImport\ImportApprovedBooks.cs:line 215


2022-10-29 16:22:29.7|Debug|ImportApprovedBooks|Inserted new trackfiles in 0ms
2022-10-29 16:22:29.7|Trace|ManualImportService|Processing file 17 of 24
2022-10-29 16:22:29.7|Trace|EventAggregator|Publishing CommandUpdatedEvent
2022-10-29 16:22:29.7|Trace|EventAggregator|CommandUpdatedEvent -> CommandController
```

[AB#3980](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3980)

**Comment by delize** [comment]
Has happened to me again with a different book. Are there file size constrains on the importer? This seems to only be happening with files that are >512MB in size.

**Comment by ta264** [comment]
I would guess calibre is choking on it. Check the calibre logs.

**Comment by delize** [comment]
> I would guess calibre is choking on it. Check the calibre logs.

@ta264 , When starting Calibre in debug mode and tailing the logs, I don't see anything related to the import of the book.

```
# cat /tmp/tmp4se86hye.txt
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-abc'
Using calibre Qt style: True
calibre Debug log
calibre 6.7.1  embedded-python: True
Linux-5.15.0-52-generic-x86_64-with-glibc2.35 Linux ('64bit', '')
('Linux', '5.15.0-52-generic', '#58-Ubuntu SMP Thu Oct 13 08:03:55 UTC 2022')
Python 3.10.1
Interface language: None
Successfully initialized third party plugins: Goodreads (1, 7, 1)
calibre 6.7.1  embedded-python: True
Linux-5.15.0-52-generic-x86_64-with-glibc2.35 Linux ('64bit', '')
('Linux', '5.15.0-52-generic', '#58-Ubuntu SMP Thu Oct 13 08:03:55 UTC 2022')
Python 3.10.1
Interface language: None
Successfully initialized third party plugins: Goodreads (1, 7, 1)
QPA platform: xcb
devicePixelRatio: 1.0
logicalDpi: 96.0 x 96.0
physicalDpi: 96.1081081081081 x 95.93223140495867
[0.00] Starting up...
[0.00] Showing splash screen...
[0.05] splash screen shown
[0.05] Initializing db...
[0.09] db initialized
[0.09] Constructing main UI...
Key '' for shortcut Book list header menu is already used by Manage categories, ignoring
[0.73] main UI initialized...
[0.73] Hiding splash screen
Starting QuickView
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-abc'
Unable to detect a launcher for 'file:///tmp/tmp4se86hye.txt'
[21.10] splash screen hidden
[21.10] Started up in 21.10 seconds with 205 books
```

It just sits here, while Readarr marks the import attempt as completed.

The steps I did above were:

1. Start Calibre
2. Restart Calibre in debug mode
3. Import failing book in Readarr
4. Restart Calibre to close out log

So I can't tell if it is Readarr or Calibre here causing the issue, but, since there is no API activity

**Comment by delize** [comment]
And I realized after being jetlagged for a bit, that you also need the Sharing over the net / API logs:

Same process as above: 

1. stop API 
2. clear logs
3. start API
4. restart Calibre in debug mode
5. import book (attempted twice) 
6. restart calibre to close out logging mechanism

<img width="794" alt="image" src="https://user-images.githubusercontent.com/4028612/199853352-3b1ac787-e9b6-4558-bd25-8f9dc12d4aff.png">

**Comment by delize** [comment]
Indeed not a Readarr issue. Needed to modify the Max Allowed File Size on the Calibre side. Sorry for the useless bug report.
<img width="925" alt="Screenshot 2022-11-05 at 00 05 34" src="https://user-images.githubusercontent.com/4028612/200087252-1bda15be-57ac-4748-af4b-43f64b01a597.png">

Once this was modified from `500` to `1024`, uploads worked great.
