### ISSUE TITLE
database locked, high IOPS from readarr and process monitored downloads never finishes

### ISSUE THREAD

**Issue by imro2** [Readarr/Readarr#2101]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I have other arr application running on synology in dockers and readarr is the only one consistently consuming exorbitant amounts of IOPS and creating 90% of disk utilization. The IOPS according to synology resorce monitor are almost entirely writes. It is a fresh installation with only 12 items listed in wanted. There are two items in Activity - Queue. The task "Process Monitored Downloads" never finishes. Trace log is peppered with database locked exceptions.

I have scrolled trough a bunch of the trace logs and the exception seems to be always related to `INSERT INTO Commands` albeit for different "Name".

### Expected Behavior

not consuming 40% of systems IOPS

### Steps To Reproduce

1. start docker

### Environment

```markdown
- OS: Synolody DSM 7
- Readarr: 0.1.1.1320
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: N/A
- Database: sqlite-3.40.1-r0
```

### What branch are you running?

Master

### Trace Logs?

```
2023-01-03 00:58:05.2|Trace|Scheduler|Pending Tasks: 3
2023-01-03 00:58:05.2|Trace|CommandQueueManager|Publishing RefreshMonitoredDownloads
2023-01-03 00:58:05.2|Trace|CommandQueueManager|Checking if command is queued or started: RefreshMonitoredDownloads
2023-01-03 00:58:05.2|Trace|CommandQueueManager|Inserting new command: RefreshMonitoredDownloads
2023-01-03 00:58:35.2|Error|TaskExtensions|Task Error

[v0.1.1.1320] code = Busy (5), message = System.Data.SQLite.SQLiteException (0x800007AF): database is locked
database is locked
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in /_/Dapper/SqlMapper.cs:line 1075
   at Dapper.SqlMapper.QueryMultipleImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 1033
   at Dapper.SqlMapper.QueryMultiple(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 1009
   at NzbDrone.Core.Datastore.BasicRepository`1.Insert(IDbConnection connection, IDbTransaction transaction, TModel model) in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 189
   at NzbDrone.Core.Datastore.BasicRepository`1.Insert(TModel model) in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 147
   at NzbDrone.Core.Messaging.Commands.CommandQueueManager.Push[TCommand](TCommand command, CommandPriority priority, CommandTrigger trigger) in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandQueueManager.cs:line 132
   at NzbDrone.Core.Messaging.Commands.CommandQueueManager.Push(String commandName, Nullable`1 lastExecutionTime, Nullable`1 lastStartTime, CommandPriority priority, CommandTrigger trigger) in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandQueueManager.cs:line 146
   at NzbDrone.Core.Jobs.Scheduler.ExecuteCommands() in D:\a\1\s\src\NzbDrone.Core\Jobs\Scheduler.cs:line 42
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
SQL: 
==== Begin Query Trace ====

QUERY TEXT:
INSERT INTO Commands ("Name", "Body", "Priority", "Status", "QueuedAt", "StartedAt", "EndedAt", "Exception", "Trigger") VALUES (@Name, @Body, @Priority, @Status, @QueuedAt, @StartedAt, @EndedAt, @Exception, @Trigger); SELECT last_insert_rowid() id

PARAMETERS:
Name = ["\"RefreshMonitoredDownloads\""]
Body = [{
  "sendUpdatesToClient": false,
  "updateScheduledTask": true,
  "completionMessage": "Completed",
  "requiresDiskAccess": false,
  "isExclusive": false,
  "isTypeExclusive": false,
  "name": "RefreshMonitoredDownloads",
  "lastExecutionTime": "2023-01-03T06:53:36.8238769Z",
  "lastStartTime": "2023-01-03T06:53:33.2184188Z",
  "trigger": "scheduled",
  "suppressMessages": false
}]
Priority = ["low"]
Status = ["queued"]
QueuedAt = ["2023-01-03T06:58:05.2447424Z"]
StartedAt = [null]
EndedAt = [null]
Exception = [null]
Trigger = ["scheduled"]
Message = [null]
Id = [0]

==== End Query Trace ====
```

[AB#4618](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4618)

**Comment by imro2** [comment]
![image](https://user-images.githubusercontent.com/10169292/210314489-0de7a932-b278-4682-95f4-7831d47fa91f.png)
The huge dip in the middle of the plotted area is Readarr restarting.

**Comment by bakerboy448** [comment]
Database locked is not a bug.  Your system cannot keep up with the required ongoing IO

**Comment by imro2** [comment]
I have radarr, sonarr, and bazarr, and neither one of them is experiencing this issue. Neither one of them consumes 90% of disk IO either. I see this boilerplate answer plastered all over the internet with little to back it up. Any valid reason an idle sitting readarr should be consuming all available write IOPS 100% of the time?

**Comment by bakerboy448** [comment]
Readarr would not be doing that and based on what you're describing it's not possible for readarr to be idle like you say.

Your logs also indicate several other ongoing tasks.

**Comment by imro2** [comment]
Well I don't know what it is doing, but it certainly is consuming all IO for specific disk pool:
![image](https://user-images.githubusercontent.com/10169292/210385750-813fa44c-16ef-4d0c-919b-2321cbf6b665.png)

Note I have two disk pools.

**Comment by imro2** [comment]
If I kill the process, readarr restarts and behaves normally (without excessive IO) for about 2 minutes. It produces 16 trace log files in the process and then the IOs go through the roof. The last trace file is attached and was retrieved for the first time just as the IOs shut up.
[Readarr.trace.txt](https://github.com/Readarr/Readarr/files/10338004/Readarr.trace.txt)

**Comment by PearsonFlyer** [comment]
Your logs indicate that it's still working through importing books. That is resource-intensive. Your Readarr is not sitting idle, as an earlier comment indicated (you should see this with an active task in System / Tasks). That process can take days. Once it's done, I would guess your system will go back to normal.

**Comment by imro2** [comment]
After noticing that most of the log entries are related to 'Jane Austen - Pride and Prejudice' (54% out of 250K+ log entries mentioned either the author or the book) I deleted Jane Austin out of readarr completely as well as deleted the entry for the book out of the queue which resolved the issue and readarr is now behaving normally. I am assuming that the book being a public domain, there is way too many published copies, which kills readarr during the import process.

Maybe this can be replicated by adding 'Pride and Prejudice' to monitored books.

**Comment by imro2** [comment]
Just some more info: I was partially able to recreate the issue on my laptop with SSD. When I say partially, I mean the disk utilization went up to 50%, but it was over within 50 seconds. The entire import process for that single book took about 14 minutes.

I created a new docker instance for readarr, added only Pride and Prejudice to be monitored. The import process produced 16 files worth of trace logs. the cache.db ended up being 123MB. There are only 5 row in the HttpResponse table, but the last row Value column has 125501299 characters. The readarr.db is 94MB and the largest table is Editions with 47835 rows and pgsize of 88313856 (I am assuming that is bytes). This is with only one author added with one book monitored. Pride and Prejudice has 12794 editions.

Somehow this kills readarr on Synology with 5400 rpm hard drives and no SSD cache. I do use btrfs, so not sure if that plays into it. I let it run for about an hour and it would not finish. I guess I could let it try to finish, but not sure how it would affect performance after that.

Anyway, this might not be a bug, but it is definitely something to consider. You may close it if you don't think that this is worth your time.

**Comment by bakerboy448** [comment]
What's your metadata profile details?  That's in theory cut down on editions.

**Comment by imro2** [comment]
it is just the default it came with

![image](https://user-images.githubusercontent.com/10169292/210486485-f92478b3-590a-486b-838b-8ca3a90202f8.png)

**Comment by imro2** [comment]
So I was looking over the logs, comparing them to code base and I think I can pinpoint the high IOPS to `EditionRepository.SetMonitored(Edition edition)`. Relevant log entries:

```
2023-01-04 03:46:54.3|Info|ImportApprovedBooks|Importing book 1/1 [3060926][Pride and Prejudice]
2023-01-04 03:46:54.4|Debug|ImportApprovedBooks|Updating release to [53851157][Pride and Prejudice]
...
2023-01-04 03:47:43.5|Info|ImportApprovedBooks|Importing 1 files
2023-01-04 03:47:43.5|Debug|ImportApprovedBooks|Importing 1 files. replaceExisting: True
```

there is the 49 seconds of high IOPS and pretty much only thing that is happening in the mean time is 

    book.Editions = _editionService.SetMonitored(newRelease); 

So I believe that the whole issue comes down to `UpdateMany(allEditions);` statement in `/src/NzbDrone.Core/Books/Repositories/EditionRepository.cs` - `SetMonitored(Edition edition)`. I don't completely understand why it is a problem though. Readarr can insert those rows without much fuss, so why does the update totally kill it and why is it doing so many writes?

Only thing I can think of is that on each update it has to updated the index, but I would assume that it is smart enough to know that the values in index did not change.

**Comment by bakerboy448** [comment]
You can add `LogSql` attribute as true in the config to log the sql calls to trace

**Comment by imro2** [comment]
So there is basically 12794 entries similar to this:

```
2023-01-09 00:57:48.5|Trace|SqlBuilderExtensions|
==== Begin Query Trace ====

QUERY TEXT:
UPDATE Editions SET "BookId" = @BookId, "ForeignEditionId" = @ForeignEditionId, "TitleSlug" = @TitleSlug, "Isbn13" = @Isbn13, "Asin" = @Asin, "Title" = @Title, "Language" = @Language, "Overview" = @Overview, "Format" = @Format, "IsEbook" = @IsEbook, "Disambiguation" = @Disambiguation, "Publisher" = @Publisher, "PageCount" = @PageCount, "ReleaseDate" = @ReleaseDate, "Images" = @Images, "Links" = @Links, "Ratings" = @Ratings, "Monitored" = @Monitored, "ManualAdd" = @ManualAdd WHERE "Id" = @Id

PARAMETERS:
BookId = [1]
ForeignEditionId = ["\"52742236\""]
TitleSlug = ["\"52742236\""]
Isbn13 = [null]
Asin = ["\"B07YYN3HVT\""]
Title = ["\"PRIDE AND PREJUDICE\""]
Language = [null]
Overview = ["\"Pride and Prejudice is an 1813 romantic novel of manners written by Jane Austen. The novel follows the character development of Elizabeth Bennet, the dynamic protagonist of the book, who learns about the repercussions of hasty judgments and eventually comes to appreciate the difference between superficial goodness and actual goodness. A classic piece filled with comedy, its humour lies in its honest depiction of manners, education, marriage and money during the Regency era in Great Britain.  Mr Bennet of Longbourn estate has five daughters, but because his property is entailed it can only be passed from male heir to male heir. Consequently, Mr Bennet's family will be destitute upon his death. Because his wife also lacks an inheritance, it is imperative that at least one of the girls marry well to support the others upon his death, which is a motivation that drives the plot. Jane Austen's opening line--\"It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife\"—is a sentence filled with irony and sets the tone for the book. The novel revolves around the importance of marrying for love, not simply for economic gain or social prestige, despite the communal pressure to make a good (i.e., wealthy) match.  Pride and Prejudice has delighted readers for years, consistently appearing near the top of lists of \"most-loved books\" among literary scholars and the reading public. It has become one of the most popular novels in English literature with over 20 million copies sold and has inspired many derivatives that abound in modern literature. For more than a century, amateur and professional dramatic adaptations, reprints, unofficial sequels, films, and TV versions of Pride and Prejudice have portrayed the memorable characters and themes of the novel, reaching mass audiences. The 2005 film Pride & Prejudice, starring Keira Knightley and Matthew Macfadyen, is the most recent film adaptation that closely represents the book, with the 2016 action, comedy, and horror spin-off Pride and Prejudice and Zombies being the most recent Hollywood film adaptation.\""]
Format = ["\"Kindle Edition\""]
IsEbook = [true]
Disambiguation = ["\"\""]
Publisher = ["\"\""]
PageCount = [356]
ReleaseDate = ["2019-10-09T00:00:00Z"]
Images = [[
  {
    "url": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1570918910l/52742236.jpg",
    "coverType": "cover",
    "extension": ".jpg"
  }
]]
Links = [[
  {
    "url": "https://www.goodreads.com/book/show/52742236-pride-and-prejudice",
    "name": "Goodreads Book"
  }
]]
Ratings = [{
  "votes": 0,
  "value": 4.28,
  "popularity": 0.0
}]
Monitored = [false]
ManualAdd = [false]
Id = [15857]

==== End Query Trace ====
```

A little excessive in the context of 12000 editions given that only the `Monitored` column is really changing.

Below is the log immediately following the previous entries. As you can see nothing really happens for 56 seconds while the connection is busy executing 12000+ update statements. The SQL statements are dumped (SqlBuilderExtensions.LogQuery) before they are executed.

```
2023-01-09 00:58:18.0|Trace|SqlBuilderExtensions|
==== Begin Query Trace ====

QUERY TEXT:
SELECT ScheduledTasks.*
 FROM ScheduledTasks       

PARAMETERS:

==== End Query Trace ====

2023-01-09 00:58:18.1|Trace|Scheduler|Pending Tasks: 0
2023-01-09 00:58:42.6|Trace|EventAggregator|Publishing BookEditedEvent
2023-01-09 00:58:42.6|Trace|EventAggregator|BookEditedEvent -> AuthorStatisticsService
2023-01-09 00:58:42.6|Trace|EventAggregator|BookEditedEvent <- AuthorStatisticsService
2023-01-09 00:58:42.6|Trace|EventAggregator|BookEditedEvent -> BookController
2023-01-09 00:58:42.6|Trace|SqlBuilderExtensions|
==== Begin Query Trace ====

QUERY TEXT:
SELECT Authors.Id AS AuthorId,
                     Books.Id AS BookId,
                     SUM(COALESCE(BookFiles.Size, 0)) AS SizeOnDisk,
                     1 AS TotalBookCount,
                     CASE WHEN BookFiles.Id IS NULL THEN 0 ELSE 1 END AS AvailableBookCount,
                     CASE WHEN (Books.Monitored = 1 AND (Books.ReleaseDate < @currentDate) OR Books.ReleaseDate IS NULL) OR BookFiles.Id IS NOT NULL THEN 1 ELSE 0 END AS BookCount,
                     CASE WHEN BookFiles.Id IS NULL THEN 0 ELSE COUNT(BookFiles.Id) END AS BookFileCount
 FROM Editions 
JOIN Books ON ("Editions"."BookId" = "Books"."Id")
JOIN Authors ON ("Books"."AuthorMetadataId" = "Authors"."AuthorMetadataId")
  
LEFT JOIN BookFiles ON ("Editions"."Id" = "BookFiles"."EditionId")
 WHERE ("Editions"."Monitored" = @Clause5_P1) AND ("Authors"."Id" = @Clause9_P1)
 
GROUP BY Authors.Id , Books.Id
  

PARAMETERS:
Clause5_P1 = [true]
Clause9_P1 = [1]
currentDate = ["2023-01-09T00:58:42.658755Z"]

==== End Query Trace ====


2023-01-09 00:58:44.2|Trace|EventAggregator|BookEditedEvent <- BookController
2023-01-09 00:58:44.2|Trace|EventAggregator|BookEditedEvent -> AuthorController
2023-01-09 00:58:44.2|Trace|SqlBuilderExtensions|
==== Begin Query Trace ====

QUERY TEXT:
SELECT Books.*
 FROM Books    WHERE (("Books"."AuthorMetadataId" IN (1)) AND ("Books"."ReleaseDate" > @Clause1_P1))
 
GROUP BY Books.AuthorMetadataId
 HAVING Books.ReleaseDate = MIN(Books.ReleaseDate)
 

PARAMETERS:
Clause1_P1 = ["2023-01-09T00:58:44.2469527Z"]

==== End Query Trace ====


2023-01-09 00:58:44.2|Trace|SqlBuilderExtensions|
==== Begin Query Trace ====

QUERY TEXT:
SELECT Books.*
 FROM Books    WHERE (("Books"."AuthorMetadataId" IN (1)) AND ("Books"."ReleaseDate" < @Clause1_P1))
 
GROUP BY Books.AuthorMetadataId
 HAVING Books.ReleaseDate = MAX(Books.ReleaseDate)
 

PARAMETERS:
Clause1_P1 = ["2023-01-09T00:58:44.2547252Z"]

==== End Query Trace ====


2023-01-09 00:58:44.2|Trace|SqlBuilderExtensions|
==== Begin Query Trace ====

QUERY TEXT:
SELECT RootFolders.*
 FROM RootFolders       

PARAMETERS:

==== End Query Trace ====


2023-01-09 00:58:44.2|Trace|EventAggregator|BookEditedEvent <- AuthorController
2023-01-09 00:58:44.2|Info|ImportApprovedBooks|Importing 1 files
2023-01-09 00:58:44.2|Debug|ImportApprovedBooks|Importing 1 files. replaceExisting: True
```

I can see that under normal circumstances updating all fields whether they need it or not is not a big deal. But with this many editions it becomes a problem. I am assuming that the enhancement is going to be to limit editions? Otherwise there would probably have to be an enhancement to only updated fields/rows that really changed.

Thank you for working on this, or at  lease considering it. Let me know if you need anything else.
