### ISSUE TITLE
Releases Which Cannot Be Parsed, Cannot Be Downloaded

### ISSUE THREAD

**Issue by thegranddesign** [Readarr/Readarr#2111]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Generally I first want to say that, even as a beta, this software has been a dream to use.  I think this speaks volumes of the overall *arr codebase as well as the Readarr developers.

Unfortunately I've run into one bug that I  am having much difficulty tracking down.  It seems as though when a release cannot be parsed, it then cannot be downloaded.  I do not have any reproduction steps that I can provide for this, but due to the "uncaught" nature of the error, I believe it should be relatively straightforward to track down.

It *seems* as though when a release has a status of "Unable to parse release", when the download is attempted anyway, the item *always* fails with "Unable to parse books in the release" and the download itself is never even attempted.

The stacktrace is listed below.

### Expected Behavior

I would expect that even if the release fails to parse, the download will still occur and allow me to manually import the file.

### Environment

```markdown
- OS: FreeBSD
- Readarr: 0.1.1.1320
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Any
- Database: Whatever installs with the `readarr` package in FreeBSD
```

### What branch are you running?

Develop

### Trace Logs?

```
2023-01-05 23:08:41.2|Error|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.

[v0.1.1.1320] NzbDrone.Core.Exceptions.NzbDroneClientException: Unable to parse books in the release
   at Readarr.Api.V1.Indexers.ReleaseController.Create(ReleaseResource release) in D:\a\1\s\src\Readarr.Api.V1\Indexers\ReleaseController.cs:line 132
   at lambda_method572(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Readarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Readarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Readarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Readarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Readarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Readarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Readarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Readarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Readarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Readarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

**Comment by thegranddesign** [comment]
I also want to be clear that this is not a "The file is not downloadable" issue.

Here is what I did to verify that this is not an issue with the API or the server's basic functioning:

1. Use the trace logs to get the exact URL that Readarr is using to parse into the download page
2. Use `curl` to request that URL and save the results to a flie.
3. Open that file
4. Search for a release that has errored via the UI
5. Find the link that is being given to download for that release
6. Use `curl` to download that file
7. Open that file to verify it is correct

All of the above works fine and that downloaded file, when manually sent to my download client and downloaded, imports into Readarr properly.

**Comment by brokenalarms** [comment]
@thegranddesign hitting this with some files too, did you ever resolve?

**Comment by thegranddesign** [comment]
@brokenalarms I did not :(
