### ISSUE TITLE
Adding book causes 500 "Unexpected response from https://api.bookinfo.club/v1/work/xxxx" response without UI feedback

### ISSUE THREAD

**Issue by soswow** [Readarr/Readarr#2123]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When I am trying to press green button "Add XXX" on a page http://192.168.1.167:8787/add/search?term=XXX, it turns into spinner, then after a bit back to green back button. No UI changes indicating there is a problem.

### Expected Behavior

Book is added or there is at least some UI indicating presence of error and steps to mitigate it.

### Steps To Reproduce

1. Normal environment, clean installation on mac. 
2. I search for a book XXXX, try to add it
3. In network tab of devtools I can see:
```
{
  "message": "Unexpected response from https://api.bookinfo.club/v1/work/56475080",
  "description": "System.NotImplementedException: Unexpected response from https://api.bookinfo.club/v1/work/56475080\n   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.PollBook(String foreignBookId) in D:\\a\\1\\s\\src\\NzbDrone.Core\\MetadataSource\\BookInfo\\BookInfoProxy.cs:line 655\n   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.GetBookInfo(String foreignBookId) in D:\\a\\1\\s\\src\\NzbDrone.Core\\MetadataSource\\BookInfo\\BookInfoProxy.cs:line 123\n   at NzbDrone.Core.Books.AddBookService.AddSkyhookData(Book newBook) in D:\\a\\1\\s\\src\\NzbDrone.Core\\Books\\Services\\AddBookService.cs:line 111\n   at NzbDrone.Core.Books.AddBookService.AddBook(Book book, Boolean doRefresh) in D:\\a\\1\\s\\src\\NzbDrone.Core\\Books\\Services\\AddBookService.cs:line 47\n   at Readarr.Api.V1.Books.BookController.AddBook(BookResource bookResource) in D:\\a\\1\\s\\src\\Readarr.Api.V1\\Books\\BookController.cs:line 144\n   at lambda_method484(Closure , Object , Object[] )\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State\u0026 next, Scope\u0026 scope, Object\u0026 state, Boolean\u0026 isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()\n--- End of stack trace from previous location ---\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State\u0026 next, Scope\u0026 scope, Object\u0026 state, Boolean\u0026 isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.\u003CInvokeInnerFilterAsync\u003Eg__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeFilterPipelineAsync\u003Eg__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeAsync\u003Eg__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeAsync\u003Eg__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\n   at Microsoft.AspNetCore.Routing.EndpointMiddleware.\u003CInvoke\u003Eg__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)\n   at Readarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\\a\\1\\s\\src\\Readarr.Http\\Middleware\\BufferingMiddleware.cs:line 28\n   at Readarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\\a\\1\\s\\src\\Readarr.Http\\Middleware\\IfModifiedMiddleware.cs:line 41\n   at Readarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\\a\\1\\s\\src\\Readarr.Http\\Middleware\\CacheHeaderMiddleware.cs:line 33\n   at Readarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\\a\\1\\s\\src\\Readarr.Http\\Middleware\\UrlBaseMiddleware.cs:line 27\n   at Readarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\\a\\1\\s\\src\\Readarr.Http\\Middleware\\VersionMiddleware.cs:line 28\n   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)\n   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)\n   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.\u003CInvoke\u003Eg__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)"
}
```

### Environment

```markdown
- OS: MacOS 13.1
- Readarr: 0.1.1.1320
- Docker Install: N/A
- Using Reverse Proxy: No
- Browser: Chrome
- DB Migration: 21
- .NET Core: Yes (6.0.3)
```

### What branch are you running?

Master

### Trace Logs?

[Readarr.debug.txt](https://github.com/Readarr/Readarr/files/10399515/Readarr.debug.txt)
[Readarr.trace.txt](https://github.com/Readarr/Readarr/files/10399516/Readarr.trace.txt)

[AB#4699](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4699)

**Comment by craized** [comment]
+1 for this issue running docker

Version
    0.1.1.1320
.NET Core
    Yes (6.0.3)
Docker
    Yes

I'm also experiencing Goodbooks API errors searching. Including logs in case they are useful

```2023-01-12 18:06:37.8|Warn|HttpClient|HTTP Error - Res: [POST] https://api.bookinfo.club/v1/book/bulk: 429.TooManyRequests (0 bytes)
2023-01-12 18:06:37.8|Warn|BookInfoProxy|Error mapping search results

[v0.1.1.1504] NzbDrone.Common.Http.TooManyRequestsException: HTTP request failed: [429:TooManyRequests] [POST] at [https://api.bookinfo.club/v1/book/bulk]
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 97
   at NzbDrone.Common.Http.HttpClient.Post(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 302
   at NzbDrone.Common.Http.HttpClient.Post[T](HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 308
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.MapSearchResult(List`1 ids) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\BookInfo\BookInfoProxy.cs:line 462
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.Search(String query, Boolean getAllEditions) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\BookInfo\BookInfoProxy.cs:line 295
```

```2023-01-12 18:07:47.8|Warn|BookInfoProxy|Error searching by book id

[v0.1.1.1504] NzbDrone.Core.MetadataSource.BookInfo.BookInfoException: Unexpected response from https://api.bookinfo.club/v1/book/72346564
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.GetEditionInfo(Int32 id, Boolean getAllEditions) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\BookInfo\BookInfoProxy.cs:line 397
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.SearchByGoodreadsBookId(Int32 id, Boolean getAllEditions) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\BookInfo\BookInfoProxy.cs:line 356
```

**Comment by blastbeng** [comment]
Similar issue here, getting 401:Unauthorized

Version
0.1.1.1320
.NET Core
Yes (6.0.3)
Docker
Yes

Also impacting import list sync

```
readarr    | [v0.1.1.1320] NzbDrone.Common.Http.HttpException: HTTP request failed: [401:Unauthorized] [POST] at [https://api.bookinfo.club/v1/book/bulk]
readarr    |    at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 101
readarr    |    at NzbDrone.Common.Http.HttpClient.Post(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 302
readarr    |    at NzbDrone.Common.Http.HttpClient.Post[T](HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 308
readarr    |    at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.MapSearchResult(List`1 ids) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\BookInfo\BookInfoProxy.cs:line 462
readarr    |    at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.Search(String query, Boolean getAllEditions) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\BookInfo\BookInfoProxy.cs:line 295
```

**Comment by ta264** [comment]
Currently all readarr clients are blocked until we can implement request backing off when the server is struggling.
