### ISSUE TITLE
Unable to install - PostgreSQL Options Error

### ISSUE THREAD

**Issue by jakesteele** [Readarr/Readarr#2223]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Trying to install Readarr on a fresh copy of windows 10, directly after Sonarr, Radarr and Prowlarr installed.

Installer hangs on removing previous windows service, install fails, application doesn’t run.

### Expected Behavior

Install works correctly, application runs, I can visit local host and see Readarr.

### Steps To Reproduce

Using the Windows x64 Installer, running on Windows Server 2022.

Installer just hangs on Removing Previous Windows Service. (See logs below)

I have also tried 0.1.2 same issue, I also tried a restart.
Installation is broken I can neither access the website or launch the Readarr applications.
Uninstall fails but thats to be expected as it didn’t install correctly.

### Environment

```markdown
- OS: Windows Server 2022
- Readarr: 0.1.3
- Docker Install: No - Baremetal
- Using Reverse Proxy: No
- Browser: Chrome
- Database: None
```

### What branch are you running?

Develop

### Trace Logs?

2023-02-24 22:27:21.4|Info|Bootstrap|Starting Readarr - C:\ProgramData\Readarr\bin\Readarr.Console.dll - Version 0.1.3.1584
2023-02-24 22:27:22.7|Fatal|ConsoleApp|EPIC FAIL!

[v0.1.3.1584] DryIoc.ContainerException: code: Error.UnableToResolveUnknownService;
message: Unable to resolve Microsoft.Extensions.Options.IOptions<NzbDrone.Core.Datastore.PostgresOptions> as parameter "postgresOptions" (IsSingletonOrDependencyOfSingleton)
  in Singleton NzbDrone.Core.Configuration.ConfigFileProvider: NzbDrone.Core.Configuration.IConfigFileProvider as parameter "configFileProvider" FactoryId=1007 (IsSingletonOrDependencyOfSingleton)
  in Singleton NzbDrone.Host.AccessControl.FirewallAdapter: NzbDrone.Host.AccessControl.IFirewallAdapter as parameter "firewallAdapter" FactoryId=372 (IsSingletonOrDependencyOfSingleton)
  in Singleton NzbDrone.Host.AccessControl.RemoteAccessAdapter: NzbDrone.Host.AccessControl.IRemoteAccessAdapter as parameter "remoteAccessAdapter" FactoryId=373 (IsSingletonOrDependencyOfSingleton)
  in resolution root NzbDrone.Host.UtilityModeRouter FactoryId=1210
  from container without scope
 with Rules with {TrackingDisposableTransients, AutoConcreteTypeResolution, SelectLastRegisteredFactory} and without {ThrowOnRegisteringDisposableTransient, VariantGenericTypesInResolvedCollection}
 with DefaultReuse=Singleton {Lifespan=1000}
 with FactorySelector=SelectLastRegisteredFactory
 with Made={FactoryMethod=ConstructorWithResolvableArguments}
Where no service registrations found
  and no dynamic registrations found in 0 of Rules.DynamicServiceProviders
  and nothing found in 1 of Rules.UnknownServiceResolvers
   at DryIoc.Throw.It(Int32 error, Object arg0, Object arg1, Object arg2, Object arg3) in /_/src/DryIoc/Container.cs:line 14444
   at DryIoc.Container.TryThrowUnableToResolve(Request request) in /_/src/DryIoc/Container.cs:line 925
   at DryIoc.Container.DryIoc.IContainer.ResolveFactory(Request request) in /_/src/DryIoc/Container.cs:line 905
   at DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request) in /_/src/DryIoc/Container.cs:line 11851
   at DryIoc.Factory.GetExpressionOrDefault(Request request) in /_/src/DryIoc/Container.cs:line 10841
   at DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request) in /_/src/DryIoc/Container.cs:line 11851
   at DryIoc.Factory.GetExpressionOrDefault(Request request) in /_/src/DryIoc/Container.cs:line 10841
   at DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request) in /_/src/DryIoc/Container.cs:line 11851
   at DryIoc.Factory.GetExpressionOrDefault(Request request) in /_/src/DryIoc/Container.cs:line 10841
   at DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request) in /_/src/DryIoc/Container.cs:line 11851
   at DryIoc.Factory.GetExpressionOrDefault(Request request) in /_/src/DryIoc/Container.cs:line 10841
   at DryIoc.Container.ResolveAndCache(Int32 serviceTypeHash, Type serviceType, IfUnresolved ifUnresolved) in /_/src/DryIoc/Container.cs:line 420
   at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, IfUnresolved ifUnresolved) in /_/src/DryIoc/Container.cs:line 386
   at DryIoc.Resolver.Resolve[TService](IResolver resolver, IfUnresolved ifUnresolved) in /_/src/DryIoc/Container.cs:line 8433
   at NzbDrone.Host.Bootstrap.Start(String[] args, Action`1 trayCallback) in D:\a\1\s\src\NzbDrone.Host\Bootstrap.cs:line 86
   at NzbDrone.Console.ConsoleApp.Main(String[] args) in D:\a\1\s\src\NzbDrone.Console\ConsoleApp.cs:line 43

**Comment by Qstick** [comment]
Thanks for creating a GHI issue for this.
