### ISSUE TITLE
Adding new Author/Book: "BookInfoProxy: Error mapping search results"

### ISSUE THREAD

**Issue by dougclarknc** [Readarr/Readarr#2227]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Actual: "Could not find any results" in UI, Many errors in logs

### Expected Behavior

Given: Logged in as user will all privileges
When: I search for new content using any prefix (isbn, author) or plain search
Expected: Valid search info returns entries and data is populated in results list

### Steps To Reproduce

1. Login with valid privileged user
2. Land on home page
3. Enter search term in searchbox
4. Select from search suggestions Add new item: search "..."

### Environment

```markdown
- OS: Ubuntu 20.04.5
- Readarr: 0.1.4.1596
- Docker Install: 0.1.4.1596-ls35 by linuxserver.io 
- Using Reverse Proxy: Traefik
- Browser: All
- Database: Sqlite 3.40.1
```

### What branch are you running?

Develop

### Trace Logs?

[Warn] BookInfoProxy: Error mapping search results 

[v0.1.4.1596] System.NullReferenceException: Object reference not set to an instance of an object.

   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.MapBulkBook(BulkBookResource resource) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\BookInfo\BookInfoProxy.cs:line 508

   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.MapSearchResult(List`1 ids) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\BookInfo\BookInfoProxy.cs:line 491

   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.Search(String query, Boolean getAllEditions) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\BookInfo\BookInfoProxy.cs:line 295

[Warn] BookInfoProxy: Error searching by book id 

[v0.1.4.1596] NzbDrone.Core.MetadataSource.BookInfo.BookInfoException: Unexpected response from https://api.bookinfo.club/v1/book/78671

   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.GetEditionInfo(Int32 id, Boolean getAllEditions) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\BookInfo\BookInfoProxy.cs:line 412

   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.SearchByGoodreadsBookId(Int32 id, Boolean getAllEditions) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\BookInfo\BookInfoProxy.cs:line 356

**Comment by PearsonFlyer** [comment]
It appears that, at the moment, the Readarr metadata server is down. This is not a bug, just an outage.
