### ISSUE TITLE
Couldn't import book - Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by Nammurg** [Readarr/Readarr#2374]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Downloaded books fail to import automatically.

### Expected Behavior

Downloaded books to import automatically.

### Steps To Reproduce

It is an intermittent issue and usually happens when downloading and importing books from a large list (~100 books or more).
Issue seems to be fixed after a restart of the Readarr container.

In [this](https://www.reddit.com/r/Readarr/comments/v1kw5x/unable_to_import_book_index_outside_the_bounds_of/) conversation, it is mentioned that there might be an issue with a cache file, haven't tested it myself yet.

### Environment

```markdown
- OS: Unraid 6.11.5
- Readarr: 0.1.4.1596
- Docker Install: 20.10.21
- Using Reverse Proxy: No
- Browser: Microsoft Edge Version 112.0.1722.48 (Official build) (64-bit)
- Database: Sqlite 3.38.5
```

### What branch are you running?

Master

### Trace Logs?
```
Couldn't import book /data/torrents/books/Lightning in a Mirror by Jayne Ann Krentz EPUB/Lightning in a Mirror by Jayne Ann Krentz.epub: Index was outside the bounds of the array.

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Net.CredentialCache.Add(Uri uriPrefix, String authType, NetworkCredential cred)
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in D:\a\1\s\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 75
   at NzbDrone.Common.Http.HttpClient.ExecuteRequest(HttpRequest request, CookieContainer cookieContainer) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 124
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 59
   at NzbDrone.Common.Http.HttpClient.Post[T](HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 310
   at NzbDrone.Core.Books.Calibre.CalibreProxy.AddBook(BookFile book, CalibreSettings settings) in D:\a\1\s\src\NzbDrone.Core\Books\Calibre\CalibreProxy.cs:line 156
   at NzbDrone.Core.Books.Calibre.CalibreProxy.AddAndConvert(BookFile file, CalibreSettings settings) in D:\a\1\s\src\NzbDrone.Core\Books\Calibre\CalibreProxy.cs:line 84
   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeBookFile(BookFile bookFile, LocalBook localBook, Boolean copyOnly) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\UpgradeMediaFileService.cs:line 112
   at NzbDrone.Core.MediaFiles.BookImport.ImportApprovedBooks.Import(List`1 decisions, Boolean replaceExisting, DownloadClientItem downloadClientItem, ImportMode importMode) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\BookImport\ImportApprovedBooks.cs:line 215

```

**Comment by Nammurg** [comment]
It just happened again with another big operation of searching and adding downloaded files.
The cache.db file has reached 5.53 GB (5,947,027,456 bytes) which did not allow anything else to be processed.
renamed the file and restarted readarr which resolved this issue again, however, any downloaded files which were not imported, are now marked in yellow as "Import failed" and need to manually import them as the automated import just skips them.


```
Couldn't refresh info for [20322940][Sara Nisha Adams]: SQL logic error
no such table: HttpResponse

code = Error (1), message = System.Data.SQLite.SQLiteException (0x800007BF): SQL logic error
no such table: HttpResponse
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in /_/Dapper/SqlMapper.cs:line 1075
   at Dapper.SqlMapper.QueryImpl[T](IDbConnection cnn, CommandDefinition command, Type effectiveType)+MoveNext() in /_/Dapper/SqlMapper.cs:line 1094
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 734
   at NzbDrone.Core.Datastore.SqlMapperExtensions.Query[T](IDatabase db, String sql, Object param) in D:\a\1\s\src\NzbDrone.Core\Datastore\Extensions\SqlMapperExtensions.cs:line 17
   at NzbDrone.Core.Datastore.BasicRepository`1.Query(SqlBuilder builder) in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 73
   at NzbDrone.Core.Http.CachedHttpResponseRepository.FindByUrl(String url) in D:\a\1\s\src\NzbDrone.Core\Http\CachedHttpResponseRepository.cs:line 22
   at NzbDrone.Core.Http.CachedHttpResponseService.Get(HttpRequest request, Boolean useCache, TimeSpan ttl) in D:\a\1\s\src\NzbDrone.Core\Http\CachedHttpResponseService.cs:line 55
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.PollAuthorUncached(String foreignAuthorId) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\BookInfo\BookInfoProxy.cs:line 608
   at LazyCache.CachingService.<>c__DisplayClass22_1`1.<GetOrAdd>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at LazyCache.CachingService.GetValueFromLazy[T](Object item, Boolean& valueHasChangedType)
   at LazyCache.CachingService.GetOrAdd[T](String key, Func`2 addItemFactory, MemoryCacheEntryOptions policy)
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.GetAuthorInfo(String foreignAuthorId, Boolean useCache) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\BookInfo\BookInfoProxy.cs:line 105
   at NzbDrone.Core.Books.RefreshAuthorService.GetSkyhookData(String foreignId) in D:\a\1\s\src\NzbDrone.Core\Books\Services\RefreshAuthorService.cs:line 99
   at NzbDrone.Core.Books.RefreshAuthorService.RefreshSelectedAuthors(List`1 authorIds, Boolean isNew, CommandTrigger trigger) in D:\a\1\s\src\NzbDrone.Core\Books\Services\RefreshAuthorService.cs:line 350
```

**Comment by BrendanKOz** [comment]
I am seeing a similar error, but with a different error message.

```
[Info] DiskScanService: Scanning /mnt/tank/media/e-books/Calibre/
[Info] DiskScanService: Getting book list from calibre for /mnt/tank/media/e-books/Calibre/
[Error] CommandExecutor: Error occurred while executing task RescanFolders
[v0.3.3.2171] System.IndexOutOfRangeException: Index was outside the bounds of the array.
    at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
    at System.Net.CredentialCache.Add(Uri uriPrefix, String authType, NetworkCredential cred)
    at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in ./Readarr.Common/Http/Dispatchers/ManagedHttpDispatcher.cs:line 71
    at NzbDrone.Common.Http.HttpClient.ExecuteRequest(HttpRequest request, CookieContainer cookieContainer) in ./Readarr.Common/Http/HttpClient.cs:line 141
    at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in ./Readarr.Common/Http/HttpClient.cs:line 59
    at NzbDrone.Common.Http.HttpClient.Get[T](HttpRequest request) in ./Readarr.Common/Http/HttpClient.cs:line 307
    at NzbDrone.Core.Books.Calibre.CalibreProxy.GetAllBookFilePaths(CalibreSettings settings) in ./Readarr.Core/Books/Calibre/CalibreProxy.cs:line 463
    at NzbDrone.Core.MediaFiles.DiskScanService.GetBookFiles(String path, Boolean allDirectories) in ./Readarr.Core/MediaFiles/DiskScanService.cs:line 257
    at NzbDrone.Core.MediaFiles.DiskScanService.Scan(List`1 folders, FilterFilesType filter, Boolean addNewAuthors, List`1 authorIds) in ./Readarr.Core/MediaFiles/DiskScanService.cs:line 137
    at NzbDrone.Core.MediaFiles.DiskScanService.Execute(RescanFoldersCommand message) in ./Readarr.Core/MediaFiles/DiskScanService.cs:line 310
    at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in ./Readarr.Core/Messaging/Commands/CommandExecutor.cs:line 111
    at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
    at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in ./Readarr.Core/Messaging/Commands/CommandExecutor.cs:line 42
```
