### ISSUE TITLE
Unable to confirm deletion popup for Remote Path Mapping and Root Folders

### ISSUE THREAD

**Issue by jstraten** [Readarr/Readarr#2587]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When I attempt to delete a Remote Path Mapping or Root Folder, Readarr gives me a confirmation popup. The content of the popup is also not showing the correct information, but, most importantly, it only accepts Cancel and not Delete.

### Expected Behavior

The popup should show me correct information and allow to confirm the deletion.

### Environment

```markdown
- OS: Ubuntu 22.04
- Readarr: 0.1.8.1889
- Docker Install: N/A
- Using Reverse Proxy: No
- Browser: Microsoft Edge and Firefox
- Database: Sqlite 3.37.2
```

### What branch are you running?

Develop

### Trace Logs?

2023-06-12 18:52:06.8|Error|TaskExtensions|Task Error

[v0.1.8.1889] code = ReadOnly (8), message = System.Data.SQLite.SQLiteException (0x800017FF): attempt to write a readonly database
attempt to write a readonly database
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in /_/Dapper/SqlMapper.cs:line 1075
   at Dapper.SqlMapper.QueryMultipleImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 1058
   at NzbDrone.Core.Datastore.BasicRepository`1.Insert(IDbConnection connection, IDbTransaction transaction, TModel model) in ./Readarr.Core/Datastore/BasicRepository.cs:line 199
   at NzbDrone.Core.Datastore.BasicRepository`1.Insert(TModel model) in ./Readarr.Core/Datastore/BasicRepository.cs:line 152
   at NzbDrone.Core.Messaging.Commands.CommandQueueManager.Push[TCommand](TCommand command, CommandPriority priority, CommandTrigger trigger) in ./Readarr.Core/Messaging/Commands/CommandQueueManager.cs:line 137
   at NzbDrone.Core.Messaging.Commands.CommandQueueManager.Push(String commandName, Nullable`1 lastExecutionTime, Nullable`1 lastStartTime, CommandPriority priority, CommandTrigger trigger) in ./Readarr.Core/Messaging/Commands/CommandQueueManager.cs:line 141
   at NzbDrone.Core.Jobs.Scheduler.ExecuteCommands() in ./Readarr.Core/Jobs/Scheduler.cs:line 42
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
SQL: 
==== Begin Query Trace ====

QUERY TEXT:
INSERT INTO Commands ("Name", "Body", "Priority", "Status", "QueuedAt", "StartedAt", "EndedAt", "Exception", "Trigger") VALUES (@Name, @Body, @Priority, @Status, @QueuedAt, @StartedAt, @EndedAt, @Exception, @Trigger); SELECT last_insert_rowid() id

PARAMETERS:
Name = ["\"MessagingCleanup\""]
Body = [{
  "sendUpdatesToClient": false,
  "updateScheduledTask": true,
  "completionMessage": "Completed",
  "requiresDiskAccess": false,
  "isExclusive": false,
  "isTypeExclusive": false,
  "isLongRunning": false,
  "name": "MessagingCleanup",
  "lastExecutionTime": "2023-06-11T16:56:17.328549Z",
  "lastStartTime": "2023-06-11T16:56:17.3236154Z",
  "trigger": "scheduled",
  "suppressMessages": false
}]
Priority = ["low"]
Status = ["queued"]
QueuedAt = ["2023-06-12T18:52:06.8032709Z"]
StartedAt = [null]
EndedAt = [null]
Exception = [null]
Trigger = ["scheduled"]
Message = [null]
Id = [0]

==== End Query Trace ====

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have followed the steps in the wiki link above and provided the required trace logs that are relevant and show this issue.

**Comment by mynameisbogdan** [comment]
```
System.Data.SQLite.SQLiteException (0x800017FF): attempt to write a readonly database
attempt to write a readonly database
```

You have bigger issues than the modal.
