### ISSUE TITLE
Unable to parse Agatha Christie

### ISSUE THREAD

**Issue by english06** [Readarr/Readarr#2641]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Adding Agatha Christie either manually or with import from Goodreads causes a parsing error. Attempting to add a book manually causes an error that I have also attached with the trace log. I have attempted to use both my regular metadata profile as well as a zero restriction profile. Both with same result.

### Expected Behavior

Correctly added.

### Environment

```markdown
- OS: 16.04
- Readarr: 0.2.2.1931
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: Chrome
- Database: Sqlite 3.41.2
```

### What branch are you running?

Nightly

### Trace Logs?

```
2023-07-08 04:10:12.3|Error|Parser|An error has occurred while trying to parse Agatha Christie [Hercule Poirot 11] The ABC Murders (epub) (epub)

[v0.1.3.1573] System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at NzbDrone.Core.Parser.Parser.ParseBookTitleWithSearchCriteria(String title, Author author, List`1 books) in D:\a\1\s\src\NzbDrone.Core\Parser\Parser.cs:line 417


2023-07-08 04:10:12.3|Error|Parser|An error has occurred while trying to parse Agatha Christie [Hercule Poirot 11] The ABC Murders (epub)

[v0.1.3.1573] System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at NzbDrone.Core.Parser.Parser.ParseBookTitleWithSearchCriteria(String title, Author author, List`1 books) in D:\a\1\s\src\NzbDrone.Core\Parser\Parser.cs:line 417


2023-07-08 04:10:12.3|Error|Parser|An error has occurred while trying to parse Agatha Christie [Hercule Poirot 09] Three Act Tragedy (epub) (epub)

[v0.1.3.1573] System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at NzbDrone.Core.Parser.Parser.ParseBookTitleWithSearchCriteria(String title, Author author, List`1 books) in D:\a\1\s\src\NzbDrone.Core\Parser\Parser.cs:line 417


2023-07-08 04:10:12.3|Error|Parser|An error has occurred while trying to parse Agatha Christie [Hercule Poirot 09] Three Act Tragedy (epub)

[v0.1.3.1573] System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at NzbDrone.Core.Parser.Parser.ParseBookTitleWithSearchCriteria(String title, Author author, List`1 books) in D:\a\1\s\src\NzbDrone.Core\Parser\Parser.cs:line 417


2023-07-08 04:10:12.3|Error|Parser|An error has occurred while trying to parse Agatha Christie [Hercule Poirot 10] Death In The Clouds (epub)

[v0.1.3.1573] System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at NzbDrone.Core.Parser.Parser.ParseBookTitleWithSearchCriteria(String title, Author author, List`1 books) in D:\a\1\s\src\NzbDrone.Core\Parser\Parser.cs:line 417


2023-07-08 04:10:12.3|Error|Parser|An error has occurred while trying to parse Agatha Christie [Hercule Poirot 10] Death In The Clouds (epub) (epub)

[v0.1.3.1573] System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at NzbDrone.Core.Parser.Parser.ParseBookTitleWithSearchCriteria(String title, Author author, List`1 books) in D:\a\1\s\src\NzbDrone.Core\Parser\Parser.cs:line 417


2023-07-08 04:10:12.3|Error|Parser|An error has occurred while trying to parse Agatha Christie [Hercule Poirot 07] Lord Edgware Dies (epub)

[v0.1.3.1573] System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at NzbDrone.Core.Parser.Parser.ParseBookTitleWithSearchCriteria(String title, Author author, List`1 books) in D:\a\1\s\src\NzbDrone.Core\Parser\Parser.cs:line 417


2023-07-08 04:10:12.3|Error|Parser|An error has occurred while trying to parse Agatha Christie [Hercule Poirot 07] Lord Edgware Dies (epub) (epub)

[v0.1.3.1573] System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at NzbDrone.Core.Parser.Parser.ParseBookTitleWithSearchCriteria(String title, Author author, List`1 books) in D:\a\1\s\src\NzbDrone.Core\Parser\Parser.cs:line 417
```
```
2023-07-08 04:35:18.4|Trace|Http|Req: 233 [GET] /api/v1/search?term=hercule%20poirot (from 74.*.*.177 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36)
2023-07-08 04:35:18.4|Debug|Readarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-07-08 04:35:18.4|Trace|CachedHttpResponseService|Returning cached response for [GET] https://www.goodreads.com/book/auto_complete?format=json&q=hercule%20poirot
2023-07-08 04:35:18.4|Trace|ConfigService|Using default config value for 'metadatasource' defaultValue:''
2023-07-08 04:35:18.4|Trace|HttpClient|Req: [POST] https://api.bookinfo.club/v1/book/bulk
2023-07-08 04:35:18.4|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2023-07-08 04:35:19.0|Trace|HttpClient|Res: [POST] https://api.bookinfo.club/v1/book/bulk: 200.OK (25886 bytes) (613 ms)
2023-07-08 04:35:19.0|Trace|Http|Res: 233 [GET] /api/v1/search?term=hercule%20poirot: 200.OK (634 ms)
2023-07-08 04:35:19.0|Debug|Api|[GET] /api/v1/search?term=hercule%20poirot: 200.OK (634 ms)
2023-07-08 04:35:23.1|Trace|Http|Req: 234 [POST] /api/v1/book (from 74.*.*.177 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36)
2023-07-08 04:35:23.1|Debug|Readarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-07-08 04:35:23.1|Debug|AddBookService|Adding book [1073110][The Murder of Roger Ackroyd]
2023-07-08 04:35:23.1|Trace|ConfigService|Using default config value for 'metadatasource' defaultValue:''
2023-07-08 04:35:23.1|Trace|HttpClient|Req: [GET] https://api.bookinfo.club/v1/work/1073110
2023-07-08 04:35:23.1|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2023-07-08 04:35:23.3|Trace|HttpClient|Res: [GET] https://api.bookinfo.club/v1/work/1073110: 302.Redirect (0 bytes) (168 ms)
2023-07-08 04:35:23.3|Debug|BookInfoProxy|Clearing cache for 123715 due to Expired
2023-07-08 04:35:23.3|Trace|ConfigService|Using default config value for 'metadatasource' defaultValue:''
2023-07-08 04:35:23.3|Trace|CachedHttpResponseService|Returning cached response for [GET] https://api.bookinfo.club/v1/author/123715
2023-07-08 04:35:23.3|Error|AddBookService|Book with Foreign Id 1073110 was not found, it may have been removed from Goodreads.
2023-07-08 04:35:23.3|Trace|ReadarrErrorPipeline|Handling Exception
2023-07-08 04:35:23.3|Warn|ReadarrErrorPipeline|Invalid request Validation failed: 
 -- GoodreadsId: A book with this ID was not found
2023-07-08 04:35:23.3|Trace|Http|Res: 234 [POST] /api/v1/book: 400.BadRequest (217 ms)
2023-07-08 04:35:23.3|Debug|Api|[POST] /api/v1/book: 400.BadRequest (217 ms)
```

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by fagenorn** [comment]
Having the same issue with Stephen King:

```
2023-07-09 18:32:18.8|Error|Parser|An error has occurred while trying to parse Needful Things - Stephen King [Unabridged]

[v0.2.0.1908] System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at NzbDrone.Core.Parser.Parser.ParseBookTitleWithSearchCriteria(String title, Author author, List`1 books) in ./Readarr.Core/Parser/Parser.cs:line 418


2023-07-09 18:32:18.8|Error|Parser|An error has occurred while trying to parse Stephen King- Liseys historie-Norsk Lydbok

[v0.2.0.1908] System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at NzbDrone.Core.Parser.Parser.ParseBookTitleWithSearchCriteria(String title, Author author, List`1 books) in ./Readarr.Core/Parser/Parser.cs:line 418


2023-07-09 18:32:18.8|Error|Parser|An error has occurred while trying to parse STEPHEN KING`S N # 04 ( of 4 )

[v0.2.0.1908] System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at NzbDrone.Core.Parser.Parser.ParseBookTitleWithSearchCriteria(String title, Author author, List`1 books) in ./Readarr.Core/Parser/Parser.cs:line 418


2023-07-09 18:32:18.8|Error|Parser|An error has occurred while trying to parse Stephen King - Mobiel (NLT-Release)

[v0.2.0.1908] System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at NzbDrone.Core.Parser.Parser.ParseBookTitleWithSearchCriteria(String title, Author author, List`1 books) in ./Readarr.Core/Parser/Parser.cs:line 418


2023-07-09 18:32:18.8|Error|Parser|An error has occurred while trying to parse Stephen King - De Duistere Kant (E-Book) NLT-Release

[v0.2.0.1908] System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at NzbDrone.Core.Parser.Parser.ParseBookTitleWithSearchCriteria(String title, Author author, List`1 books) in ./Readarr.Core/Parser/Parser.cs:line 418


2023-07-09 18:32:18.9|Error|Parser|An error has occurred while trying to parse Stephen King - Eenmalige Zonde (2011) E-Book NLT-Release

[v0.2.0.1908] System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at NzbDrone.Core.Parser.Parser.ParseBookTitleWithSearchCriteria(String title, Author author, List`1 books) in ./Readarr.Core/Parser/Parser.cs:line 418
```

**Comment by brucekinsey** [comment]
Came to find this, I'm glad I'm not the only one having issues. Seems to be the same as #2656

Looks like bookclub.info isn't returning/cache-ing items currently. https://api.bookinfo.club/v1/author/3389 returns no works

**Comment by bakerboy448** [comment]
Consolidating into general #2656
