### ISSUE TITLE
GoodReads started to fail to import

### ISSUE THREAD

**Issue by JakeShirley** [Readarr/Readarr#2900]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

A pre-existing GoodReads list that I occasionally update stopped importing.  At closer look it seems like perhaps some of the books I added started causing issues.

NOTE: I run two instances of Readarr, one for audiobooks and one for ebooks.  The ebook instance is still working fine with this list.  The audiobook instance is erroring.  Perhaps something about my metadata is corrupted? 

When the list is processed and imported I get the following error:

Message: `Error occurred while executing task ImportListSync: Object reference not set to an instance of an object.`

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.MetadataSource.Goodreads.GoodreadsProxy.MapBook(BookResource resource) in ./Readarr.Core/MetadataSource/Goodreads/GoodreadsProxy.cs:line 181
   at NzbDrone.Core.MetadataSource.Goodreads.GoodreadsProxy.GetBookInfo(String foreignEditionId, Boolean useCache) in ./Readarr.Core/MetadataSource/Goodreads/GoodreadsProxy.cs:line 145
   at NzbDrone.Core.ImportLists.ImportListSyncService.MapBookReport(ImportListItemInfo report) in ./Readarr.Core/ImportLists/ImportListSyncService.cs:line 208
   at NzbDrone.Core.ImportLists.ImportListSyncService.ProcessReports(List`1 reports) in ./Readarr.Core/ImportLists/ImportListSyncService.cs:line 114
   at NzbDrone.Core.ImportLists.ImportListSyncService.SyncList(ImportListDefinition definition) in ./Readarr.Core/ImportLists/ImportListSyncService.cs:line 87
   at NzbDrone.Core.ImportLists.ImportListSyncService.Execute(ImportListSyncCommand message) in ./Readarr.Core/ImportLists/ImportListSyncService.cs:line 440
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in ./Readarr.Core/Messaging/Commands/CommandExecutor.cs:line 111
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in ./Readarr.Core/Messaging/Commands/CommandExecutor.cs:line 42
```

### Expected Behavior

The list works properly and imports.

### Steps To Reproduce

1.  Add this bookshelf as an import list (I am not sure this works cross-account):
    - https://www.goodreads.com/review/list/142202572-chelsea?ref=nav_mybooks&shelf=jakeplz
2. Click test and save
3. See failure after refresh

### Environment

```markdown
- OS: Unraid
- Readarr: nightly-1a1f4ab by hotio
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: Firefox
- Database: Sqlite 3.41.2
```

### What branch are you running?

Nightly

### Trace Logs?

[readarr.trace.txt](https://github.com/Readarr/Readarr/files/12515740/readarr.trace.txt)

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by mmatforum** [comment]
I just started TRYING to use Readarr and this is happening on a lot of books. It will only add one Agatha Christie novel and half of my Stephen King books won't add. There are others but those are the worst

**Comment by bakerboy448** [comment]
Believe this is covered under various other issues or was related to the metadata issue in fall

**Comment by matt872000** [comment]
Can you link to the duplicate issue? Or are you saying that it's the metadata's fault and won't be addressing it?

**Comment by bakerboy448** [comment]
start with [Discord](http://readarr.com/discord) for support/questions.

more than likely it's the `Stephen king` issue that's ongoing, or is already fixed
