### ISSUE TITLE
RefreshAuthorService: Couldn't refresh info for [3389][AuthorName]: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Tailslide** [Readarr/Readarr#2961]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Click refresh on author.. new books are not added and the error below shows in events

### Expected Behavior

New books should get added for author

### Steps To Reproduce

Search for author
Click "Refresh and Scan" button at top.
Check events

### Environment

```markdown
- OS: Synology DSM 7.2-64570 Update 1
- Readarr: 0.3.6.2232
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Edge Version 117.0.2045.43 (Official build) (64-bit)
- Database: Sqlite 3.41.2
```

### What branch are you running?

Develop

### Trace Logs?

```
<details><summary>Redacted Logs</summary>
2023-09-29 11:47:03.5|Trace|EventAggregator|ConfigFileSavedEvent <~ ReconfigureLogging
2023-09-29 11:47:03.5|Trace|EventAggregator|ConfigSavedEvent <~ TaskManager
2023-09-29 11:47:08.9|Trace|Http|Req: 401 [GET] /api/v1/rootFolder (from 172.24.0.1 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.43)
2023-09-29 11:47:08.9|Debug|Readarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-09-29 11:47:08.9|Debug|DiskProvider|path: /config/Library/
2023-09-29 11:47:08.9|Trace|Http|Res: 401 [GET] /api/v1/rootFolder: 200.OK (7 ms)
2023-09-29 11:47:08.9|Debug|Api|[GET] /api/v1/rootFolder: 200.OK (7 ms)
2023-09-29 11:47:09.2|Trace|Http|Req: 402 [GET] /api/v1/search?term=AuthorFirstName%20AuthorLastName (from 172.24.0.1 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.43)
2023-09-29 11:47:09.2|Debug|Readarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-09-29 11:47:09.2|Trace|CachedHttpResponseService|Returning cached response for [GET] https://www.goodreads.com/book/auto_complete?format=json&q=AuthorFirstName%20AuthorLastName
2023-09-29 11:47:09.2|Trace|ConfigService|Using default config value for 'metadatasource' defaultValue:''
2023-09-29 11:47:09.2|Trace|HttpClient|Req: [POST] https://api.bookinfo.club/v1/book/bulk: [11588,830502,10614,43615,87591651]
2023-09-29 11:47:09.2|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2023-09-29 11:47:10.3|Trace|HttpClient|Res: HTTP/2.0 [POST] https://api.bookinfo.club/v1/book/bulk: 200.OK (12776 bytes) (1125 ms)
2023-09-29 11:47:10.4|Trace|Http|Res: 402 [GET] /api/v1/search?term=AuthorFirstName%20AuthorLastName: 200.OK (1178 ms)
2023-09-29 11:47:10.4|Debug|Api|[GET] /api/v1/search?term=AuthorFirstName%20AuthorLastName: 200.OK (1178 ms)
2023-09-29 11:47:10.4|Debug|BookInfoProxy|Clearing cache for 3389 due to TokenExpired
2023-09-29 11:47:11.7|Trace|Http|Req: 403 [GET] /api/v1/series?authorId=519 (from 172.24.0.1 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.43)
2023-09-29 11:47:11.7|Trace|Http|Req: 404 [GET] /api/v1/bookFile?authorId=519 (from 172.24.0.1 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.43)
2023-09-29 11:47:11.7|Trace|Http|Req: 405 [GET] /api/v1/queue/details?authorId=519 (from 172.24.0.1 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.43)
2023-09-29 11:47:11.7|Debug|Readarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-09-29 11:47:11.7|Debug|Readarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-09-29 11:47:11.7|Debug|Readarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-09-29 11:47:11.7|Trace|Http|Res: 405 [GET] /api/v1/queue/details?authorId=519: 200.OK (3 ms)
2023-09-29 11:47:11.7|Debug|Api|[GET] /api/v1/queue/details?authorId=519: 200.OK (3 ms)
2023-09-29 11:47:11.7|Trace|Http|Res: 403 [GET] /api/v1/series?authorId=519: 200.OK (25 ms)
2023-09-29 11:47:11.7|Debug|Api|[GET] /api/v1/series?authorId=519: 200.OK (25 ms)
2023-09-29 11:47:11.8|Trace|Http|Res: 404 [GET] /api/v1/bookFile?authorId=519: 200.OK (31 ms)
2023-09-29 11:47:11.8|Debug|Api|[GET] /api/v1/bookFile?authorId=519: 200.OK (31 ms)
2023-09-29 11:47:14.1|Trace|Http|Req: 406 [POST] /api/v1/command (from 172.24.0.1 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.43)
2023-09-29 11:47:14.1|Debug|Readarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-09-29 11:47:14.1|Trace|CommandQueueManager|Publishing RefreshAuthor
2023-09-29 11:47:14.1|Trace|CommandQueueManager|Checking if command is queued or started: RefreshAuthor
2023-09-29 11:47:14.1|Trace|CommandQueueManager|Inserting new command: RefreshAuthor
2023-09-29 11:47:14.2|Trace|CommandExecutor|RefreshAuthorCommand -> RefreshAuthorService
2023-09-29 11:47:14.2|Trace|CommandQueueManager|Marking command as started: RefreshAuthor
2023-09-29 11:47:14.2|Trace|Http|Res: 406 [POST] /api/v1/command: 201.Created (8 ms)
2023-09-29 11:47:14.2|Debug|Api|[POST] /api/v1/command: 201.Created (8 ms)
2023-09-29 11:47:14.2|Trace|EventAggregator|Publishing CommandUpdatedEvent
2023-09-29 11:47:14.2|Trace|EventAggregator|CommandUpdatedEvent -> CommandController
2023-09-29 11:47:14.2|Trace|EventAggregator|CommandUpdatedEvent <- CommandController
2023-09-29 11:47:14.2|Debug|BookInfoProxy|Getting Author details GoodreadsId of 3389
2023-09-29 11:47:14.2|Trace|ConfigService|Using default config value for 'metadatasource' defaultValue:''
2023-09-29 11:47:14.2|Trace|CachedHttpResponseService|Returning cached response for [GET] https://api.bookinfo.club/v1/author/3389
2023-09-29 11:47:14.2|Info|RefreshAuthorService|Updating Info for AuthorFirstName AuthorLastName
2023-09-29 11:47:14.2|Trace|EventAggregator|Publishing CommandUpdatedEvent
2023-09-29 11:47:14.2|Trace|EventAggregator|CommandUpdatedEvent -> CommandController
2023-09-29 11:47:14.2|Trace|EventAggregator|CommandUpdatedEvent <- CommandController
2023-09-29 11:47:14.2|Debug|AuthorMetadataRepository|1 author metadata up to date; Updating 0, Adding 0 author metadata entries.
2023-09-29 11:47:14.2|Trace|RefreshAuthorService|local: 519 remote: 519
2023-09-29 11:47:14.2|Trace|RefreshAuthorService|Updating Author [3389][AuthorFirstName AuthorLastName]
2023-09-29 11:47:14.2|Trace|RefreshAuthorService|updated: False forceUpdateFileTags: False
2023-09-29 11:47:14.4|Trace|MetadataProfileService|Filtering:

2023-09-29 11:47:14.4|Debug|RefreshAuthorService|[3389][AuthorFirstName AuthorLastName] 0 books up to date. Adding 0, Updating 0, Merging 0, Deleting 258.
2023-09-29 11:47:14.4|Info|RefreshBookService|Updating Info for End of Watch
2023-09-29 11:47:14.4|Trace|EventAggregator|Publishing CommandUpdatedEvent
2023-09-29 11:47:14.4|Trace|EventAggregator|CommandUpdatedEvent -> CommandController
2023-09-29 11:47:14.4|Trace|EventAggregator|CommandUpdatedEvent <- CommandController
2023-09-29 11:47:14.4|Trace|ConfigService|Using default config value for 'metadatasource' defaultValue:''
2023-09-29 11:47:14.4|Trace|HttpClient|Req: [GET] https://api.bookinfo.club/v1/work/45313982
2023-09-29 11:47:14.4|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2023-09-29 11:47:14.9|Trace|HttpClient|Res: HTTP/2.0 [GET] https://api.bookinfo.club/v1/work/45313982: 302.Redirect (0 bytes) (470 ms)
2023-09-29 11:47:14.9|Error|RefreshBookService|Could not find book with id 45313982
2023-09-29 11:47:14.9|Error|RefreshAuthorService|Couldn't refresh info for [3389][AuthorFirstName AuthorLastName]

[v0.3.6.2232] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Books.RefreshBookService.GetRemoteData(Book local, List`1 remote, Author data) in ./Readarr.Core/Books/Services/RefreshBookService.cs:line 117
   at NzbDrone.Core.Books.RefreshEntityServiceBase`2.RefreshEntityInfo(TEntity local, List`1 remoteItems, Author remoteData, Boolean forceChildRefresh, Boolean forceUpdateFileTags, Nullable`1 lastUpdate) in ./Readarr.Core/Books/Services/RefreshEntityServiceBase.cs:line 197
   at NzbDrone.Core.Books.RefreshBookService.RefreshBookInfo(List`1 books, List`1 remoteBooks, Author remoteData, Boolean forceBookRefresh, Boolean forceUpdateFileTags, Nullable`1 lastUpdate) in ./Readarr.Core/Books/Services/RefreshBookService.cs:line 341
   at NzbDrone.Core.Books.RefreshAuthorService.RefreshChildren(SortedChildren localChildren, List`1 remoteChildren, Author remoteData, Boolean forceChildRefresh, Boolean forceUpdateFileTags, Nullable`1 lastUpdate) in ./Readarr.Core/Books/Services/RefreshAuthorService.cs:line 285
   at NzbDrone.Core.Books.RefreshEntityServiceBase`2.SortChildren(TEntity entity, List`1 remoteChildren, Author remoteData, Boolean forceChildRefresh, Boolean forceUpdateFileTags, Nullable`1 lastUpdate) in ./Readarr.Core/Books/Services/RefreshEntityServiceBase.cs:line 290
   at NzbDrone.Core.Books.RefreshEntityServiceBase`2.RefreshEntityInfo(TEntity local, List`1 remoteItems, Author remoteData, Boolean forceChildRefresh, Boolean forceUpdateFileTags, Nullable`1 lastUpdate) in ./Readarr.Core/Books/Services/RefreshEntityServiceBase.cs:line 197
   at NzbDrone.Core.Books.RefreshAuthorService.RefreshSelectedAuthors(List`1 authorIds, Boolean isNew, CommandTrigger trigger) in ./Readarr.Core/Books/Services/RefreshAuthorService.cs:line 351
</details>
```

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by mynameisbogdan** [comment]
Being vague in the logs isn't helpful.

**Comment by Tailslide** [comment]
Please disregard it's OK if my information isn't sufficient
