### ISSUE TITLE
Error mapping search results: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by ds8k** [Readarr/Readarr#2971]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Search results aren't returning anthing

### Expected Behavior

Search is able to find authors

### Steps To Reproduce

Attempt to search for any authors

### Environment

```markdown
- OS: TrueNAS SCALE
- Readarr: 0.3.6.2232
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Chrome
- Database: Sqlite 3.41.2
```

### What branch are you running?

Master

### Trace Logs?

```
2023-10-06 05:55:32.5|Warn|BookInfoProxy|Error mapping search results

[v0.3.5.2217] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.MapBulkBook(BulkBookResource resource) in ./Readarr.Core/MetadataSource/BookInfo/BookInfoProxy.cs:line 510
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.MapSearchResult(List`1 ids) in ./Readarr.Core/MetadataSource/BookInfo/BookInfoProxy.cs:line 493
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.Search(String query, Boolean getAllEditions) in ./Readarr.Core/MetadataSource/BookInfo/BookInfoProxy.cs:line 297


2023-10-06 05:55:32.5|Warn|BookInfoProxy|Error mapping search results

[v0.3.5.2217] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.MapBulkBook(BulkBookResource resource) in ./Readarr.Core/MetadataSource/BookInfo/BookInfoProxy.cs:line 510
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.MapSearchResult(List`1 ids) in ./Readarr.Core/MetadataSource/BookInfo/BookInfoProxy.cs:line 493
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.Search(String query, Boolean getAllEditions) in ./Readarr.Core/MetadataSource/BookInfo/BookInfoProxy.cs:line 297
```

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by mynameisbogdan** [comment]
I added a condition to prevent the NullRef, but that doesn't fix the issue at hand.

**Comment by hisabimbola** [comment]
I'm also having the same issue. Search result is empty. Twas working 2 days ago. Can someone reopen the issue

**Comment by bart-kooi** [comment]
Same here, this does seem like a bug not sure why it was closed

**Comment by mynameisbogdan** [comment]
Because it's external, nothing to fix in the app.

**Comment by bart-kooi** [comment]
Do you know what changed externally that is causing this?

**Comment by mynameisbogdan** [comment]
Yes, I do. And it's going to be fixed soon.
