### ISSUE TITLE
Endless Rescan prevents upgrade

### ISSUE THREAD

**Issue by Dude77777** [Readarr/Readarr#3068]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I am currently on version 0.3.1.2096 trying to update to any newer versions including 0.3.10.2287. My main issue are:
1) Readarr takes a very long time to start staying in the tasklist but not showing the UI for like an hour
2) When it does show it has spawned endless Rescan folders tasks
3) I try to delete all but the currently running one, however, that keeps running for more than 24 hours and never completes
4) Often it hogs 10 GB of my 16 GB RAM
5) Very often it shows "Connection Lost"
This means that Readarr never gets to the Application Update task might resolve some of these performance issues.
What should I do? 

![Screenshot 2023-11-14 232808](https://github.com/Readarr/Readarr/assets/83953593/e323de46-067b-47b6-8816-c48a2a441b70)

### Expected Behavior

User can upgrade before any other tasks are spawned

### Steps To Reproduce

1. With the environment as per below
2. Everytime Readarr starts (many times it doesnt)
3. It seems broken, unable to upgrade itself before going in an endless loop

### Environment

```markdown
- OS: Windows 11
- Readarr: 0.3.1.2096
- Docker Install: - 
- Using Reverse Proxy: - 
- Browser: Chrome 119.0.6045.124
- Database: Sqlite 3.36.0
```

### What branch are you running?

Develop

### Trace Logs?

Readarr is very unstable so I struggle to get to the logs 

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
closing; invalid report, logs are not optional and were marked as provided but not provided

as per
> Reports may be closed if the required logs are not provided.

=====
you can always update manually and reinstall over existing

**Comment by Dude77777** [comment]
Hi @bakerboy448 , could you please describe in a few steps how to update manually (develop branch). Im afraid I dont use github etc.

**Comment by Dude77777** [comment]
@bakerboy448 So I went to https://github.com/Readarr/Readarr/releases/tag/v0.3.10.2287 and downloaded [Readarr.develop.0.3.10.2287.windows-core-x64-installer.exe](https://github.com/Readarr/Readarr/releases/download/v0.3.10.2287/Readarr.develop.0.3.10.2287.windows-core-x64-installer.exe). Then I stopped Readarr and installed over the same directory: C:\ProgramData\Readarr. Start is manual, not as a service (it takes too many resources and I only use it ocassionally).
However, when I start it and go to system status it still shows Version 0.3.1.2096 even though I can see that a few files in the install drive have been changed to 15/11/2023. Any ideas?

**Comment by Dude77777** [comment]
This seems to be the update log:
2023-11-15 06:38:30.4|Info|UpdateApp|Starting Readarr Update Client
2023-11-15 06:38:30.8|Info|AppFolderInfo|Data directory is being overridden to [U:\FICTION]
2023-11-15 06:38:30.9|Debug|UpdateApp|Readarr process ID: 77156
2023-11-15 06:38:31.1|Debug|UpdateApp|Using process ID to find installation directory: 77156
2023-11-15 06:38:31.3|Debug|ProcessProvider|Finding process with Id:77156
2023-11-15 06:38:33.1|Debug|ProcessProvider|Found process 77156:Readarr [C:\ProgramData\Readarr\bin\Readarr.exe]
2023-11-15 06:38:33.2|Debug|UpdateApp|Executable location: C:\ProgramData\Readarr\bin\Readarr.exe
2023-11-15 06:38:33.2|Info|InstallUpdateService|Installation Folder: C:\ProgramData\Readarr\bin
2023-11-15 06:38:35.4|Info|InstallUpdateService|Updating Readarr from version 0.3.1.2096 to version 0.3.10.2287
2023-11-15 06:38:35.4|Info|InstallUpdateService|Verifying requirements before update...
2023-11-15 06:38:35.4|Debug|ProcessProvider|Finding process with Id:77156
2023-11-15 06:38:35.5|Debug|ProcessProvider|Found process 77156:Readarr [C:\ProgramData\Readarr\bin\Readarr.exe]
2023-11-15 06:38:41.7|Info|InstallUpdateService|Verifying Update Folder
2023-11-15 06:38:41.7|Fatal|UpdateApp|An error has occurred while applying update package.

[v0.3.10.2287] System.IO.DirectoryNotFoundException: Update folder doesn't exist C:\Users\micha\AppData\Local\Temp\readarr_update\Readarr\
   at NzbDrone.Update.UpdateEngine.InstallUpdateService.Verify(String targetFolder, Int32 processId) in ./Readarr.Update/UpdateEngine/InstallUpdateService.cs:line 82
   at NzbDrone.Update.UpdateEngine.InstallUpdateService.Start(String installationFolder, Int32 processId) in ./Readarr.Update/UpdateEngine/InstallUpdateService.cs:line 91
   at NzbDrone.Update.UpdateApp.Start(String[] args) in ./Readarr.Update/UpdateApp.cs:line 60
   at NzbDrone.Update.UpdateApp.Main(String[] args) in ./Readarr.Update/UpdateApp.cs:line 45
