### ISSUE TITLE
Can't add new - Metadata Provider Health Message also shows

### ISSUE THREAD

**Issue by richbutler1** [Readarr/Readarr#3106]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Status>Health>Message: We are currently experiencing issues with our metadata provider, this will prevent user searches and author refreshes from working. We are working to solve the issue.

Problem: Cannot add new 

Replicate Issue?: Multiple reports of same issue found in reddit - r/selfhosted post: https://www.reddit.com/r/selfhosted/comments/17ulrlg/readarr_issues/

### Expected Behavior

Abilty to search for and add new:
From left navigation: Library > Add New > enter a valid value for author or title, e.g. asimov would return books by that author

### Steps To Reproduce

From left navigation: Library > Add New generates response "Couldn't find any results for 'asimov'

### Environment

```markdown
- OS: Linux
- Readarr: 0.3.10.2287
- Docker Install: Yes, container on unraid using develop branch
- Repo: ghcr.io/hotio/readarr:testing
latest: develop
testing
testing-0.3.10.2287
testing-5daaeab
age: 22days - 11-5-2023
- Using Reverse Proxy:cloudflare tunnel
- Browser: chrome or firefox latest
- Database: Sqlite 3.41.2

Version
0.3.10.2287
Package Version
testing-5daaeab by hotio
.NET Core
Yes (6.0.21)
Docker
Yes
DB Migration
158
Database
Sqlite 3.41.2
AppData directory
/config
Startup directory
/app/bin
Mode
Console
```

### What branch are you running?

Develop

### Trace Logs?
```
2023-11-27 15:39:23.5|Trace|Http|Res: 141 [GET] /api/v1/search?term=asimo: 200.OK (299 ms)
2023-11-27 15:39:23.5|Debug|Api|[GET] /api/v1/search?term=asimo: 200.OK (299 ms)
2023-11-27 15:39:23.6|Trace|Http|Req: 142 [GET] /api/v1/search?term=asimov (from 10.0.1.208 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36)
2023-11-27 15:39:24.7|Debug|Readarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-11-27 15:39:24.7|Trace|CachedHttpResponseService|Returning cached response for [GET] https://www.goodreads.com/book/auto_complete?format=json&q=asimov
2023-11-27 15:39:24.7|Trace|ConfigService|Using default config value for 'metadatasource' defaultValue:''
2023-11-27 15:39:24.7|Trace|HttpClient|Req: [POST] https://api.bookinfo.club/v1/book/bulk: [29579,41804,29581,29580,46654]
2023-11-27 15:39:24.7|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2023-11-27 15:39:24.8|Trace|HttpClient|Res: HTTP/2.0 [POST] https://api.bookinfo.club/v1/book/bulk: 521.521 (15 bytes)
error code: 521 (94 ms)
2023-11-27 15:39:24.8|Warn|BookInfoProxy|Error mapping search results

[v0.3.10.2287] Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: e. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at NzbDrone.Common.Http.HttpResponse`1..ctor(HttpResponse response) in ./Readarr.Common/Http/HttpResponse.cs:line 107
   at NzbDrone.Common.Http.HttpClient.PostAsync[T](HttpRequest request) in ./Readarr.Common/Http/HttpClient.cs:line 371
   at NzbDrone.Common.Http.HttpClient.Post[T](HttpRequest request) in ./Readarr.Common/Http/HttpClient.cs:line 377
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.MapSearchResult(List`1 ids) in ./Readarr.Core/MetadataSource/BookInfo/BookInfoProxy.cs:line 489
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.Search(String query, Boolean getAllEditions) in ./Readarr.Core/MetadataSource/BookInfo/BookInfoProxy.cs:line 297
```
### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by MaddyTP** [comment]
Same issue here.

**Comment by sboucher660** [comment]
Same issue here. been ongoing for a while

**Comment by CandyCurt** [comment]
i have the same issue in two independent instances

**Comment by bakerboy448** [comment]
A health check message indicating the metadata server is having issues is NOT A BUG

https://github.com/Readarr/Readarr/issues/2970#issuecomment-1822031496

**Comment by richbutler1** [comment]
> A health check message indicating the metadata server is having issues is NOT A BUG
> 
> [#2970 (comment)](https://github.com/Readarr/Readarr/issues/2970#issuecomment-1822031496)

Did you look at the tracelog and see the error? A metadata provider inactive should not being throwing an error unless the code/validation logic isn't right. Am I missing something?

**Comment by bakerboy448** [comment]
Yes

# We are currently experiencing issues with our metadata provider, this will prevent user searches and author refreshes from working. We are working to solve the issue.

logs clearly show an author search

```none
2023-11-27 15:39:24.7|Trace|CachedHttpResponseService|Returning cached response for [GET] [goodreads.com/book/auto_complete?format=json&q=asimov](https://www.goodreads.com/book/auto_complete?format=json&q=asimov)
2023-11-27 15:39:24.7|Trace|ConfigService|Using default config value for 'metadatasource' defaultValue:''
2023-11-27 15:39:24.7|Trace|HttpClient|Req: [POST] [api.bookinfo.club/v1/book/bulk](https://api.bookinfo.club/v1/book/bulk): [29579,41804,29581,29580,46654]
2023-11-27 15:39:24.7|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2023-11-27 15:39:24.8|Trace|HttpClient|Res: HTTP/2.0 [POST] [api.bookinfo.club/v1/book/bulk](https://api.bookinfo.club/v1/book/bulk): 521.521 (15 bytes)
error code: 521 (94 ms)
2023-11-27 15:39:24.8|Warn|BookInfoProxy|Error mapping search results
```

**Comment by richbutler1** [comment]
ok, saw the mapping error and exception. I am not a developer. Was trying to help the community. Lighten up a little. Happy Holidays!

**Comment by bakerboy448** [comment]
https://wiki.servarr.com/readarr/system#we-are-currently-experiencing-issues-with-our-metadata-provider-this-will-prevent-user-searches-and-author-refreshes-from-working-we-are-working-to-solve-the-issue
