### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by mattyteds** [Readarr/Readarr#3131]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

While auto importing from SABnzbd, Readarr will fail to import randomly and report a Object reference not set to an instance of an object." error.

### Expected Behavior

File should import.

### Steps To Reproduce

Appears to be random.

### Environment

```markdown
- OS: Ubuntu 18.04
- Readarr: 0.3.13.2331
- Docker Install: yes
- Using Reverse Proxy: yes/SWAG
- Browser: Chrome 120.0.6099.111 (Official Build) (64-bit)
- Database: Sqlite 3.41.2
```

### What branch are you running?

Nightly

### Trace Logs?

2023-12-23 19:02:19.5|Info|ImportApprovedBooks|Importing book 1/1 [18297942][Burn in Hades]
2023-12-23 19:02:19.5|Info|ImportApprovedBooks|Importing 1 files
2023-12-23 19:02:19.5|Warn|ImportApprovedBooks|Couldn't import book /storage/downloads/usenet/complete/books/Michael L Martin Jr - [Life After Death 01] - Burn in Hades (epub)/Michael L Martin Jr - [Life After Death 01] - Burn in Hades (epub).epub

[v0.3.13.2331] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeBookFile(BookFile bookFile, LocalBook localBook, Boolean copyOnly) in ./Readarr.Core/MediaFiles/UpgradeMediaFileService.cs:line 49
   at NzbDrone.Core.MediaFiles.BookImport.ImportApprovedBooks.Import(List`1 decisions, Boolean replaceExisting, DownloadClientItem downloadClientItem, ImportMode importMode) in ./Readarr.Core/MediaFiles/BookImport/ImportApprovedBooks.cs:line 215

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by mattyteds** [comment]
I have trace logs on now, I will try to capture this error when it occurs again.

**Comment by beastyrabbit** [comment]
Hi. 
I got the same Error and i also got Log Files.
[Link to Log](https://notebin.de/?0f1c37d4731aa719#CJJpgP8iovx7EFYb9kznDfy1ctvMk9vNYPcdKURh1uKT)

The Book "Playing Dead" is the Issue. 
Auto import failed. Manuel Import worked.

The Author is `/author/5363529`
She does not have many books to this sould be good for testing.


```2024-04-05 00:41:28.5|Warn|ImportApprovedBooks|Couldn't import book /data/usenet/complete/books/Julia_Heaberlin_-_Playing_Dead_(epub)/Julia Heaberlin - Playing Dead (epub).epub
[v0.3.22.2487] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeBookFile(BookFile bookFile, LocalBook localBook, Boolean copyOnly) in ./Readarr.Core/MediaFiles/UpgradeMediaFileService.cs:line 49
   at NzbDrone.Core.MediaFiles.BookImport.ImportApprovedBooks.Import(List`1 decisions, Boolean replaceExisting, DownloadClientItem downloadClientItem, ImportMode importMode) in ./Readarr.Core/MediaFiles/BookImport/ImportApprovedBooks.cs:line 235```

**Comment by bakerboy448** [comment]
Preserving second commenters logs
https://logs.notifiarr.com/?80f1d9cfc156e4af#6VYLmcuCNaojzbFgbhDC2frBikctKeYRphis7dBHaeKk
