### ISSUE TITLE
BookInfoProxy: Unexpected error getting author info

### ISSUE THREAD

**Issue by bthuree** [Readarr/Readarr#3166]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When starting from scratch (clean readarr), and importing existing calibre library (which fetched all books metadata from goodreads just fine, deleted all that did not work)

the Reading file works 99% ok
```
readarr    | [Info] ImportDecisionMaker: Reading file 8630/8710 
```

Then comes the Identifying book part
And I get a lot of these errors, that just slows readarr down drastically
```
readarr    | [Warn] BookInfoProxy: Unexpected error getting author info
readarr    |
readarr    | [v0.3.14.2348] NzbDrone.Core.MetadataSource.BookInfo.BookInfoException: Failed to get works for 23791379
readarr    |    at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.PollAuthorUncached(String foreignAuthorId) in ./Readarr.Core/MetadataSource/BookInfo/BookInfoProxy.cs:line 652
readarr    |    at LazyCache.CachingService.<>c__DisplayClass22_1`1.<GetOrAdd>b__1()
readarr    |    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
readarr    |    at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
readarr    |    at System.Lazy`1.CreateValue()
readarr    |    at LazyCache.CachingService.GetValueFromLazy[T](Object item, Boolean& valueHasChangedType)
readarr    |    at LazyCache.CachingService.GetOrAdd[T](String key, Func`2 addItemFactory, MemoryCacheEntryOptions policy)
readarr    |    at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.GetAuthorInfo(String foreignAuthorId, Boolean useCache) in ./Readarr.Core/MetadataSource/BookInfo/BookInfoProxy.cs:line 107
```

And just now I saw this error also pop up in my docker-compose window
```
readarr    | [Warn] BookInfoProxy: Error searching for the billion subsidies are all mine: urban fantasy adventure book 8
readarr    |
readarr    | [v0.3.14.2348] NzbDrone.Core.MetadataSource.Goodreads.GoodreadsException: Search for 'the billion subsidies are all mine: urban fantasy adventure book 8' failed. Invalid response received from Goodreads.
readarr    |  ---> System.Net.Http.HttpRequestException: Resource temporarily unavailable (www.goodreads.com:443)
readarr    |  ---> System.Net.Sockets.SocketException (11): Resource temporarily unavailable
readarr    |    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
```

### Expected Behavior

No errors should occur during import of existing books from a calibre library that can fetch metadata for all books from goodreads
Also the time to fetch author info should be fast (either working, or mark for further investigation)

### Steps To Reproduce

Delete readarr environment, and start it up again.
Everything clean
Add library and calibre connection.

### Environment

```markdown
Version
    0.3.14.2348
Package Version
    0.3.14.2348-ls81 by linuxserver.io 
.NET Core
    Yes (6.0.25)
Docker
    Yes
DB Migration
    158
Database
    Sqlite 3.41.2
AppData directory
    /config
Startup directory
    /app/readarr/bin
Mode
    Console
Uptime
```

### What branch are you running?

Develop

### Trace Logs?

```
2024-01-05 16:08:44.6|Debug|Readarr.Http.Authentication.NoAuthenticationHandler|AuthenticationScheme: None was successfully authenticated.
2024-01-05 16:08:44.6|Trace|Http|Res: 432 [GET] /logfile/readarr.trace.txt: 200.OK (2 ms)
2024-01-05 16:08:46.3|Trace|ConfigService|Using default config value for 'metadatasource' defaultValue:''
2024-01-05 16:08:46.3|Trace|HttpClient|Req: [GET] https://api.bookinfo.club/v1/author/43359945
2024-01-05 16:08:46.3|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2024-01-05 16:08:46.3|Trace|HttpClient|Res: HTTP/2.0 [GET] https://api.bookinfo.club/v1/author/43359945: 200.OK (353 bytes) (25 ms)
2024-01-05 16:08:48.3|Trace|ConfigService|Using default config value for 'metadatasource' defaultValue:''
2024-01-05 16:08:48.3|Trace|HttpClient|Req: [GET] https://api.bookinfo.club/v1/author/43359945
2024-01-05 16:08:48.3|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2024-01-05 16:08:48.4|Trace|HttpClient|Res: HTTP/2.0 [GET] https://api.bookinfo.club/v1/author/43359945: 200.OK (353 bytes) (25 ms)
2024-01-05 16:08:50.4|Trace|ConfigService|Using default config value for 'metadatasource' defaultValue:''
2024-01-05 16:08:50.4|Trace|HttpClient|Req: [GET] https://api.bookinfo.club/v1/author/43359945
2024-01-05 16:08:50.4|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2024-01-05 16:08:50.4|Trace|HttpClient|Res: HTTP/2.0 [GET] https://api.bookinfo.club/v1/author/43359945: 200.OK (353 bytes) (29 ms)
2024-01-05 16:08:50.7|Trace|Http|Req: 433 [GET] /logfile/readarr.trace.txt (from 172.20.0.1 Mozilla/5.0 (X11; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0)
2024-01-05 16:08:50.7|Debug|Readarr.Http.Authentication.NoAuthenticationHandler|AuthenticationScheme: None was successfully authenticated.
2024-01-05 16:08:50.7|Trace|Http|Res: 433 [GET] /logfile/readarr.trace.txt: 200.OK (2 ms)
2024-01-05 16:08:52.4|Trace|ConfigService|Using default config value for 'metadatasource' defaultValue:''
2024-01-05 16:08:52.4|Trace|HttpClient|Req: [GET] https://api.bookinfo.club/v1/author/43359945
2024-01-05 16:08:52.4|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2024-01-05 16:08:52.4|Trace|HttpClient|Res: HTTP/2.0 [GET] https://api.bookinfo.club/v1/author/43359945: 200.OK (353 bytes) (25 ms)
2024-01-05 16:08:54.5|Debug|BookInfoProxy|Clearing cache for 43359945 due to Removed
2024-01-05 16:08:54.5|Warn|BookInfoProxy|Unexpected error getting author info

[v0.3.14.2348] NzbDrone.Core.MetadataSource.BookInfo.BookInfoException: Failed to get works for 43359945
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.PollAuthorUncached(String foreignAuthorId) in ./Readarr.Core/MetadataSource/BookInfo/BookInfoProxy.cs:line 652
   at LazyCache.CachingService.<>c__DisplayClass22_1`1.<GetOrAdd>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at LazyCache.CachingService.GetValueFromLazy[T](Object item, Boolean& valueHasChangedType)
   at LazyCache.CachingService.GetOrAdd[T](String key, Func`2 addItemFactory, MemoryCacheEntryOptions policy)
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.GetAuthorInfo(String foreignAuthorId, Boolean useCache) in ./Readarr.Core/MetadataSource/BookInfo/BookInfoProxy.cs:line 107


2024-01-05 16:08:54.5|Trace|ConfigService|Using default config value for 'metadatasource' defaultValue:''
2024-01-05 16:08:54.5|Trace|HttpClient|Req: [GET] https://api.bookinfo.club/v1/work/199994561
2024-01-05 16:08:54.5|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2024-01-05 16:08:54.5|Trace|HttpClient|Res: HTTP/2.0 [GET] https://api.bookinfo.club/v1/work/199994561: 404.NotFound (0 bytes) (28 ms)
2024-01-05 16:08:54.5|Trace|CandidateService|Searching by goodreads id 197406086
2024-01-05 16:08:54.5|Trace|ConfigService|Using default config value for 'metadatasource' defaultValue:''
2024-01-05 16:08:54.5|Trace|HttpClient|Req: [GET] https://api.bookinfo.club/v1/book/197406086
2024-01-05 16:08:54.5|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2024-01-05 16:08:54.5|Trace|Http|Req: 434 [GET] /logfile/readarr.trace.txt (from 172.20.0.1 Mozilla/5.0 (X11; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0)
2024-01-05 16:08:54.5|Debug|Readarr.Http.Authentication.NoAuthenticationHandler|AuthenticationScheme: None was successfully authenticated.
```

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bthuree** [comment]
Adding more complete trace log as attachement
[ReaderTraceLogForeignAuthorId.log](https://github.com/Readarr/Readarr/files/13838231/ReaderTraceLogForeignAuthorId.log)

**Comment by bthuree** [comment]
This is not a support request, this to me is a pure bug, there should never be any unhandled exceptions.
But I wonder if https://github.com/Readarr/Readarr/commit/27e498bb1405936a37eb70cfac9a875a4f3cda48 fixed it.

**Comment by bthuree** [comment]
Also, please don't close it as COMPLETED when it is not completed, but Rejected.

**Comment by bakerboy448** [comment]
This was due to the metadata server being down and problematic

the referenced commit has nothing to do with the bookinfo metadata server
