### ISSUE TITLE
Disable inotify based "Watch Root Folders for file changes" on FreeBSD, causes "name does not resolve" errors.

### ISSUE THREAD

**Issue by dekimsey** [Readarr/Readarr#3326]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

On FreeBSD, the use of the "Watch Root Folders for file changes" will cause DNS resolution in the app to mysteriously fail. This is due to (wave hands) issues in the inotify implementation used by .NET 6.0's FileSystemWatcher on FreeBSD.

This was previously identified in [lidarr/lidarr#1947](https://github.com/Lidarr/Lidarr/issues/1947#issuecomment-832181973).

See also:
 - https://github.com/dotnet/runtime/issues/14537#issuecomment-111975140
 - https://github.com/dotnet/runtime/issues/14716
 

### Expected Behavior

On FreeBSD machines, the "Watch Root Folders for file changes" should be disabled by default (if not altogether, I don't recall if I ever enabled it. I frankly don't recognize it). If left enable-able, I would recommend a warning indicating that it is not advised on FreeBSD machines as it will brick DNS resolution.

### Steps To Reproduce

1. Set-up services
2. Add indexer, download clients, or integrations.
3. Add content? (Unclear)
Once `2024-02-18 20:32:02.2|Info|RootFolderWatchingService|Watching directory /media/my-dir/` appears, DNS will eventually begin to fail. As it appears intermittent on first start, some worker threads may work until they are recyled. Eventually, it will not work at all.

### Environment

```markdown
- OS: FreeBSD 13.2 x64
- Readarr: 0.3.19.2437
- Docker Install:
- Using Reverse Proxy: Yes
- Browser: -
- Database: -
```

### What branch are you running?

Master

### Trace Logs?

https://gist.github.com/dekimsey/95fd1fa5fe1b24c32dc50c40fe33db4f

Discord [discussion](https://discord.com/channels/264387956343570434/1028840624864120872/1208963428144910447) on the issue as well.

An older similar stack-trace as well: 
```
[v0.3.11.2319] System.Net.Http.HttpRequestException: Name does not resolve (readarr.servarr.com:443)
 ---> System.Net.Sockets.SocketException (0xFFFDFFFF): Name does not resolve
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.attemptConnection(AddressFamily addressFamily, SocketsHttpConnectionContext context, CancellationToken cancellationToken) in ./Readarr.Common/Http/Dispatchers/ManagedHttpDispatcher.cs:line 305
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.onConnect(SocketsHttpConnectionContext context, CancellationToken cancellationToken) in ./Readarr.Common/Http/Dispatchers/ManagedHttpDispatcher.cs:line 281
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp2ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponseAsync(HttpRequest request, CookieContainer cookies) in ./Readarr.Common/Http/Dispatchers/ManagedHttpDispatcher.cs:line 106
   at NzbDrone.Common.Http.HttpClient.ExecuteRequestAsync(HttpRequest request, CookieContainer cookieContainer) in ./Readarr.Common/Http/HttpClient.cs:line 157
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in ./Readarr.Common/Http/HttpClient.cs:line 70
   at NzbDrone.Common.Http.HttpClient.GetAsync[T](HttpRequest request) in ./Readarr.Common/Http/HttpClient.cs:line 336
   at NzbDrone.Common.Http.HttpClient.Get[T](HttpRequest request) in ./Readarr.Common/Http/HttpClient.cs:line 341
   at NzbDrone.Core.Update.UpdatePackageProvider.GetLatestUpdate(String branch, Version currentVersion) in ./Readarr.Core/Update/UpdatePackageProvider.cs:line 53
   at NzbDrone.Core.Update.CheckUpdateService.AvailableUpdate() in ./Readarr.Core/Update/UpdateCheckService.cs:line 25
   at NzbDrone.Core.HealthCheck.Checks.UpdateCheck.Check() in ./Readarr.Core/HealthCheck/Checks/UpdateCheck.cs:line 71
   at NzbDrone.Core.HealthCheck.HealthCheckService.PerformHealthCheck(IProvideHealthCheck[] healthChecks, IEvent message, Boolean performServerChecks) in ./Readarr.Core/HealthCheck/HealthCheckService.cs:line 92
   at NzbDrone.Core.HealthCheck.HealthCheckService.HandleAsync(IEvent message) in ./Readarr.Core/HealthCheck/HealthCheckService.cs:line 175
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
```

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
In the web interface go Settings -> Media Management, scroll down to the File Management section and uncheck the box for "Watch Root Folders for file changes".

_Originally posted by @Spunky17 in https://github.com/Lidarr/Lidarr/issues/1947#issuecomment-833491360_
            
            Xref
