### ISSUE TITLE
BookInfoProxy and CandidateService Errors

### ISSUE THREAD

**Issue by manuelkamp** [Readarr/Readarr#3484]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Want to add my Book collection. It reads my books, but cannot import them.

```
System.Net.WebException: Http request timed out
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponseAsync(HttpRequest request, CookieContainer cookies) in ./Readarr.Common/Http/Dispatchers/ManagedHttpDispatcher.cs:line 145
   at NzbDrone.Common.Http.HttpClient.ExecuteRequestAsync(HttpRequest request, CookieContainer cookieContainer) in ./Readarr.Common/Http/HttpClient.cs:line 157
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in ./Readarr.Common/Http/HttpClient.cs:line 70
   at NzbDrone.Common.Http.HttpClient.Get(HttpRequest request) in ./Readarr.Common/Http/HttpClient.cs:line 327
   at NzbDrone.Core.Http.CachedHttpResponseService.Get(HttpRequest request, Boolean useCache, TimeSpan ttl) in ./Readarr.Core/Http/CachedHttpResponseService.cs:line 40
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.PollAuthorUncached(String foreignAuthorId) in ./Readarr.Core/MetadataSource/BookInfo/BookInfoProxy.cs:line 614
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.<>c__DisplayClass30_0.<PollAuthor>b__0() in ./Readarr.Core/MetadataSource/BookInfo/BookInfoProxy.cs:line 588
   at LazyCache.AppCacheExtensions.<>c__DisplayClass7_0`1.<GetOrAdd>b__0(ICacheEntry _)
   at LazyCache.CachingService.<>c__DisplayClass22_1`1.<GetOrAdd>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at LazyCache.CachingService.GetValueFromLazy[T](Object item, Boolean& valueHasChangedType)
   at LazyCache.CachingService.GetOrAdd[T](String key, Func`2 addItemFactory, MemoryCacheEntryOptions policy)
   at LazyCache.AppCacheExtensions.GetOrAdd[T](IAppCache cache, String key, Func`1 addItemFactory, MemoryCacheEntryOptions policy)
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.PollAuthor(String foreignAuthorId) in ./Readarr.Core/MetadataSource/BookInfo/BookInfoProxy.cs:line 587
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.GetAuthorInfo(String foreignAuthorId, Boolean useCache) in ./Readarr.Core/MetadataSource/BookInfo/BookInfoProxy.cs:line 99
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.SearchByGoodreadsAuthorId(Int32 id) in ./Readarr.Core/MetadataSource/BookInfo/BookInfoProxy.cs:line 313
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.Search(String query, Boolean getAllEditions) in ./Readarr.Core/MetadataSource/BookInfo/BookInfoProxy.cs:line 268
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.SearchForNewBook(String title, String author, Boolean getAllEditions) in ./Readarr.Core/MetadataSource/BookInfo/BookInfoProxy.cs:line 216
```

```
NzbDrone.Core.MetadataSource.Goodreads.GoodreadsException: Search for 'Stephanie Fuchs' failed. Invalid response received from Goodreads.
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.SearchForNewBook(String title, String author, Boolean getAllEditions) in ./Readarr.Core/MetadataSource/BookInfo/BookInfoProxy.cs:line 226
   at NzbDrone.Core.MediaFiles.BookImport.Identification.CandidateService.GetRemoteCandidates(LocalEdition localEdition, IdentificationOverrides idOverrides)+MoveNext() in ./Readarr.Core/MediaFiles/BookImport/Identification/CandidateService.cs:line 355
```

### Expected Behavior

Readarr is able to import my books.

### Steps To Reproduce

Add new folder to Books and wait automatic search for books.

### Environment

```markdown
- OS: Ubuntu 22.04
- Readarr: 0.3.26.2526
- Docker Install: no
- Using Reverse Proxy: no
- Browser: not relevant
- Database: Sqlite 3.37.2
```

### What branch are you running?

Master

### Trace Logs?

https://pastebin.kmpr.at//paste.php?id=8b1fcf61-1215-11ef-8952-3a303f3fd287

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
Network timeouts are generally not a bug
