### ISSUE TITLE
[Add New] Searching is failing due to BookInfoProxy being down

### ISSUE THREAD

**Issue by labithiotis** [Readarr/Readarr#3485]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

On Add New page the search is yielding no results, the logs have errors about BookInfoProxy and Unexpected character encountered while parsing value.

Seems like https://bookinfo.club/ is down?

### Expected Behavior

Searching for an author or book name should return results

### Steps To Reproduce

1. Click Add New
2. Search for Author
3. Observed no results returned

### Environment

```markdown
- OS: Mac M1 / Docker
- Readarr: 0.3.26.2526
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Brave
- Database: Sqlite 3.44.2
```

### What branch are you running?

Develop

### Trace Logs?
```logs
2024-05-15 16:10:08 [Warn] BookInfoProxy: Error mapping search results 
2024-05-15 16:10:08 
2024-05-15 16:10:08 [v0.3.26.2526] Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: e. Path '', line 0, position 0.
2024-05-15 16:10:08    at Newtonsoft.Json.JsonTextReader.ParseValue()
2024-05-15 16:10:08    at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
2024-05-15 16:10:08    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
2024-05-15 16:10:08    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
2024-05-15 16:10:08    at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
2024-05-15 16:10:08    at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
2024-05-15 16:10:08    at NzbDrone.Common.Serializer.Json.Deserialize[T](String json) in ./Readarr.Common/Serializer/Newtonsoft.Json/Json.cs:line 41
2024-05-15 16:10:08    at NzbDrone.Common.Http.HttpResponse`1..ctor(HttpResponse response) in ./Readarr.Common/Http/HttpResponse.cs:line 107
2024-05-15 16:10:08    at NzbDrone.Common.Http.HttpClient.PostAsync[T](HttpRequest request) in ./Readarr.Common/Http/HttpClient.cs:line 371
2024-05-15 16:10:08    at NzbDrone.Common.Http.HttpClient.Post[T](HttpRequest request) in ./Readarr.Common/Http/HttpClient.cs:line 377
2024-05-15 16:10:08    at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.MapSearchResult(List`1 ids) in ./Readarr.Core/MetadataSource/BookInfo/BookInfoProxy.cs:line 489
2024-05-15 16:10:08    at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.Search(String query, Boolean getAllEditions) in ./Readarr.Core/MetadataSource/BookInfo/BookInfoProxy.cs:line 297
```
### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by arsenicks** [comment]
@bakerboy448 I'm not sure this is a support request, I have the exact same error here since few days. I cannot add new books or author no matter what I try. I always get this error. What made you evaluate  this as a support request more that a bug/problem ? Asking politely, just want to understand :)

bookinfo dns doesn't resolve as far as I can see..
```
$ dig bookinfo.club +short
$ dig bookinfo.club +short @8.8.8.8
$ dig bookinfo.club +short @1.1.1.1
```
Oh, but api.bookinfo.club does resolv.. I guess this is the url used and why you flagged this as support request. But anyway the logs doesn't say it can't contact the api but it got an unexpected char..

I can provide more logs or info if asked/explain how to do it, I'm not sure how to turn debug/verbose on..

```
[Warn] BookInfoProxy: Error mapping search results 
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.Search(String query, Boolean getAllEditions) in ./Readarr.Core/MetadataSource/BookInfo/BookInfoProxy.cs:line 297
[v0.3.26.2526] Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: e. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at NzbDrone.Common.Http.HttpResponse`1..ctor(HttpResponse response) in ./Readarr.Common/Http/HttpResponse.cs:line 107
   at NzbDrone.Common.Http.HttpClient.PostAsync[T](HttpRequest request) in ./Readarr.Common/Http/HttpClient.cs:line 371
   at NzbDrone.Common.Http.HttpClient.Post[T](HttpRequest request) in ./Readarr.Common/Http/HttpClient.cs:line 377
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.MapSearchResult(List`1 ids) in ./Readarr.Core/MetadataSource/BookInfo/BookInfoProxy.cs:line 489
```

**Comment by bakerboy448** [comment]
Because the metadata server having issues - as noted in the pinned discord posts - is not a readarr bug

**Comment by arsenicks** [comment]
Yeah here's the pinned message for others that could pass by.

![image](https://github.com/Readarr/Readarr/assets/22738397/1f1fea76-b977-4efc-a5fa-5e838bd0f5f7)

@bakerboy448 Thanks for the follow up, Maybe we could keep an issue open with the info and you guy's can simply ignore the messages in there ? I don't know, I'm thinking about the additional issues that will be opened, I'm probably not the only one with a clogged discord that won't necessarily look there first especially as the error message doesn't say anything about connecting but sounds more like an error with a weird char..

Anyway thanks for your work guy's we'll stay tuned for an update!
