### ISSUE TITLE
BUG: Error occurred while executing task ManualImport: Connection refused Connection refused

### ISSUE THREAD

**Issue by dan-christensen** [Readarr/Readarr#352]
**Describe the bug**
After a torrent is done, Readarr fails to import it automatically.

**To Reproduce**
1. Add a new book
2. Have it download
3. Manual/Auto import it
4. View the logs

**Expected behavior**
The book should be imported

**Logs**
```
System.Net.WebException: Connection refused Connection refused: 'https://192.168.0.8:8080/cdb/add-book/945340673/False/$dummy.epub'
 ---> System.Net.WebException: Connection refused Connection refused
 ---> System.Net.Http.HttpRequestException: Connection refused
 ---> System.Net.Sockets.SocketException (111): Connection refused
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at System.Net.HttpWebRequest.SendRequest()
   at System.Net.HttpWebRequest.GetResponse()
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in d:\a\1\s\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 146
   --- End of inner exception stack trace ---
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in d:\a\1\s\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 146
   at NzbDrone.Common.Http.HttpClient.ExecuteRequest(HttpRequest request, CookieContainer cookieContainer) in d:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 125
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in d:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 59
   at NzbDrone.Common.Http.HttpClient.Post(HttpRequest request) in d:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 301
   at NzbDrone.Common.Http.HttpClient.Post[T](HttpRequest request) in d:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 307
   at NzbDrone.Core.Books.Calibre.CalibreProxy.AddBook(BookFile book, CalibreSettings settings) in d:\a\1\s\src\NzbDrone.Core\Books\Calibre\CalibreProxy.cs:line 71
   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.CalibreAddAndConvert(BookFile file, CalibreSettings settings) in d:\a\1\s\src\NzbDrone.Core\MediaFiles\UpgradeMediaFileService.cs:line 133
   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeBookFile(BookFile bookFile, LocalBook localBook, Boolean copyOnly) in d:\a\1\s\src\NzbDrone.Core\MediaFiles\UpgradeMediaFileService.cs:line 116
   at NzbDrone.Core.MediaFiles.BookImport.ImportApprovedBooks.Import(List`1 decisions, Boolean replaceExisting, DownloadClientItem downloadClientItem, ImportMode importMode) in d:\a\1\s\src\NzbDrone.Core\MediaFiles\BookImport\ImportApprovedBooks.cs:line 190
   at NzbDrone.Core.MediaFiles.BookImport.Manual.ManualImportService.Execute(ManualImportCommand message) in d:\a\1\s\src\NzbDrone.Core\MediaFiles\BookImport\Manual\ManualImportService.cs:line 325
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in d:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 112
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in d:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 42
```

**System info (please complete the following information):**
 - Readarr Version: 0.1.0.145 unstable docker image
 - Operating System Centos 7

**Additional context**
Running in the docker image

**Comment by ta264** [comment]
looks like calibre is down

**Comment by dan-christensen** [comment]
Yeah that's what I've figured out too. It's not down, just configured wrong. I checked everything but that before posting this, my bad.
