### ISSUE TITLE
Goodreads Owned Books is Defunct (HTTP 404)

### ISSUE THREAD

**Issue by Redirts** [Readarr/Readarr#3707]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

2024-08-30 15:01:47.0|Info|ImportListSyncService|Starting Import List Sync
2024-08-30 15:01:47.9|Warn|HttpClient|HTTP Error - Res: HTTP/1.1 [GET] https://www.goodreads.com/owned_books/user?_nc=1&format=xml&id=181329280&page=1: 404.NotFound (29 bytes)
<error>Page not found</error>
2024-08-30 15:01:47.9|Warn|GoodreadsOwnedBooks|Error fetching bookshelves from Goodreads

[v0.3.32.2587] NzbDrone.Common.Http.HttpException: HTTP request failed: [404:NotFound] [GET] at [https://www.goodreads.com/owned_books/user?_nc=1&format=xml&id=181329280&page=1]
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in ./Readarr.Common/Http/HttpClient.cs:line 119
   at NzbDrone.Common.Http.HttpClient.Get(HttpRequest request) in ./Readarr.Common/Http/HttpClient.cs:line 327
   at NzbDrone.Core.ImportLists.Goodreads.GoodreadsImportListBase`1.OAuthGet(HttpRequestBuilder builder) in ./Readarr.Core/ImportLists/Goodreads/GoodreadsImportListBase.cs:line 139
   at NzbDrone.Core.ImportLists.Goodreads.GoodreadsOwnedBooks.GetOwned(Int32 page) in ./Readarr.Core/ImportLists/Goodreads/OwnedBooks/GoodreadsOwnedBooks.cs:line 70
<error>Page not found</error>

2024-08-30 15:01:47.9|Info|ImportListSyncService|No list items to process

### Expected Behavior

I think that the concept of owned books no longer exists in Goodreads so this is probably a deprecated import list type

### Steps To Reproduce

Setup an import list of type "Goodreads Owned Books" and wait for it to attempt the sync

### Environment

```markdown
- OS: Debian 12
- Readarr: 0.3.32.2587
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Chrome 128.0.6613.113
- Database: Sqlite 3.40.1
```

### What branch are you running?

Master

### Trace Logs?

2024-08-30 15:01:47.0|Info|ImportListSyncService|Starting Import List Sync
2024-08-30 15:01:47.9|Warn|HttpClient|HTTP Error - Res: HTTP/1.1 [GET] https://www.goodreads.com/owned_books/user?_nc=1&format=xml&id=181329280&page=1: 404.NotFound (29 bytes)
<error>Page not found</error>
2024-08-30 15:01:47.9|Warn|GoodreadsOwnedBooks|Error fetching bookshelves from Goodreads

[v0.3.32.2587] NzbDrone.Common.Http.HttpException: HTTP request failed: [404:NotFound] [GET] at [https://www.goodreads.com/owned_books/user?_nc=1&format=xml&id=181329280&page=1]
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in ./Readarr.Common/Http/HttpClient.cs:line 119
   at NzbDrone.Common.Http.HttpClient.Get(HttpRequest request) in ./Readarr.Common/Http/HttpClient.cs:line 327
   at NzbDrone.Core.ImportLists.Goodreads.GoodreadsImportListBase`1.OAuthGet(HttpRequestBuilder builder) in ./Readarr.Core/ImportLists/Goodreads/GoodreadsImportListBase.cs:line 139
   at NzbDrone.Core.ImportLists.Goodreads.GoodreadsOwnedBooks.GetOwned(Int32 page) in ./Readarr.Core/ImportLists/Goodreads/OwnedBooks/GoodreadsOwnedBooks.cs:line 70
<error>Page not found</error>

2024-08-30 15:01:47.9|Info|ImportListSyncService|No list items to process

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
- [ ] action: obsolete and disable existing
