### ISSUE TITLE
Goodreads Shelves Import List failing 

### ISSUE THREAD

**Issue by rg9400** [Readarr/Readarr#372]
**Describe the bug**
I can't seem to get books from my to-read shelf to import into Readarr. It finds the 9 books I have in my shelf properly, and these are all normal books I added on GR itself. I keep getting variations of the below error

`Failed to import id: 23840265 - : constraint failed
NOT NULL constraint failed: Editions.Title`

Logs
```
20-8-14 21:44:25.7|Debug|FetchAndParseImportListService|Found 9 from Goodreads Bookshelves
20-8-14 21:44:25.7|Debug|FetchAndParseImportListService|Found 9 reports
20-8-14 21:44:25.7|Info|ImportListSyncService|Processing 9 list items
20-8-14 21:44:25.7|Trace|EventAggregator|Publishing CommandUpdatedEvent
20-8-14 21:44:25.7|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
20-8-14 21:44:25.7|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
20-8-14 21:44:25.7|Trace|ImportListSyncService|Processing list item 1/9
20-8-14 21:44:25.7|Trace|EventAggregator|Publishing CommandUpdatedEvent
20-8-14 21:44:25.7|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
20-8-14 21:44:25.7|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
20-8-14 21:44:25.7|Debug|GoodreadsProxy|Getting Book with GoodreadsId of 50548197
20-8-14 21:44:25.8|Trace|ImportListSyncService|Mapped 50548197 to [75543174][A Deadly Education]
20-8-14 21:44:25.8|Trace|ImportListSyncService|Processing list item 2/9
20-8-14 21:44:25.8|Trace|EventAggregator|Publishing CommandUpdatedEvent
20-8-14 21:44:25.8|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
20-8-14 21:44:25.8|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
20-8-14 21:44:25.8|Debug|GoodreadsProxy|Getting Book with GoodreadsId of 40701777
20-8-14 21:44:25.8|Trace|ImportListSyncService|Mapped 40701777 to [63304678][The Trouble with Peace]
20-8-14 21:44:25.8|Trace|ImportListSyncService|Processing list item 3/9
20-8-14 21:44:25.8|Trace|EventAggregator|Publishing CommandUpdatedEvent
20-8-14 21:44:25.8|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
20-8-14 21:44:25.8|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
20-8-14 21:44:25.8|Debug|GoodreadsProxy|Getting Book with GoodreadsId of 52378515
20-8-14 21:44:25.8|Trace|ImportListSyncService|Mapped 52378515 to [73056535][The Memory of Souls]
20-8-14 21:44:25.8|Trace|ImportListSyncService|Processing list item 4/9
20-8-14 21:44:25.8|Trace|EventAggregator|Publishing CommandUpdatedEvent
20-8-14 21:44:25.8|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
20-8-14 21:44:25.8|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
20-8-14 21:44:25.8|Debug|GoodreadsProxy|Getting Book with GoodreadsId of 11503920
20-8-14 21:44:25.8|Trace|ImportListSyncService|Mapped 11503920 to [16439607][Return of the Thief]
20-8-14 21:44:25.8|Trace|ImportListSyncService|Processing list item 5/9
20-8-14 21:44:25.8|Trace|EventAggregator|Publishing CommandUpdatedEvent
20-8-14 21:44:25.8|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
20-8-14 21:44:25.8|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
20-8-14 21:44:25.8|Debug|GoodreadsProxy|Getting Book with GoodreadsId of 48717744
20-8-14 21:44:25.8|Trace|ImportListSyncService|Mapped 48717744 to [48012708][The Tower of Nero]
20-8-14 21:44:25.8|Trace|ImportListSyncService|Processing list item 6/9
20-8-14 21:44:25.8|Trace|EventAggregator|Publishing CommandUpdatedEvent
20-8-14 21:44:25.8|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
20-8-14 21:44:25.8|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
20-8-14 21:44:25.8|Debug|GoodreadsProxy|Getting Book with GoodreadsId of 40550366
20-8-14 21:44:25.8|Trace|ImportListSyncService|Mapped 40550366 to [62967372][Blood & Honey]
20-8-14 21:44:25.8|Trace|ImportListSyncService|Processing list item 7/9
20-8-14 21:44:25.8|Trace|EventAggregator|Publishing CommandUpdatedEvent
20-8-14 21:44:25.8|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
20-8-14 21:44:25.8|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
20-8-14 21:44:25.8|Debug|GoodreadsProxy|Getting Book with GoodreadsId of 31520883
20-8-14 21:44:25.8|Trace|ImportListSyncService|Mapped 31520883 to [52201861][A ​Sky Beyond the Storm]
20-8-14 21:44:25.8|Trace|ImportListSyncService|Processing list item 8/9
20-8-14 21:44:25.8|Trace|EventAggregator|Publishing CommandUpdatedEvent
20-8-14 21:44:25.8|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
20-8-14 21:44:25.8|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
20-8-14 21:44:25.8|Debug|GoodreadsProxy|Getting Book with GoodreadsId of 50623864
20-8-14 21:44:25.8|Trace|ImportListSyncService|Mapped 50623864 to [46895612][The Invisible Life of Addie LaRue]
20-8-14 21:44:25.8|Trace|ImportListSyncService|Processing list item 9/9
20-8-14 21:44:25.8|Trace|EventAggregator|Publishing CommandUpdatedEvent
20-8-14 21:44:25.8|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
20-8-14 21:44:25.8|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
20-8-14 21:44:25.8|Debug|GoodreadsProxy|Getting Book with GoodreadsId of 17250966
20-8-14 21:44:25.8|Trace|ImportListSyncService|Mapped 17250966 to [23840265][Rhythm of War]
20-8-14 21:44:25.9|Debug|AuthorMetadataRepository|0 author metadata up to date; Updating 0, Adding 0 author metadata entries.
20-8-14 21:44:25.9|Trace|EventAggregator|Publishing AuthorsImportedEvent
20-8-14 21:44:25.9|Trace|EventAggregator|AuthorsImportedEvent -> AuthorAddedHandler
20-8-14 21:44:25.9|Trace|EventAggregator|AuthorsImportedEvent <- AuthorAddedHandler
20-8-14 21:44:25.9|Debug|AddBookService|Adding book [75543174][[NULL]]
20-8-14 21:44:25.9|Error|AddBookService|Failed to import id: 75543174 - 

[v0.1.0.170] code = Constraint (19), message = System.Data.SQLite.SQLiteException (0x800027AF): constraint failed
NOT NULL constraint failed: Editions.Title
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in /_/Dapper/SqlMapper.cs:line 1051
   at Dapper.SqlMapper.QueryMultipleImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 1020
   at Dapper.SqlMapper.QueryMultiple(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 996
   at NzbDrone.Core.Datastore.BasicRepository`1.Insert(IDbConnection connection, IDbTransaction transaction, TModel model) in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 176
   at NzbDrone.Core.Datastore.BasicRepository`1.InsertMany(IList`1 models) in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 194
   at NzbDrone.Core.Books.EditionService.InsertMany(List`1 editions) in D:\a\1\s\src\NzbDrone.Core\Books\Services\EditionService.cs:line 53
   at NzbDrone.Core.Books.BookService.AddBook(Book newBook, Boolean doRefresh) in D:\a\1\s\src\NzbDrone.Core\Books\Services\BookService.cs:line 74
   at NzbDrone.Core.Books.AddBookService.AddBook(Book book, Boolean doRefresh) in D:\a\1\s\src\NzbDrone.Core\Books\Services\AddBookService.cs:line 82
   at NzbDrone.Core.Books.AddBookService.AddBooks(List`1 books, Boolean doRefresh) in D:\a\1\s\src\NzbDrone.Core\Books\Services\AddBookService.cs:line 95

20-8-14 21:44:25.9|Debug|AddBookService|Adding book [63304678][[NULL]]
20-8-14 21:44:25.9|Error|AddBookService|Failed to import id: 63304678 - 

[v0.1.0.170] code = Constraint (19), message = System.Data.SQLite.SQLiteException (0x800027AF): constraint failed
NOT NULL constraint failed: Editions.Title
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in /_/Dapper/SqlMapper.cs:line 1051
   at Dapper.SqlMapper.QueryMultipleImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 1020
   at Dapper.SqlMapper.QueryMultiple(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 996
   at NzbDrone.Core.Datastore.BasicRepository`1.Insert(IDbConnection connection, IDbTransaction transaction, TModel model) in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 176
   at NzbDrone.Core.Datastore.BasicRepository`1.InsertMany(IList`1 models) in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 194
   at NzbDrone.Core.Books.EditionService.InsertMany(List`1 editions) in D:\a\1\s\src\NzbDrone.Core\Books\Services\EditionService.cs:line 53
   at NzbDrone.Core.Books.BookService.AddBook(Book newBook, Boolean doRefresh) in D:\a\1\s\src\NzbDrone.Core\Books\Services\BookService.cs:line 74
   at NzbDrone.Core.Books.AddBookService.AddBook(Book book, Boolean doRefresh) in D:\a\1\s\src\NzbDrone.Core\Books\Services\AddBookService.cs:line 82
   at NzbDrone.Core.Books.AddBookService.AddBooks(List`1 books, Boolean doRefresh) in D:\a\1\s\src\NzbDrone.Core\Books\Services\AddBookService.cs:line 95

20-8-14 21:44:25.9|Debug|AddBookService|Adding book [73056535][[NULL]]
20-8-14 21:44:25.9|Error|AddBookService|Failed to import id: 73056535 - 

[v0.1.0.170] code = Constraint (19), message = System.Data.SQLite.SQLiteException (0x800027AF): constraint failed
NOT NULL constraint failed: Editions.Title
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in /_/Dapper/SqlMapper.cs:line 1051
   at Dapper.SqlMapper.QueryMultipleImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 1020
   at Dapper.SqlMapper.QueryMultiple(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 996
   at NzbDrone.Core.Datastore.BasicRepository`1.Insert(IDbConnection connection, IDbTransaction transaction, TModel model) in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 176
   at NzbDrone.Core.Datastore.BasicRepository`1.InsertMany(IList`1 models) in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 194
   at NzbDrone.Core.Books.EditionService.InsertMany(List`1 editions) in D:\a\1\s\src\NzbDrone.Core\Books\Services\EditionService.cs:line 53
   at NzbDrone.Core.Books.BookService.AddBook(Book newBook, Boolean doRefresh) in D:\a\1\s\src\NzbDrone.Core\Books\Services\BookService.cs:line 74
   at NzbDrone.Core.Books.AddBookService.AddBook(Book book, Boolean doRefresh) in D:\a\1\s\src\NzbDrone.Core\Books\Services\AddBookService.cs:line 82
   at NzbDrone.Core.Books.AddBookService.AddBooks(List`1 books, Boolean doRefresh) in D:\a\1\s\src\NzbDrone.Core\Books\Services\AddBookService.cs:line 95

20-8-14 21:44:25.9|Debug|AddBookService|Adding book [16439607][[NULL]]
20-8-14 21:44:25.9|Error|AddBookService|Failed to import id: 16439607 - 

[v0.1.0.170] code = Constraint (19), message = System.Data.SQLite.SQLiteException (0x800027AF): constraint failed
NOT NULL constraint failed: Editions.Title
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in /_/Dapper/SqlMapper.cs:line 1051
   at Dapper.SqlMapper.QueryMultipleImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 1020
   at Dapper.SqlMapper.QueryMultiple(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 996
   at NzbDrone.Core.Datastore.BasicRepository`1.Insert(IDbConnection connection, IDbTransaction transaction, TModel model) in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 176
   at NzbDrone.Core.Datastore.BasicRepository`1.InsertMany(IList`1 models) in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 194
   at NzbDrone.Core.Books.EditionService.InsertMany(List`1 editions) in D:\a\1\s\src\NzbDrone.Core\Books\Services\EditionService.cs:line 53
   at NzbDrone.Core.Books.BookService.AddBook(Book newBook, Boolean doRefresh) in D:\a\1\s\src\NzbDrone.Core\Books\Services\BookService.cs:line 74
   at NzbDrone.Core.Books.AddBookService.AddBook(Book book, Boolean doRefresh) in D:\a\1\s\src\NzbDrone.Core\Books\Services\AddBookService.cs:line 82
   at NzbDrone.Core.Books.AddBookService.AddBooks(List`1 books, Boolean doRefresh) in D:\a\1\s\src\NzbDrone.Core\Books\Services\AddBookService.cs:line 95

20-8-14 21:44:25.9|Debug|AddBookService|Adding book [48012708][[NULL]]
20-8-14 21:44:25.9|Error|AddBookService|Failed to import id: 48012708 - 

[v0.1.0.170] code = Constraint (19), message = System.Data.SQLite.SQLiteException (0x800027AF): constraint failed
NOT NULL constraint failed: Editions.Title
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in /_/Dapper/SqlMapper.cs:line 1051
   at Dapper.SqlMapper.QueryMultipleImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 1020
   at Dapper.SqlMapper.QueryMultiple(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 996
   at NzbDrone.Core.Datastore.BasicRepository`1.Insert(IDbConnection connection, IDbTransaction transaction, TModel model) in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 176
   at NzbDrone.Core.Datastore.BasicRepository`1.InsertMany(IList`1 models) in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 194
   at NzbDrone.Core.Books.EditionService.InsertMany(List`1 editions) in D:\a\1\s\src\NzbDrone.Core\Books\Services\EditionService.cs:line 53
   at NzbDrone.Core.Books.BookService.AddBook(Book newBook, Boolean doRefresh) in D:\a\1\s\src\NzbDrone.Core\Books\Services\BookService.cs:line 74
   at NzbDrone.Core.Books.AddBookService.AddBook(Book book, Boolean doRefresh) in D:\a\1\s\src\NzbDrone.Core\Books\Services\AddBookService.cs:line 82
   at NzbDrone.Core.Books.AddBookService.AddBooks(List`1 books, Boolean doRefresh) in D:\a\1\s\src\NzbDrone.Core\Books\Services\AddBookService.cs:line 95

20-8-14 21:44:26.0|Debug|AddBookService|Adding book [62967372][[NULL]]
20-8-14 21:44:26.0|Error|AddBookService|Failed to import id: 62967372 - 

[v0.1.0.170] code = Constraint (19), message = System.Data.SQLite.SQLiteException (0x800027AF): constraint failed
NOT NULL constraint failed: Editions.Title
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in /_/Dapper/SqlMapper.cs:line 1051
   at Dapper.SqlMapper.QueryMultipleImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 1020
   at Dapper.SqlMapper.QueryMultiple(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 996
   at NzbDrone.Core.Datastore.BasicRepository`1.Insert(IDbConnection connection, IDbTransaction transaction, TModel model) in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 176
   at NzbDrone.Core.Datastore.BasicRepository`1.InsertMany(IList`1 models) in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 194
   at NzbDrone.Core.Books.EditionService.InsertMany(List`1 editions) in D:\a\1\s\src\NzbDrone.Core\Books\Services\EditionService.cs:line 53
   at NzbDrone.Core.Books.BookService.AddBook(Book newBook, Boolean doRefresh) in D:\a\1\s\src\NzbDrone.Core\Books\Services\BookService.cs:line 74
   at NzbDrone.Core.Books.AddBookService.AddBook(Book book, Boolean doRefresh) in D:\a\1\s\src\NzbDrone.Core\Books\Services\AddBookService.cs:line 82
   at NzbDrone.Core.Books.AddBookService.AddBooks(List`1 books, Boolean doRefresh) in D:\a\1\s\src\NzbDrone.Core\Books\Services\AddBookService.cs:line 95

20-8-14 21:44:26.0|Debug|AddBookService|Adding book [52201861][[NULL]]
20-8-14 21:44:26.0|Error|AddBookService|Failed to import id: 52201861 - 

[v0.1.0.170] code = Constraint (19), message = System.Data.SQLite.SQLiteException (0x800027AF): constraint failed
NOT NULL constraint failed: Editions.Title
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in /_/Dapper/SqlMapper.cs:line 1051
   at Dapper.SqlMapper.QueryMultipleImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 1020
   at Dapper.SqlMapper.QueryMultiple(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 996
   at NzbDrone.Core.Datastore.BasicRepository`1.Insert(IDbConnection connection, IDbTransaction transaction, TModel model) in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 176
   at NzbDrone.Core.Datastore.BasicRepository`1.InsertMany(IList`1 models) in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 194
   at NzbDrone.Core.Books.EditionService.InsertMany(List`1 editions) in D:\a\1\s\src\NzbDrone.Core\Books\Services\EditionService.cs:line 53
   at NzbDrone.Core.Books.BookService.AddBook(Book newBook, Boolean doRefresh) in D:\a\1\s\src\NzbDrone.Core\Books\Services\BookService.cs:line 74
   at NzbDrone.Core.Books.AddBookService.AddBook(Book book, Boolean doRefresh) in D:\a\1\s\src\NzbDrone.Core\Books\Services\AddBookService.cs:line 82
   at NzbDrone.Core.Books.AddBookService.AddBooks(List`1 books, Boolean doRefresh) in D:\a\1\s\src\NzbDrone.Core\Books\Services\AddBookService.cs:line 95

20-8-14 21:44:26.0|Debug|AddBookService|Adding book [46895612][[NULL]]
20-8-14 21:44:26.0|Error|AddBookService|Failed to import id: 46895612 - 

[v0.1.0.170] code = Constraint (19), message = System.Data.SQLite.SQLiteException (0x800027AF): constraint failed
NOT NULL constraint failed: Editions.Title
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in /_/Dapper/SqlMapper.cs:line 1051
   at Dapper.SqlMapper.QueryMultipleImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 1020
   at Dapper.SqlMapper.QueryMultiple(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 996
   at NzbDrone.Core.Datastore.BasicRepository`1.Insert(IDbConnection connection, IDbTransaction transaction, TModel model) in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 176
   at NzbDrone.Core.Datastore.BasicRepository`1.InsertMany(IList`1 models) in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 194
   at NzbDrone.Core.Books.EditionService.InsertMany(List`1 editions) in D:\a\1\s\src\NzbDrone.Core\Books\Services\EditionService.cs:line 53
   at NzbDrone.Core.Books.BookService.AddBook(Book newBook, Boolean doRefresh) in D:\a\1\s\src\NzbDrone.Core\Books\Services\BookService.cs:line 74
   at NzbDrone.Core.Books.AddBookService.AddBook(Book book, Boolean doRefresh) in D:\a\1\s\src\NzbDrone.Core\Books\Services\AddBookService.cs:line 82
   at NzbDrone.Core.Books.AddBookService.AddBooks(List`1 books, Boolean doRefresh) in D:\a\1\s\src\NzbDrone.Core\Books\Services\AddBookService.cs:line 95

20-8-14 21:44:26.0|Debug|AddBookService|Adding book [23840265][[NULL]]
20-8-14 21:44:26.0|Error|AddBookService|Failed to import id: 23840265 - 

[v0.1.0.170] code = Constraint (19), message = System.Data.SQLite.SQLiteException (0x800027AF): constraint failed
NOT NULL constraint failed: Editions.Title
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in /_/Dapper/SqlMapper.cs:line 1051
   at Dapper.SqlMapper.QueryMultipleImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 1020
   at Dapper.SqlMapper.QueryMultiple(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 996
   at NzbDrone.Core.Datastore.BasicRepository`1.Insert(IDbConnection connection, IDbTransaction transaction, TModel model) in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 176
   at NzbDrone.Core.Datastore.BasicRepository`1.InsertMany(IList`1 models) in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 194
   at NzbDrone.Core.Books.EditionService.InsertMany(List`1 editions) in D:\a\1\s\src\NzbDrone.Core\Books\Services\EditionService.cs:line 53
   at NzbDrone.Core.Books.BookService.AddBook(Book newBook, Boolean doRefresh) in D:\a\1\s\src\NzbDrone.Core\Books\Services\BookService.cs:line 74
   at NzbDrone.Core.Books.AddBookService.AddBook(Book book, Boolean doRefresh) in D:\a\1\s\src\NzbDrone.Core\Books\Services\AddBookService.cs:line 82
   at NzbDrone.Core.Books.AddBookService.AddBooks(List`1 books, Boolean doRefresh) in D:\a\1\s\src\NzbDrone.Core\Books\Services\AddBookService.cs:line 95

20-8-14 21:44:26.0|Info|ImportListSyncService|Import List Sync Completed. Items found: 9, Authors added: 0, Books added: 9
```

**Comment by ta264** [comment]
Fixed
