### ISSUE TITLE
api.bookinfo.club 500 InternalServerError

### ISSUE THREAD

**Issue by ConorHK** [Readarr/Readarr#3742]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Any requests to search books results in a 500 InternalServerError
```
2024-09-16 21:10:08.1|Info|Auth|Auth-Success ip 172.18.0.1 username 'admin'
2024-09-16 21:10:21.5|Warn|HttpClient|HTTP Error - Res: HTTP/2.0 [POST] https://api.bookinfo.club/v1/book/bulk: 500.InternalServerError (0 bytes)
2024-09-16 21:10:21.5|Warn|BookInfoProxy|NzbDrone.Common.Http.HttpException: HTTP request failed: [500:InternalServerError] [POST] at [https://api.bookinfo.club/v1/book/bulk]

[v0.3.32.2587] NzbDrone.Common.Http.HttpException: HTTP request failed: [500:InternalServerError] [POST] at [https://api.bookinfo.club/v1/book/bulk]
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in ./Readarr.Common/Http/HttpClient.cs:line 119
   at NzbDrone.Common.Http.HttpClient.PostAsync[T](HttpRequest request) in ./Readarr.Common/Http/HttpClient.cs:line 369
   at NzbDrone.Common.Http.HttpClient.Post[T](HttpRequest request) in ./Readarr.Common/Http/HttpClient.cs:line 377
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.MapSearchResult(List`1 ids) in ./Readarr.Core/MetadataSource/BookInfo/BookInfoProxy.cs:line 493
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.Search(String query, Boolean getAllEditions) in ./Readarr.Core/MetadataSource/BookInfo/BookInfoProxy.cs:line 296

```

### Expected Behavior

Search complete as expected

### Environment

```markdown
- OS: Debian
- Readarr: 0.3.32.2587
- Docker Install: Yes
- Using Reverse Proxy:
```

### What branch are you running?

Master

### Trace Logs?

```
2024-09-16 21:09:15.9|Info|ImportApprovedBooks|Importing 0 files
2024-09-16 21:10:08.1|Info|Auth|Auth-Success ip 172.18.0.1 username 'admin'
2024-09-16 21:10:21.5|Warn|HttpClient|HTTP Error - Res: HTTP/2.0 [POST] https://api.bookinfo.club/v1/book/bulk: 500.InternalServerError (0 bytes)
2024-09-16 21:10:21.5|Warn|BookInfoProxy|NzbDrone.Common.Http.HttpException: HTTP request failed: [500:InternalServerError] [POST] at [https://api.bookinfo.club/v1/book/bulk]

[v0.3.32.2587] NzbDrone.Common.Http.HttpException: HTTP request failed: [500:InternalServerError] [POST] at [https://api.bookinfo.club/v1/book/bulk]
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in ./Readarr.Common/Http/HttpClient.cs:line 119
   at NzbDrone.Common.Http.HttpClient.PostAsync[T](HttpRequest request) in ./Readarr.Common/Http/HttpClient.cs:line 369
   at NzbDrone.Common.Http.HttpClient.Post[T](HttpRequest request) in ./Readarr.Common/Http/HttpClient.cs:line 377
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.MapSearchResult(List`1 ids) in ./Readarr.Core/MetadataSource/BookInfo/BookInfoProxy.cs:line 493
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.Search(String query, Boolean getAllEditions) in ./Readarr.Core/MetadataSource/BookInfo/BookInfoProxy.cs:line 296



```

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
Invalid bug report
- no trace logs
- master is not a valid branch
- metadata server issues are not a readarr bug

see also:
- https://github.com/Readarr/Readarr/issues/2783#issuecomment-2351691389
- The pinned messages in discord
- https://wiki.servarr.com/en/readarr/metadata-issues
