### ISSUE TITLE
GoodReads List Sync Fails to Import Author (and Books)

### ISSUE THREAD

**Issue by jgramling17** [Readarr/Readarr#3924]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

GoodReads List Sync Fails to Import Author (and Books)

The problem seems to be when making a call to api.bookinfo.club/v1/author. It's using the wrong AuthorId. See a snippit from the logs:
```2024-12-11 22:40:08.4|Debug|BookInfoProxy|Getting Author details GoodreadsId of Darby Kane
2024-12-11 22:40:08.4|Trace|ConfigService|Using default config value for 'metadatasource' defaultValue:''
2024-12-11 22:40:08.4|Trace|HttpClient|Req: [GET] https://api.bookinfo.club/v1/author/Darby Kane
2024-12-11 22:40:08.4|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2024-12-11 22:40:08.7|Trace|HttpClient|Res: HTTP/2.0 [GET] https://api.bookinfo.club/v1/author/Darby Kane: 400.BadRequest (249 bytes)
{"type":"https://tools.ietf.org/html/rfc9110#section-15.5.1","title":"One or more validation errors occurred.","status":400,"errors":{"id":["The value 'Darby Kane' is not valid."]},"traceId":"00-910af1e029391e127a7498898934c856-22051e0f07efab84-00"} (330 ms)
2024-12-11 22:40:08.7|Error|AddAuthorService|Failed to import id: Darby Kane - Darby Kane

[v0.4.5.2699] NzbDrone.Core.Exceptions.BadRequestException: Darby Kane
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.PollAuthorUncached(String foreignAuthorId) in ./Readarr.Core/MetadataSource/BookInfo/BookInfoProxy.cs:line 633
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.GetAuthorInfo(String foreignAuthorId, Boolean useCache) in ./Readarr.Core/MetadataSource/BookInfo/BookInfoProxy.cs:line 102
   at NzbDrone.Core.Books.AddAuthorService.AddSkyhookData(Author newAuthor) in ./Readarr.Core/Books/Services/AddAuthorService.cs:line 98
   at NzbDrone.Core.Books.AddAuthorService.AddAuthors(List`1 newAuthors, Boolean doRefresh) in ./Readarr.Core/Books/Services/AddAuthorService.cs:line 73
```

### Expected Behavior

GoodReads List Sync Imports new Authors and Books

### Steps To Reproduce

Create GoodReads List
Sync GoodReads List in Radarr

### Environment

```markdown
- OS: Ubuntu 20.04
- Readarr: 0.4.5.2699
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Chrome (Latest)
- Database: Sqlite 3.45.3
```

### What branch are you running?

Develop

### Trace Logs?

[readarr.trace.txt](https://github.com/user-attachments/files/18105409/readarr.trace.txt)

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by jgramling17** [comment]
@bakerboy448 
Can you explain why this is not a bug?

**Comment by shug4587** [comment]
Unsure if similar issue but also cannot sync with GoodReads using import list function.
Readarr version 0.4.5.2699

No other sync items queued, only the pull from GoodReads shelf.

**Log**
[Warn] BookInfoProxy: Unexpected error getting book info 
[v0.4.5.2699] NzbDrone.Core.MetadataSource.BookInfo.BookInfoException: Unexpected response fetching book data
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.PollBook(String foreignBookId) in ./Readarr.Core/MetadataSource/BookInfo/BookInfoProxy.cs:line 723
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.GetBookInfo(String foreignBookId) in ./Readarr.Core/MetadataSource/BookInfo/BookInfoProxy.cs:line 130
[Error] AddBookService: Book with Foreign Id 70000797 was not found, it may have been removed from Goodreads. 
[Error] AddBookService: Failed to import id: 70000797 -  
[v0.4.5.2699] FluentValidation.ValidationException: Validation failed: 
 -- GoodreadsId: A book with this ID was not found
   at NzbDrone.Core.Books.AddBookService.AddSkyhookData(Book newBook) in ./Readarr.Core/Books/Services/AddBookService.cs:line 117
   at NzbDrone.Core.Books.AddBookService.AddBook(Book book, Boolean doRefresh) in ./Readarr.Core/Books/Services/AddBookService.cs:line 45
   at NzbDrone.Core.Books.AddBookService.AddBooks(List`1 books, Boolean doRefresh) in ./Readarr.Core/Books/Services/AddBookService.cs:line 92
[Warn] BookInfoProxy: Unexpected error getting book info 
[v0.4.5.2699] NzbDrone.Core.MetadataSource.BookInfo.BookInfoException: Unexpected response fetching book data
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.PollBook(String foreignBookId) in ./Readarr.Core/MetadataSource/BookInfo/BookInfoProxy.cs:line 723
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.GetBookInfo(String foreignBookId) in ./Readarr.Core/MetadataSource/BookInfo/BookInfoProxy.cs:line 130
[Error] AddBookService: Book with Foreign Id 47113792 was not found, it may have been removed from Goodreads. 
[Error] AddBookService: Failed to import id: 47113792 -  
[v0.4.5.2699] FluentValidation.ValidationException: Validation failed: 
 -- GoodreadsId: A book with this ID was not found
   at NzbDrone.Core.Books.AddBookService.AddSkyhookData(Book newBook) in ./Readarr.Core/Books/Services/AddBookService.cs:line 117
   at NzbDrone.Core.Books.AddBookService.AddBook(Book book, Boolean doRefresh) in ./Readarr.Core/Books/Services/AddBookService.cs:line 45
   at NzbDrone.Core.Books.AddBookService.AddBooks(List`1 books, Boolean doRefresh) in ./Readarr.Core/Books/Services/AddBookService.cs:line 92
[Warn] BookInfoProxy: Unexpected error getting book info 
[v0.4.5.2699] NzbDrone.Core.MetadataSource.BookInfo.BookInfoException: Failed to get books for 80630360
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.PollBook(String foreignBookId) in ./Readarr.Core/MetadataSource/BookInfo/BookInfoProxy.cs:line 739
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.GetBookInfo(String foreignBookId) in ./Readarr.Core/MetadataSource/BookInfo/BookInfoProxy.cs:line 130
[Error] AddBookService: Book with Foreign Id 80630360 was not found, it may have been removed from Goodreads. 
[Error] AddBookService: Failed to import id: 80630360 -  
[v0.4.5.2699] FluentValidation.ValidationException: Validation failed: 
 -- GoodreadsId: A book with this ID was not found
   at NzbDrone.Core.Books.AddBookService.AddSkyhookData(Book newBook) in ./Readarr.Core/Books/Services/AddBookService.cs:line 117
   at NzbDrone.Core.Books.AddBookService.AddBook(Book book, Boolean doRefresh) in ./Readarr.Core/Books/Services/AddBookService.cs:line 45
   at NzbDrone.Core.Books.AddBookService.AddBooks(List`1 books, Boolean doRefresh) in ./Readarr.Core/Books/Services/AddBookService.cs:line 92
[Warn] BookInfoProxy: Unexpected error getting book info 
[v0.4.5.2699] NzbDrone.Core.MetadataSource.BookInfo.BookInfoException: Unexpected response fetching book data
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.PollBook(String foreignBookId) in ./Readarr.Core/MetadataSource/BookInfo/BookInfoProxy.cs:line 723
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.GetBookInfo(String foreignBookId) in ./Readarr.Core/MetadataSource/BookInfo/BookInfoProxy.cs:line 130
[Error] AddBookService: Book with Foreign Id 71212024 was not found, it may have been removed from Goodreads. 
[Error] AddBookService: Failed to import id: 71212024 -  
[v0.4.5.2699] FluentValidation.ValidationException: Validation failed: 
 -- GoodreadsId: A book with this ID was not found
   at NzbDrone.Core.Books.AddBookService.AddSkyhookData(Book newBook) in ./Readarr.Core/Books/Services/AddBookService.cs:line 117
   at NzbDrone.Core.Books.AddBookService.AddBook(Book book, Boolean doRefresh) in ./Readarr.Core/Books/Services/AddBookService.cs:line 45
   at NzbDrone.Core.Books.AddBookService.AddBooks(List`1 books, Boolean doRefresh) in ./Readarr.Core/Books/Services/AddBookService.cs:line 92
[Warn] BookInfoProxy: Unexpected error getting book info 
[v0.4.5.2699] NzbDrone.Core.MetadataSource.BookInfo.BookInfoException: Unexpected response fetching book data
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.PollBook(String foreignBookId) in ./Readarr.Core/MetadataSource/BookInfo/BookInfoProxy.cs:line 723
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.GetBookInfo(String foreignBookId) in ./Readarr.Core/MetadataSource/BookInfo/BookInfoProxy.cs:line 130
[Error] AddBookService: Book with Foreign Id 56138833 was not found, it may have been removed from Goodreads. 
[Error] AddBookService: Failed to import id: 56138833 -  
[v0.4.5.2699] FluentValidation.ValidationException: Validation failed: 
 -- GoodreadsId: A book with this ID was not found
   at NzbDrone.Core.Books.AddBookService.AddSkyhookData(Book newBook) in ./Readarr.Core/Books/Services/AddBookService.cs:line 117
   at NzbDrone.Core.Books.AddBookService.AddBook(Book book, Boolean doRefresh) in ./Readarr.Core/Books/Services/AddBookService.cs:line 45
   at NzbDrone.Core.Books.AddBookService.AddBooks(List`1 books, Boolean doRefresh) in ./Readarr.Core/Books/Services/AddBookService.cs:line 92
[Info] ImportListSyncService: Import List Sync Completed. Items found: 16, Authors added: 15, Books added: 16 
[Info] ImportListSyncService: Starting Import List Sync 
[Info] ImportListSyncService: No list items to process 
[Info] RssSyncService: Starting RSS Sync 
[Info] DownloadDecisionMaker: Processing 20 releases 
[Info] RssSyncService: RSS Sync Completed. Reports found: 20, Reports grabbed: 0 
[Info] ImportListSyncService: Starting Import List Sync 
[Info] ImportListSyncService: No list items to process 
[Info] ImportListSyncService: Starting Import List Sync 
[Info] ImportListSyncService: No list items to process 
[Info] ImportListSyncService: Starting Import List Sync 
[Info] ImportListSyncService: No list items to process 
[Info] RssSyncService: Starting RSS Sync 
[Info] DownloadDecisionMaker: Processing 20 releases 
[Info] RssSyncService: RSS Sync Completed. Reports found: 20, Reports grabbed: 0

**Comment by mynameisbogdan** [comment]
@shug4587 it is unrelated to this PR, but related to the current metadata's 522 issue.

**Comment by shug4587** [comment]
> @shug4587 it is unrelated to this PR, but related to the current metadata's 522 issue.

Thanks for pointing this out. for others, post here:
https://github.com/Readarr/Readarr/issues/3925

**Comment by shug4587** [comment]
This issue still exists for me. I have a GoodReads bookshelf linked as import list. Readarr finds a file through the indexer, downloads it, but when parsing fails to confirm the author data.

2025-01-17 22:06:42.1|Debug|Parser|Parsing string 'Web of Betrayal: Murder in Ireland’s brutal gangland by Nicola Tallant [ENG / EPUB]'
2025-01-17 22:06:42.1|Debug|Parser|Book Parsed. Nicola Tallant - Web of Betrayal: Murder in Ireland’s brutal gangland 
2025-01-17 22:06:42.1|Debug|QualityParser|Trying to parse quality for 'Web of Betrayal: Murder in Ireland’s brutal gangland by Nicola Tallant [ENG / EPUB]'
2025-01-17 22:06:42.1|Debug|Parser|Quality parsed: EPUB v1
2025-01-17 22:06:42.1|Debug|Parser|Release Group parsed: 
2025-01-17 22:06:42.1|Debug|ParsingService|Trying inexact author match for Nicola Tallant
2025-01-17 22:06:42.1|Debug|ParsingService|No matching author Nicola Tallant
2025-01-17 22:06:42.1|Debug|DownloadDecisionMaker|Release rejected for the following reasons: [Permanent] Unknown Author

Maybe I am missing something?
In the import list profile settings:
Enable Automatic Add - on
Monitor - specific book
Monitor existing books - on
Search for new items - on
Added Author settings:
monitor new books - None

Why is it not automatically adding the author?
Thanks for your help, much appreciated.
