### ISSUE TITLE
Timeout rescanning folders with large library (and slow PC)

### ISSUE THREAD

**Issue by subhuman-zz** [Readarr/Readarr#396]
**Describe the bug**
I connected Readarr to Calibre, but cannot sync the book list, because it times out. However, if I connect to the URL shown in the error log with my web browser, I do get the list - but it takes almost five minutes to produce a 36MB JSON file. My library is fairly extensive, with 11899 books.

**To Reproduce**
1. Connect Readarr to my calibre library
2. Click on Update All on the Library page of Redarr
3. Wait
4. See error show up on console (I am launching from the console):
[Error] CommandExecutor: Error occurred while executing task RescanFolders 

[v10.0.0.32629] System.Net.WebException: The operation has timed out.: 'http://URL:8080/ajax/books'
 ---> System.Net.WebException: The operation has timed out.
   at System.Net.HttpWebRequest.GetResponse()
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in /Users/mmayer/Downloads/Readarr-develop/src/NzbDrone.Common/Http/Dispatchers/ManagedHttpDispatcher.cs:line 97

**Expected behavior**
Since it's not really a timeout, but slow delivery, it shouldn't be timing out. Perhaps the HttpRequest could be set with a higher timeout, or better yet let us set one in the config  of Readarr.

**System info:**
Readarr Version 10.0.0.32542 
.NET Core Yes
DB Migration 2
 - Operating System
macOS Catalina 10.15.6
 - .net Framework
version 3.1, using the Microsoft installer for OSX., yarn 1.22.4, npm 6.14.6

**Comment by subhuman-zz** [comment]
[Readarr.txt](https://github.com/Readarr/Readarr/files/5126860/Readarr.txt)
I have attached my log file.
