### ISSUE TITLE
Manual Import of some files results in "Edition with ID 0 does not exist" error

### ISSUE THREAD

**Issue by misleadingrhino** [Readarr/Readarr#424]
**Describe the bug**
Attempting to Manually Import some files results in the "Edition with ID 0 does not exist" error

**To Reproduce**
1. Manually import a book, seems to be random. 
2. Import results in failure.

**Expected behavior**
Book is imported normally. 

**Logs**
```

Error occurred while executing task ManualImport: Edition with ID 0 does not exist

NzbDrone.Core.Datastore.ModelNotFoundException: Edition with ID 0 does not exist
   at NzbDrone.Core.Datastore.BasicRepository`1.Get(Int32 id) in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 96
   at NzbDrone.Core.MediaFiles.BookImport.Manual.ManualImportService.Execute(ManualImportCommand message) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\BookImport\Manual\ManualImportService.cs:line 294
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 116
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 42
```

https://pastebin.com/q4mCzrdu

**System info (please complete the following information):**
Version 0.1.0.243
Package Version unstable-f1499ec-20 by hotio
.NET Core Yes
Docker Yes
DB Migration 2

**Additional context**
Book in this case is 'Ignition! - John Drury Clark' in the pastebin log.

**Comment by ta264** [comment]
I'm hoping this is fixed now, let me know if not
