### ISSUE TITLE
Proxy for usenet indexers not working after recent update to - 0.1.0.136

### ISSUE THREAD

**Issue by narniamandela** [Readarr/Readarr#44]
**Describe the bug**
Proxy for usenet indexers not working after recent update to - 0.1.0.136

**To Reproduce**

Click on test index

**Expected behavior**
Test successful 

**Logs**

20-7-15 00:22:11.8|Warn|ReadarrErrorPipeline|Invalid request Validation failed: 
 -- : Unable to connect to indexer, check the log for more details

**Comment by narniamandela** [comment]
More logs - 

System.Net.WebException: DNS Name Resolution Failure: 'api.nzbplanet.net'
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in d:\a\1\s\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 96
   at NzbDrone.Common.Http.HttpClient.ExecuteRequest(HttpRequest request, CookieContainer cookieContainer) in d:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 125
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in d:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 59
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchIndexerResponse(IndexerRequest request) in d:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 283
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in d:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 260
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in d:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 297

**Comment by ta264** [comment]
A dns failure is an issue with your local networking or the indexer, not readarr. Joon the discord channel if you need help figuring it out
