### ISSUE TITLE
Import List Sync fails

### ISSUE THREAD

**Issue by wangxu94** [Readarr/Readarr#469]
**Describe the bug**
Initial sync of a goodreads list was successful, but subsequent syncs failed with the error `Error occurred while executing task ImportListSync: Sequence contains no matching element`

**To Reproduce**
1. Go to Settings -> Import Lists
2. Add 'Goodreads Bookshelf'
3. Wait for automatic sync
4. See error in logs

**Expected behavior**
Once a goodreads list has been added, books added to the list should automatically be added to Readarr

**Screenshots**

**Logs**

Message
```
Error occurred while executing task ImportListSync: Sequence contains no matching element
```
Exception
```
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at NzbDrone.Core.ImportLists.ImportListSyncService.MapAlbumReport(ImportListItemInfo report)
   at NzbDrone.Core.ImportLists.ImportListSyncService.ProcessReports(List`1 reports) in D:\a\1\s\src\NzbDrone.Core\ImportLists\ImportListSyncService.cs:line 107
   at NzbDrone.Core.ImportLists.ImportListSyncService.SyncList(ImportListDefinition definition) in D:\a\1\s\src\NzbDrone.Core\ImportLists\ImportListSyncService.cs:line 77
   at NzbDrone.Core.ImportLists.ImportListSyncService.Execute(ImportListSyncCommand message) in D:\a\1\s\src\NzbDrone.Core\ImportLists\ImportListSyncService.cs:line 313
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 116
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 42
```

**System info (please complete the following information):**
 - Readarr Version: 0.1.0.261
 - Operating System: Docker on Ubuntu 18.04
 - .net Framework (Windows) or mono (macOS/Linux) Version: Current version on the official Docker

**Additional context**

**Comment by Drazzilb08** [comment]
Ran into a similar if not the same issue. 
```
20-11-16 18:04:53.4|Error|CommandExecutor|Error occurred while executing task ImportListSync

[v0.1.0.303] System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at NzbDrone.Core.ImportLists.ImportListSyncService.MapAlbumReport(ImportListItemInfo report)
   at NzbDrone.Core.ImportLists.ImportListSyncService.ProcessReports(List`1 reports) in D:\a\1\s\src\NzbDrone.Core\ImportLists\ImportListSyncService.cs:line 107
   at NzbDrone.Core.ImportLists.ImportListSyncService.SyncAll() in D:\a\1\s\src\NzbDrone.Core\ImportLists\ImportListSyncService.cs:line 66
   at NzbDrone.Core.ImportLists.ImportListSyncService.Execute(ImportListSyncCommand message) in D:\a\1\s\src\NzbDrone.Core\ImportLists\ImportListSyncService.cs:line 317
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 116
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 42


20-11-16 18:04:53.5|Trace|Http|Req: 85 [GET] /api/v1/command
```

When looking at my Import list from GoodReads one of the shelves made was 'Want to Read' when shown in Readarr it only shows up as `to-read`. 

After realizing this I went to test a theory. Adding a new shelf simply named `Add` I moved one of the books to that shelf, checked the `Add` box in the import settings and reran the import with success.

**Comment by babos123** [comment]
same here ...
Error occurred while executing task ImportListSync: Sequence contains no matching element
Exception
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at NzbDrone.Core.ImportLists.ImportListSyncService.MapAlbumReport(ImportListItemInfo report)
   at NzbDrone.Core.ImportLists.ImportListSyncService.ProcessReports(List`1 reports) in D:\a\1\s\src\NzbDrone.Core\ImportLists\ImportListSyncService.cs:line 107
   at NzbDrone.Core.ImportLists.ImportListSyncService.SyncAll() in D:\a\1\s\src\NzbDrone.Core\ImportLists\ImportListSyncService.cs:line 66
   at NzbDrone.Core.ImportLists.ImportListSyncService.Execute(ImportListSyncCommand message) in D:\a\1\s\src\NzbDrone.Core\ImportLists\ImportListSyncService.cs:line 317
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 86
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 42

**Comment by Gelioks** [comment]
The same here
