### ISSUE TITLE
Error occurred while executing task RescanFolders

### ISSUE THREAD

**Issue by mixednutts** [Readarr/Readarr#581]
My setup includes calibre integration and I have manually imported a book into the calibre library.  When I run the rescan folders task it fails with following details.

Edit:  The book to be imported already existed in readarr but was not downloaded.  I removed the book from readarr and it indicated successful import from calibre but does not appear in readarr.

```
20-11-2 05:51:06.7|Info|DiskScanService|Scanning /srv/calibre
20-11-2 05:51:06.7|Info|DiskScanService|Getting book list from calibre for /srv/calibre
20-11-2 05:51:06.9|Info|ImportDecisionMaker|Reading file 1/1
20-11-2 05:51:06.9|Info|TrackGroupingService|Grouping 1 tracks
20-11-2 05:51:06.9|Info|IdentificationService|Identifying book 1/1
20-11-2 05:51:08.8|Info|ImportApprovedBooks|Importing book 1/1 [1245597][First King of Shannara]
20-11-2 05:51:08.8|Warn|ArgumentValidator|Expected an expression that evaluates to true.
20-11-2 05:51:08.9|Info|DiskScanService|Scanning /srv/calibre
20-11-2 05:51:08.9|Info|DiskScanService|Getting book list from calibre for /srv/calibre
20-11-2 05:51:08.9|Error|CommandExecutor|Error occurred while executing task RescanFolders

[v0.1.0.303] System.ArgumentException: Expected an expression that evaluates to true.
   at NzbDrone.Common.EnsureThat.EnsureBoolExtensions.IsTrue(Param`1 param) in D:\a\1\s\src\NzbDrone.Common\EnsureThat\EnsureBoolExtensions.cs:line 16
   at NzbDrone.Core.Books.EditionRepository.SetMonitored(Edition edition) in D:\a\1\s\src\NzbDrone.Core\Books\Repositories\EditionRepository.cs:line 71
   at NzbDrone.Core.Books.EditionService.SetMonitored(Edition edition) in D:\a\1\s\src\NzbDrone.Core\Books\Services\EditionService.cs:line 86
   at NzbDrone.Core.MediaFiles.BookImport.ImportApprovedBooks.Import(List`1 decisions, Boolean replaceExisting, DownloadClientItem downloadClientItem, ImportMode importMode) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\BookImport\ImportApprovedBooks.cs:line 121
   at NzbDrone.Core.MediaFiles.DiskScanService.Scan(List`1 folders, FilterFilesType filter, Boolean addNewArtists, List`1 authorIds) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\DiskScanService.cs:line 168
   at NzbDrone.Core.MediaFiles.DiskScanService.Execute(RescanFoldersCommand message) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\DiskScanService.cs:line 304
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 116
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 42


20-11-2 05:51:09.1|Info|ImportDecisionMaker|Reading file 1/1
20-11-2 05:51:09.1|Info|TrackGroupingService|Grouping 1 tracks
20-11-2 05:51:09.1|Info|IdentificationService|Identifying book 1/1
20-11-2 05:51:10.4|Info|ImportApprovedBooks|Importing book 1/1 [1245597][First King of Shannara]
20-11-2 05:51:10.4|Warn|ArgumentValidator|Expected an expression that evaluates to true.
20-11-2 05:51:10.4|Error|CommandExecutor|Error occurred while executing task RescanFolders

[v0.1.0.303] System.ArgumentException: Expected an expression that evaluates to true.
   at NzbDrone.Common.EnsureThat.EnsureBoolExtensions.IsTrue(Param`1 param) in D:\a\1\s\src\NzbDrone.Common\EnsureThat\EnsureBoolExtensions.cs:line 16
   at NzbDrone.Core.Books.EditionRepository.SetMonitored(Edition edition) in D:\a\1\s\src\NzbDrone.Core\Books\Repositories\EditionRepository.cs:line 71
   at NzbDrone.Core.Books.EditionService.SetMonitored(Edition edition) in D:\a\1\s\src\NzbDrone.Core\Books\Services\EditionService.cs:line 86
   at NzbDrone.Core.MediaFiles.BookImport.ImportApprovedBooks.Import(List`1 decisions, Boolean replaceExisting, DownloadClientItem downloadClientItem, ImportMode importMode) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\BookImport\ImportApprovedBooks.cs:line 121
   at NzbDrone.Core.MediaFiles.DiskScanService.Scan(List`1 folders, FilterFilesType filter, Boolean addNewArtists, List`1 authorIds) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\DiskScanService.cs:line 168
   at NzbDrone.Core.MediaFiles.DiskScanService.Execute(RescanFoldersCommand message) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\DiskScanService.cs:line 304
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 116
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 42
```

Edit:  The book to be imported already existed in readarr but was not downloaded.  I removed the book from readarr and it indicated successful import from calibre but does not appear in readarr.  If I try to add the book again manually in readarr using the green add book button it doesn't work.  Log messages are as follows:

```
20-11-2 06:30:03.9|Debug|AddBookService|Adding book [1245597][First King of Shannara]
20-11-2 06:30:04.0|Warn|ReadarrErrorPipeline|System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Books.AddBookService.AddBook(Book book, Boolean doRefresh) in D:\a\1\s\src\NzbDrone.Core\Books\Services\AddBookService.cs:line 61
   at Readarr.Api.V1.Books.BookModule.AddBook(BookResource bookResource) in D:\a\1\s\src\Readarr.Api.V1\Books\BookModule.cs:line 155
   at Readarr.Http.REST.RestModule`1.<set_CreateResource>b__42_0(Object options) in D:\a\1\s\src\Readarr.Http\REST\RestModule.cs:line 190
   at Nancy.NancyModule.<>c__DisplayClass38_0`1.<Post>b__0(Object args)
   at Nancy.NancyModule.<>c__DisplayClass40_0`1.<Post>b__0(Object args, CancellationToken ct)
   at Nancy.Routing.Route`1.Invoke(DynamicDictionary parameters, CancellationToken cancellationToken)
   at Nancy.Routing.DefaultRouteInvoker.Invoke(Route route, CancellationToken cancellationToken, DynamicDictionary parameters, NancyContext context)
   at Nancy.Routing.DefaultRequestDispatcher.Dispatch(NancyContext context, CancellationToken cancellationToken)
   at Nancy.NancyEngine.InvokeRequestLifeCycle(NancyContext context, CancellationToken cancellationToken, IPipelines pipelines)

[v0.1.0.303] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Books.AddBookService.AddBook(Book book, Boolean doRefresh) in D:\a\1\s\src\NzbDrone.Core\Books\Services\AddBookService.cs:line 61
   at Readarr.Api.V1.Books.BookModule.AddBook(BookResource bookResource) in D:\a\1\s\src\Readarr.Api.V1\Books\BookModule.cs:line 155
   at Readarr.Http.REST.RestModule`1.<set_CreateResource>b__42_0(Object options) in D:\a\1\s\src\Readarr.Http\REST\RestModule.cs:line 190
   at Nancy.NancyModule.<>c__DisplayClass38_0`1.<Post>b__0(Object args)
   at Nancy.NancyModule.<>c__DisplayClass40_0`1.<Post>b__0(Object args, CancellationToken ct)
   at Nancy.Routing.Route`1.Invoke(DynamicDictionary parameters, CancellationToken cancellationToken)
   at Nancy.Routing.DefaultRouteInvoker.Invoke(Route route, CancellationToken cancellationToken, DynamicDictionary parameters, NancyContext context)
   at Nancy.Routing.DefaultRequestDispatcher.Dispatch(NancyContext context, CancellationToken cancellationToken)
   at Nancy.NancyEngine.InvokeRequestLifeCycle(NancyContext context, CancellationToken cancellationToken, IPipelines pipelines)


20-11-2 06:30:04.0|Fatal|ReadarrErrorPipeline|Request Failed. POST /api/v1/book

[v0.1.0.303] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Books.AddBookService.AddBook(Book book, Boolean doRefresh) in D:\a\1\s\src\NzbDrone.Core\Books\Services\AddBookService.cs:line 61
   at Readarr.Api.V1.Books.BookModule.AddBook(BookResource bookResource) in D:\a\1\s\src\Readarr.Api.V1\Books\BookModule.cs:line 155
   at Readarr.Http.REST.RestModule`1.<set_CreateResource>b__42_0(Object options) in D:\a\1\s\src\Readarr.Http\REST\RestModule.cs:line 190
   at Nancy.NancyModule.<>c__DisplayClass38_0`1.<Post>b__0(Object args)
   at Nancy.NancyModule.<>c__DisplayClass40_0`1.<Post>b__0(Object args, CancellationToken ct)
   at Nancy.Routing.Route`1.Invoke(DynamicDictionary parameters, CancellationToken cancellationToken)
   at Nancy.Routing.DefaultRouteInvoker.Invoke(Route route, CancellationToken cancellationToken, DynamicDictionary parameters, NancyContext context)
   at Nancy.Routing.DefaultRequestDispatcher.Dispatch(NancyContext context, CancellationToken cancellationToken)
   at Nancy.NancyEngine.InvokeRequestLifeCycle(NancyContext context, CancellationToken cancellationToken, IPipelines pipelines)
```

Version: 0.1.0.303
Package Version: 0.1.0.303-1 by readarr
.NET Core: Yes
DB Migration: 4
OS: archlinux 5.9.2-arch1-1

[AB#542](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/542)

**Comment by ytilis** [comment]
Wanted to chime in that I'm seeing the same thing. It seems to be consistently hitting a roadblock on the same book for me, causing all further imports of unmapped books to stop.

Trace log attached:
```
21-2-22 18:41:43.2|Debug|DiskScanService|Import decisions complete [00:05:58.4008316]
21-2-22 18:41:43.2|Info|ImportApprovedBooks|Importing book 1/72 [21553161][Shadows Over Innocence]
21-2-22 18:41:43.2|Trace|EventAggregator|Publishing CommandUpdatedEvent
21-2-22 18:41:43.2|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
21-2-22 18:41:43.2|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
21-2-22 18:41:43.2|Debug|ImportApprovedBooks|Updating release to [15822885][Shadows Over Innocence]
21-2-22 18:41:43.2|Trace|EventAggregator|Publishing BookEditedEvent
21-2-22 18:41:43.2|Trace|EventAggregator|BookEditedEvent -> AuthorStatisticsService
21-2-22 18:41:43.2|Trace|EventAggregator|BookEditedEvent <- AuthorStatisticsService
21-2-22 18:41:43.2|Trace|EventAggregator|BookEditedEvent -> BookModule
21-2-22 18:41:44.2|Trace|EventAggregator|BookEditedEvent <- BookModule
21-2-22 18:41:44.2|Trace|EventAggregator|BookEditedEvent -> AuthorModule
21-2-22 18:41:44.2|Trace|EventAggregator|BookEditedEvent <- AuthorModule
21-2-22 18:41:44.2|Info|ImportApprovedBooks|Importing book 2/72 [44951001][Crucible: All-New Tales of Valdemar]
21-2-22 18:41:44.2|Trace|EventAggregator|Publishing CommandUpdatedEvent
21-2-22 18:41:44.2|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
21-2-22 18:41:44.2|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
21-2-22 18:41:44.2|Debug|ImportApprovedBooks|Updating release to [25459706][Crucible]
21-2-22 18:41:44.2|Warn|ArgumentValidator|Expected an expression that evaluates to true.
21-2-22 18:41:44.2|Trace|CommandQueueManager|Updating command status
21-2-22 18:41:44.2|Trace|EventAggregator|Publishing CommandUpdatedEvent
21-2-22 18:41:44.2|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
21-2-22 18:41:44.2|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
21-2-22 18:41:44.2|Trace|EventAggregator|Publishing CommandExecutedEvent
21-2-22 18:41:44.2|Trace|EventAggregator|CommandExecutedEvent -> TaskManager
21-2-22 18:41:44.2|Trace|TaskManager|Updating last run time for: NzbDrone.Core.MediaFiles.Commands.RescanFoldersCommand
21-2-22 18:41:44.2|Trace|CommandExecutor|ProcessMonitoredDownloadsCommand -> DownloadProcessingService
21-2-22 18:41:44.2|Trace|CommandQueueManager|Marking command as started: ProcessMonitoredDownloads
21-2-22 18:41:44.2|Trace|EventAggregator|CommandExecutedEvent <- TaskManager
21-2-22 18:41:44.2|Trace|EventAggregator|CommandExecutedEvent -> TaskModule
21-2-22 18:41:44.2|Trace|EventAggregator|CommandExecutedEvent <- TaskModule
21-2-22 18:41:44.2|Trace|CommandExecutor|RescanFoldersCommand <- DiskScanService [00:06:03.4974258]
21-2-22 18:41:44.2|Error|CommandExecutor|Error occurred while executing task RescanFolders

[v0.1.0.500] System.ArgumentException: Expected an expression that evaluates to true.
   at NzbDrone.Common.EnsureThat.EnsureBoolExtensions.IsTrue(Param`1 param) in D:\a\1\s\src\NzbDrone.Common\EnsureThat\EnsureBoolExtensions.cs:line 13
   at NzbDrone.Core.Books.EditionRepository.SetMonitored(Edition edition) in D:\a\1\s\src\NzbDrone.Core\Books\Repositories\EditionRepository.cs:line 70
   at NzbDrone.Core.Books.EditionService.SetMonitored(Edition edition) in D:\a\1\s\src\NzbDrone.Core\Books\Services\EditionService.cs:line 86
   at NzbDrone.Core.MediaFiles.BookImport.ImportApprovedBooks.Import(List`1 decisions, Boolean replaceExisting, DownloadClientItem downloadClientItem, ImportMode importMode) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\BookImport\ImportApprovedBooks.cs:line 121
   at NzbDrone.Core.MediaFiles.DiskScanService.Scan(List`1 folders, FilterFilesType filter, Boolean addNewAuthors, List`1 authorIds) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\DiskScanService.cs:line 170
   at NzbDrone.Core.MediaFiles.DiskScanService.Execute(RescanFoldersCommand message) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\DiskScanService.cs:line 311
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 116
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 42


21-2-22 18:41:44.3|Trace|ConfigService|Using default config value for 'enablecompleteddownloadhandling' defaultValue:'True'
21-2-22 18:41:44.3|Trace|ConfigService|Using default config value for 'removecompleteddownloads' defaultValue:'False'
21-2-22 18:41:44.3|Trace|EventAggregator|Publishing DownloadsProcessedEvent
21-2-22 18:41:44.3|Trace|EventAggregator|DownloadsProcessedEvent -> DownloadMonitoringService
21-2-22 18:41:44.3|Trace|EventAggregator|Publishing TrackedDownloadRefreshedEvent
21-2-22 18:41:44.3|Trace|EventAggregator|TrackedDownloadRefreshedEvent -> QueueService
21-2-22 18:41:44.3|Trace|EventAggregator|Publishing QueueUpdatedEvent
21-2-22 18:41:44.3|Trace|EventAggregator|QueueUpdatedEvent -> QueueDetailsModule
21-2-22 18:41:44.3|Trace|EventAggregator|QueueUpdatedEvent <- QueueDetailsModule
21-2-22 18:41:44.3|Trace|EventAggregator|QueueUpdatedEvent -> QueueModule
21-2-22 18:41:44.3|Trace|EventAggregator|QueueUpdatedEvent <- QueueModule
21-2-22 18:41:44.3|Trace|EventAggregator|QueueUpdatedEvent -> QueueStatusModule
21-2-22 18:41:44.3|Trace|EventAggregator|QueueUpdatedEvent <- QueueStatusModule
21-2-22 18:41:44.3|Trace|EventAggregator|TrackedDownloadRefreshedEvent <- QueueService
21-2-22 18:41:44.3|Trace|EventAggregator|DownloadsProcessedEvent <- DownloadMonitoringService
21-2-22 18:41:44.3|Trace|CommandQueueManager|Updating command status
21-2-22 18:41:44.3|Trace|EventAggregator|Publishing CommandExecutedEvent
21-2-22 18:41:44.3|Trace|EventAggregator|CommandExecutedEvent -> TaskManager
21-2-22 18:41:44.3|Trace|EventAggregator|CommandExecutedEvent <- TaskManager
21-2-22 18:41:44.3|Trace|EventAggregator|CommandExecutedEvent -> TaskModule
21-2-22 18:41:44.3|Trace|EventAggregator|CommandExecutedEvent <- TaskModule
21-2-22 18:41:44.3|Trace|CommandExecutor|ProcessMonitoredDownloadsCommand <- DownloadProcessingService [00:00:00.0278890]
21-2-22 18:41:44.3|Trace|Http|Req: 399 [GET] /api/v1/command (from ::ffff:172.22.0.6 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36)
21-2-22 18:41:44.3|Trace|CommandQueueManager|Getting all commands
21-2-22 18:41:44.3|Trace|Http|Res: 399 [GET] /api/v1/command: 200.OK (0 ms)
21-2-22 18:41:44.3|Debug|Api|[GET] /api/v1/command: 200.OK (0 ms)
21-2-22 18:41:44.4|Trace|Http|Req: 400 [GET] /api/v1/command (from ::ffff:172.22.0.6 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36)
21-2-22 18:41:44.4|Trace|CommandQueueManager|Getting all commands
21-2-22 18:41:44.4|Trace|Http|Res: 400 [GET] /api/v1/command: 200.OK (0 ms)
21-2-22 18:41:44.4|Debug|Api|[GET] /api/v1/command: 200.OK (0 ms)
21-2-22 18:42:05.4|Trace|Http|Req: 401 [GET] /logfile/Readarr.txt (from ::ffff:172.22.0.6 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36)
21-2-22 18:42:05.4|Trace|Http|Res: 401 [GET] /logfile/Readarr.txt: 200.OK (0 ms)
21-2-22 18:42:05.9|Trace|Http|Req: 402 [GET] /favicon.ico (from ::ffff:172.22.0.6 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36)
21-2-22 18:42:05.9|Trace|Http|Res: 402 [GET] /favicon.ico: 200.OK (1 ms)
```

**Version**: 0.1.0.500
**Package Version**: nightly-8f46936 by hotio
**.NET Core**: Yes (5.0.3)
**Docker**: Yes
**DB Migration**: 6

**Comment by ta264** [comment]
I think anyone suffering from this will need to start with a fresh database.  If it's still an issue after that we can re-open.
