### ISSUE TITLE
OverflowException: Value was either too large or too small for an Int32

### ISSUE THREAD

**Issue by vityav** [Readarr/Readarr#625]
**Describe the bug**
"Error occurred while executing task RescanFolders." This seems to happen immediately after it finishes importing files.

**To Reproduce**
1. Initiate task RescanFolders
2. Wait for importing to complete
3. See error

**Expected behavior**
RescanFolders to complete successfully

**Logs**
```
20-11-23 01:49:06.0|Info|ImportApprovedBooks|Importing book 104/104 [60021532][Elevation]
20-11-23 01:49:06.0|Debug|ImportApprovedBooks|Updating release to [38355410][Elevation]
20-11-23 01:49:08.0|Info|ImportApprovedBooks|Importing 106 files
20-11-23 01:49:08.0|Debug|ImportApprovedBooks|Importing 106 files. replaceExisting: False
20-11-23 01:49:08.2|Debug|ImportApprovedBooks|Inserted new trackfiles in 28ms
20-11-23 01:49:14.0|Debug|Parser|Parsing string 'Children-Nameless-Sanderson'
20-11-23 01:49:14.0|Debug|Parser|Unable to parse Children-Nameless-Sanderson
20-11-23 01:49:14.0|Debug|Parser|Parsing string 'Children of the Nameless by Magic: the Gathering [ENG / epub mobi pdf]'
20-11-23 01:49:14.0|Debug|Parser|Unable to parse Children of the Nameless by Magic: the Gathering [ENG / epub mobi pdf]
20-11-23 01:49:14.0|Debug|Parser|Parsing string 'Children of the Nameless by Magic: the Gathering [ENG / epub mobi pdf]' using search criteria author: 'Brandon Sanderson' books: 'Children of the Nameless'
20-11-23 01:50:15.5|Error|CommandExecutor|Error occurred while executing task RescanFolders

[v0.1.0.303] System.OverflowException: Value was either too large or too small for an Int32.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Number.ParseInt32(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
   at System.Int32.Parse(String s)
   at NzbDrone.Core.Parser.Parser.ParseCalibreId(String path) in D:\a\1\s\src\NzbDrone.Core\Parser\Parser.cs:line 470
   at NzbDrone.Core.MediaFiles.DiskScanService.<>c.<Scan>b__13_4(ImportDecision`1 decision) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\DiskScanService.cs:line 173
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at NzbDrone.Core.MediaFiles.DiskScanService.Scan(List`1 folders, FilterFilesType filter, Boolean addNewArtists, List`1 authorIds) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\DiskScanService.cs:line 184
   at NzbDrone.Core.MediaFiles.DiskScanService.Execute(RescanFoldersCommand message) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\DiskScanService.cs:line 304
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 86
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 42
```

**System info (please complete the following information):**
 - Readarr Version: 0.1.0.303
 - Package Version:  [Docker] nightly-375ea03-78 by hotio 

**Additional info**
I have just under 3000 books in the library so I don't know what's actually hitting an integer limit.

[AB#585](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/585)

**Comment by grostim** [comment]
Hi ,

I am facing a similar issue:

```
20-12-30 18:23:43.4|Info|IdentificationService|Identifying book 3201/3208
20-12-30 18:23:43.4|Info|IdentificationService|Identifying book 3202/3208
20-12-30 18:23:43.4|Info|IdentificationService|Identifying book 3203/3208
20-12-30 18:23:43.4|Info|IdentificationService|Identifying book 3204/3208
20-12-30 18:23:43.4|Info|IdentificationService|Identifying book 3205/3208
20-12-30 18:23:43.4|Info|IdentificationService|Identifying book 3206/3208
20-12-30 18:23:43.4|Info|IdentificationService|Identifying book 3207/3208
20-12-30 18:23:43.4|Info|IdentificationService|Identifying book 3208/3208
20-12-30 18:23:43.7|Info|ImportApprovedBooks|Importing 0 files
20-12-30 18:23:43.8|Error|CommandExecutor|Error occurred while executing task RescanFolders

[v0.1.0.351] System.OverflowException: Value was either too large or too small for an Int32.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Number.ParseInt32(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
   at NzbDrone.Core.Parser.Parser.ParseCalibreId(String path) in D:\a\1\s\src\NzbDrone.Core\Parser\Parser.cs:line 466
   at NzbDrone.Core.MediaFiles.DiskScanService.<>c.<Scan>b__13_4(ImportDecision`1 decision) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\DiskScanService.cs:line 173
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at NzbDrone.Core.MediaFiles.DiskScanService.Scan(List`1 folders, FilterFilesType filter, Boolean addNewArtists, List`1 authorIds) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\DiskScanService.cs:line 184
   at NzbDrone.Core.MediaFiles.DiskScanService.Execute(RescanFoldersCommand message) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\DiskScanService.cs:line 304
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 116
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 42
```

**Comment by Qstick** [comment]
ParseCalibreId is no longer a method
