### ISSUE TITLE
Access to local folder /data/downloads/Seeding/Books denied when importing downloaded book

### ISSUE THREAD

**Issue by bobvmierlo** [Readarr/Readarr#641]
**Describe the bug**
On a clean install I get the error in this tracelogs when trying to import a downloaded book through Readarr and DS station.
I would expect Readarr to have access to it's own local paths. Full error in the tracelog, small error from Events below.
```
Message
Couldn't import book /data/downloads/Seeding/Books/Readarr/Maker's Curse by Trudi Canavan EPUB/Maker's Curse by Trudi Canavan.epub: Access to the path is denied.

Exception
System.UnauthorizedAccessException: Access to the path is denied.
 ---> System.IO.IOException: Operation not permitted
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.FileSystem.LinkOrCopyFile(String sourceFullPath, String destFullPath)
   at System.IO.FileSystem.MoveFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.Move(String sourceFileName, String destFileName, Boolean overwrite)
   at System.IO.File.Move(String sourceFileName, String destFileName)
   at System.IO.Abstractions.FileWrapper.Move(String sourceFileName, String destFileName)
   at NzbDrone.Common.Disk.DiskProviderBase.MoveFileInternal(String source, String destination) in D:\a\1\s\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 257
   at NzbDrone.Mono.Disk.DiskProvider.MoveFileInternal(String source, String destination) in D:\a\1\s\src\NzbDrone.Mono\Disk\DiskProvider.cs:line 226
   at NzbDrone.Common.Disk.DiskProviderBase.MoveFile(String source, String destination, Boolean overwrite) in D:\a\1\s\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 244
   at NzbDrone.Common.Disk.DiskTransferService.TryMoveFileTransactional(String sourcePath, String targetPath, Int64 originalSize, DiskTransferVerificationMode verificationMode) in D:\a\1\s\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 530
   at NzbDrone.Common.Disk.DiskTransferService.TransferFile(String sourcePath, String targetPath, TransferMode mode, Boolean overwrite, DiskTransferVerificationMode verificationMode) in D:\a\1\s\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 350
   at NzbDrone.Common.Disk.DiskTransferService.TransferFile(String sourcePath, String targetPath, TransferMode mode, Boolean overwrite, Boolean verified) in D:\a\1\s\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 233
   at NzbDrone.Core.MediaFiles.BookFileMovingService.TransferFile(BookFile bookFile, Author author, Book book, String destinationFilePath, TransferMode mode) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\BookFileMovingService.cs:line 124
   at NzbDrone.Core.MediaFiles.BookFileMovingService.MoveBookFile(BookFile bookFile, LocalBook localBook) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\BookFileMovingService.cs:line 83
   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeBookFile(BookFile bookFile, LocalBook localBook, Boolean copyOnly) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\UpgradeMediaFileService.cs:line 107
   at NzbDrone.Core.MediaFiles.BookImport.ImportApprovedBooks.Import(List`1 decisions, Boolean replaceExisting, DownloadClientItem downloadClientItem, ImportMode importMode) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\BookImport\ImportApprovedBooks.cs:line 190
```

**Platform Information (please complete the following information):**
 - OS: Synology DSM 6.2.3-25426 Update 2
 - Docker: YES
 - Mono or.NET Core Version: .NET Core from docker image 'nightly-b1a3fc2-92 by hotio'
 - Readarr Version: 0.1.0.328
 - Readarr Branch: nightly

**Trace Logs**

[Readarr.trace.txt](https://github.com/Readarr/Readarr/files/5662506/Readarr.trace.txt)

**Comment by bakerboy448** [comment]
I'll defer to ta or q, but pretty sure it isn't a bug

https://wiki.servarr.com/Docker_Guide

**Comment by ta264** [comment]
No, pretty sure this is just user error. Radarr didn't create that folder, you need to fix your permission
