### ISSUE TITLE
No results were returned from your indexer

### ISSUE THREAD

**Issue by averri** [Readarr/Readarr#644]
**Describe the bug**
It's not possible to configure Jackett indexer, it says *no results were returned from your indexer*.

**To Reproduce**
1. Add a new indexer, select Torznab and add the Jackett URL `http://localhost:9117/api/v2.0/indexers/all/results/torznab/`, and the API key.
2. Click the **Test** button.

The UI shows an error message:
```text
Query successful, but no results were returned from your indexer. This may be an issue with the indexer or your indexer category settings.
```

**Expected behavior**
The test should pass, as the Jackett is available. Using Radarr with the same configuration works with no problems.

**Screenshots**

**Platform Information (please complete the following information):**
 - OS: Ubuntu 18.04
 - Docker:Yes
 - Mono or.NET Core Version: [e.g. Mono 5.8 or .Net Core 3.1.10] (found under System -> Status)
 - Browser and Version [e.g. chrome 86.0.4240.198] (Only needed for UI issues)
 - Readarr Version 0.1.0.328, nightly-b1a3fc2-92 by hotio
 - Readarr Branch [e.g. master]

**Trace Logs**
```logs
20-12-9 21:16:34.7|Debug|Api|[GET] /api/v1/command: 200.OK (1 ms)
20-12-9 21:16:57.7|Trace|Http|Req: 25 [POST] /api/v1/indexer/test
20-12-9 21:16:57.8|Trace|HttpClient|Req: [GET] http://localhost:9117/api/v2.0/indexers/all/results/torznab/api?t=caps&apikey=(removed)
20-12-9 21:16:57.8|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
20-12-9 21:16:57.8|Trace|HttpClient|Res: [GET] http://localhost:9117/api/v2.0/indexers/all/results/torznab/api?t=caps&apikey=(removed) 200.OK (60 ms)
20-12-9 21:16:57.8|Debug|Torznab|Downloading Feed http://localhost:9117/api/v2.0/indexers/all/results/torznab/api?t=book&cat=7020,8010&extended=1&apikey=(removed)&offset=0&limit=1000
20-12-9 21:16:57.8|Trace|HttpClient|Req: [GET] http://localhost:9117/api/v2.0/indexers/all/results/torznab/api?t=book&cat=7020,8010&extended=1&apikey=(removed)&offset=0&limit=1000
20-12-9 21:16:57.8|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
20-12-9 21:17:00.5|Trace|HttpClient|Res: [GET] http://localhost:9117/api/v2.0/indexers/all/results/torznab/api?t=book&cat=7020,8010&extended=1&apikey=(removed)&offset=0&limit=1000: 200.OK (2711 ms)
20-12-9 21:17:00.6|Trace|ReadarrErrorPipeline|Handling Exception
20-12-9 21:17:00.6|Warn|ReadarrErrorPipeline|FluentValidation.ValidationException: Validation failed: 
 -- : Query successful, but no results were returned from your indexer. This may be an issue with the indexer or your indexer category settings.
   at Readarr.Api.V1.ProviderModuleBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in D:\a\1\s\src\Readarr.Api.V1\ProviderModuleBase.cs:line 207
   at Readarr.Api.V1.ProviderModuleBase`3.Test(TProviderDefinition definition, Boolean includeWarnings) in D:\a\1\s\src\Readarr.Api.V1\ProviderModuleBase.cs:line 191
   at Readarr.Api.V1.ProviderModuleBase`3.Test(TProviderResource providerResource) in D:\a\1\s\src\Readarr.Api.V1\ProviderModuleBase.cs:line 143
   at Readarr.Api.V1.ProviderModuleBase`3.<.ctor>b__2_1(Object x) in D:\a\1\s\src\Readarr.Api.V1\ProviderModuleBase.cs:line 28
   at Nancy.NancyModule.<>c__DisplayClass38_0`1.<Post>b__0(Object args)
   at Nancy.NancyModule.<>c__DisplayClass40_0`1.<Post>b__0(Object args, CancellationToken ct)
   at Nancy.Routing.Route`1.Invoke(DynamicDictionary parameters, CancellationToken cancellationToken)
   at Nancy.Routing.DefaultRouteInvoker.Invoke(Route route, CancellationToken cancellationToken, DynamicDictionary parameters, NancyContext context)
   at Nancy.Routing.DefaultRequestDispatcher.Dispatch(NancyContext context, CancellationToken cancellationToken)
   at Nancy.NancyEngine.InvokeRequestLifeCycle(NancyContext context, CancellationToken cancellationToken, IPipelines pipelines)

[v0.1.0.328] FluentValidation.ValidationException: Validation failed: 
 -- : Query successful, but no results were returned from your indexer. This may be an issue with the indexer or your indexer category settings.
   at Readarr.Api.V1.ProviderModuleBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in D:\a\1\s\src\Readarr.Api.V1\ProviderModuleBase.cs:line 207
   at Readarr.Api.V1.ProviderModuleBase`3.Test(TProviderDefinition definition, Boolean includeWarnings) in D:\a\1\s\src\Readarr.Api.V1\ProviderModuleBase.cs:line 191
   at Readarr.Api.V1.ProviderModuleBase`3.Test(TProviderResource providerResource) in D:\a\1\s\src\Readarr.Api.V1\ProviderModuleBase.cs:line 143
   at Readarr.Api.V1.ProviderModuleBase`3.<.ctor>b__2_1(Object x) in D:\a\1\s\src\Readarr.Api.V1\ProviderModuleBase.cs:line 28
   at Nancy.NancyModule.<>c__DisplayClass38_0`1.<Post>b__0(Object args)
   at Nancy.NancyModule.<>c__DisplayClass40_0`1.<Post>b__0(Object args, CancellationToken ct)
   at Nancy.Routing.Route`1.Invoke(DynamicDictionary parameters, CancellationToken cancellationToken)
   at Nancy.Routing.DefaultRouteInvoker.Invoke(Route route, CancellationToken cancellationToken, DynamicDictionary parameters, NancyContext context)
   at Nancy.Routing.DefaultRequestDispatcher.Dispatch(NancyContext context, CancellationToken cancellationToken)
   at Nancy.NancyEngine.InvokeRequestLifeCycle(NancyContext context, CancellationToken cancellationToken, IPipelines pipelines)


20-12-9 21:17:00.6|Warn|ReadarrErrorPipeline|Invalid request Validation failed: 
 -- : Query successful, but no results were returned from your indexer. This may be an issue with the indexer or your indexer category settings.
20-12-9 21:17:00.6|Trace|Http|Res: 25 [POST] /api/v1/indexer/test: 400.BadRequest (2900 ms)
20-12-9 21:17:00.6|Debug|Api|[POST] /api/v1/indexer/test: 400.BadRequest (2900 ms)
20-12-9 21:17:04.6|Trace|Scheduler|Pending Tasks: 0
```

**Comment by bakerboy448** [comment]
The test passes.

No results were available from your indexer; check your categories.

Also don’t use the jackett /all endpoint

**Comment by averri** [comment]
Hi @bakerboy448, thanks for your reply. I have a few questions, in order to understand what's happening.

1. The test in the UI **did not pass for Readarr**, see the screenshot:

![image](https://user-images.githubusercontent.com/1898447/101759942-213b2700-3ad2-11eb-97ca-f69983f0a2a3.png)

2. It is expected the configuration to work in the exact same way as Radarr, I have the Radarr working with the same configuration returning results. All the functionality of Readarr is similar to Radarr, so it's not clear to me why Readarr is returning an error. Think about the usability perspective.

This is the Radarr using the same URL and API from above, **test passing**:

![image](https://user-images.githubusercontent.com/1898447/101760787-3bc1d000-3ad3-11eb-9644-39c5a3b93e13.png)



3. Why not using the Jackett `/all` endpoint!? It's very convenient to use it, not using it contradicts the purpose of having a indexer agregattor like Jackett.

What is your suggestion for the URL to put on Readarr for querying Jackett?
