### ISSUE TITLE
Error on search for audiobooks

### ISSUE THREAD

**Issue by fpy-homeb** [Readarr/Readarr#912]
**Describe the bug**
Error when searching for audiobooks

**To Reproduce**

**Platform Information (please complete the following information):**
 - OS: raspbian os32
 - Docker: yes
 - Mono or .NET Version (System -> Status): .NET 5.0.4
 - Browser and Version (Only needed for UI issues): n/a
 - Readarr Version: 0.1.0.542
 - Readarr Branch: nightly

**Trace Logs**

21-3-22 23:24:04.4|Fatal|ReadarrErrorPipeline|Request Failed. POST /api/v1/author

[v0.1.0.542] code = ReadOnly (8), message = System.Data.SQLite.SQLiteException (0x800017FF): attempt to write a readonly database
attempt to write a readonly database
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in /_/Dapper/SqlMapper.cs:line 1064
   at Dapper.SqlMapper.QueryMultipleImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 1024
   at Dapper.SqlMapper.QueryMultiple(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 1000
   at NzbDrone.Core.Datastore.BasicRepository`1.Insert(IDbConnection connection, IDbTransaction transaction, TModel model) in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 189
   at NzbDrone.Core.Datastore.BasicRepository`1.Insert(TModel model) in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 147
   at NzbDrone.Core.Datastore.BasicRepository`1.Upsert(TModel model) in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 296
   at NzbDrone.Core.Http.CachedHttpResponseService.Get(HttpRequest request, Boolean useCache, TimeSpan ttl) in D:\a\1\s\src\NzbDrone.Core\Http\CachedHttpResponseService.cs:line 52
   at NzbDrone.Core.MetadataSource.Goodreads.GoodreadsProxy.GetAuthorInfo(String foreignAuthorId, Boolean useCache) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\Goodreads\GoodreadsProxy.cs:line 88
   at NzbDrone.Core.Books.AddAuthorService.AddSkyhookData(Author newAuthor) in D:\a\1\s\src\NzbDrone.Core\Books\Services\AddAuthorService.cs:line 100
   at NzbDrone.Core.Books.AddAuthorService.AddAuthor(Author newAuthor, Boolean doRefresh) in D:\a\1\s\src\NzbDrone.Core\Books\Services\AddAuthorService.cs:line 51
   at Readarr.Api.V1.Author.AuthorController.AddAuthor(AuthorResource authorResource) in D:\a\1\s\src\Readarr.Api.V1\Author\AuthorController.cs:line 139
   at lambda_method165(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Readarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Readarr.Http\Middleware\BufferingMiddleware.cs:line 27
   at Readarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Readarr.Http\Middleware\IfModifiedMiddleware.cs:line 40
   at Readarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Readarr.Http\Middleware\CacheHeaderMiddleware.cs:line 32
   at Readarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Readarr.Http\Middleware\UrlBaseMiddleware.cs:line 26
   at Readarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Readarr.Http\Middleware\VersionMiddleware.cs:line 27
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
SQL: 
==== Begin Query Trace ====

QUERY TEXT:
INSERT INTO HttpResponse ("Url", "LastRefresh", "Expiry", "Value", "StatusCode") VALUES (@Url, @LastRefresh, @Expiry, @Value, @StatusCode); SELECT last_insert_rowid() id

PARAMETERS:
Id = [0]
Url = ["\"https://www.goodreads.com/author/show/10746.xml?key=dcX1YH52UMjs6lznO2MuSg&_nc=1&exclude_books=true\""]
LastRefresh = ["2021-03-22T23:24:04.2073563Z"]
Expiry = ["2021-04-21T23:24:04.2073563Z"]
Value = ["\"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<GoodreadsResponse>\n  <Request>\n    <authentication>true</authentication>\n      <key><![CDATA[dcX1YH52UMjs6lznO2MuSg]]></key>\n    <method><![CDATA[author_show]]></method>\n  </Request>\n  <author>\n  <id>10746</id>\n  <name>Jim Butcher</name>\n  <link><![CDATA[https://www.goodreads.com/author/show/10746.Jim_Butcher]]></link>\n  <fans_count type=\"integer\">42776</fans_count>\n  <author_followers_count type=\"integer\">42776</author_followers_count>\n  <large_image_url><![CDATA[https://images.gr-assets.com/authors/1400640324p7/10746.jpg]]></large_image_url>\n  <image_url><![CDATA[https://images.gr-assets.com/authors/1400640324p5/10746.jpg]]></image_url>\n  <small_image_url><![CDATA[https://images.gr-assets.com/authors/1400640324p2/10746.jpg]]></small_image_url>\n  <about><![CDATA[Jim Butcher is the author of the Dresden Files, the Codex Alera, and a new steampunk series, the Cinder Spires. His resume includes a laundry list of skills which were useful a couple of centuries ago, and he plays guitar quite badly. An avid gamer, he plays tabletop games in varying systems, a variety of video games on PC and console, and LARPs whenever he can make time for it. Jim currently resides mostly inside his own head, but his head can generally be found in his home town of Independence, Missouri.<br /><br />Jim goes by the moniker Longshot in a number of online locales. He came by this name in the early 1990â€²s when he decided he would become a published author. Usually only 3 in 1000 who make such an attempt actually manage to become published; of those, only 1 in 10 make enough money to call it a living. The sale of a second series was the breakthrough that let him beat the long odds against attaining a career as a novelist.<br /><br />All the same, he refuses to change his nickname.<br />]]></about>\n  <influences></influences>\n  <works_count>197</works_count>\n  <gender>male</gender>\n  <hometown>Independence, Missouri</hometown>\n  <born_at></born_at>\n  <died_at></died_at>\n  <goodreads_author>true</goodreads_author>\n    <user>\n  <id type=\"integer\">6559504</id>\n</user>\n\n\n</author>\n\n</GoodreadsResponse>\n\""]
StatusCode = [200]

==== End Query Trace ====

21-3-22 23:24:04.5|Trace|Http|Res: 20 [POST] /api/v1/author: 500.InternalServerError (1623 ms)
21-3-22 23:24:04.5|Debug|Api|[POST] /api/v1/author: 500.InternalServerError (1623 ms)

**Comment by ta264** [comment]
1) You don't have write access to your database
2) Audiobooks are not yet supported

**Comment by fpy-homeb** [comment]
@ta264 cheers, 
Just installed latest and it seems to have fixed permissions issue. 
2. My bad
